### ISSUE TITLE
Git clone and then run examples success,but there is 404 when access curl http://localhost:9000/graphql

### ISSUE THREAD

**Issue by wufuwei** [graphql-java-kickstart/graphql-spring-boot#110]
➜  example git:(master) ✗ pwd
/Users/davidwu/Documents/git_workspace/graphql-spring-boot/example
➜  example git:(master) ✗ curl http://localhost:9000/actuator/health
{"status":"UP"}%                                                                                                                                                              ➜  example git:(master) ✗ curl http://localhost:9000/graphql
{"timestamp":"2018-08-21T06:39:07.636+0000","status":404,"error":"Not Found","message":"No message available","path":"/graphql"}%

**Comment by oliemansm** [comment]
@wufuwei Just ran the example in *example* without problems. Can open graphiql and can run queries to `/graphql` as well. Provide some more information what you're trying to do and the error you see if you're still facing this issue.

**Comment by oliemansm** [comment]
Since I wasn't able to reproduce this issue and haven't heard back from you I'm going to assume you were able to fix it and will close this issue. If you're still having problems, you can re-open it and provide some more detail.
