### ISSUE TITLE
GraphQL Servlet Bypassing API Interceptor

### ISSUE THREAD

**Issue by pclnzwang** [graphql-java-kickstart/graphql-spring-boot#120]
I have the same issue with the post below: GraphQL servlet is bypassing our customized API Interceptor. Would this be a bug?

https://stackoverflow.com/questions/50805390/spring-boot-graphqlservlet-bypassing-handlerinterceptor-mechanics

**Comment by pclnzwang** [comment]
<img width="1699" alt="screen shot 2018-09-13 at 15 31 37" src="https://user-images.githubusercontent.com/37309883/45511134-229e0d80-b76a-11e8-9300-a73a7697b6e2.png">

I guess this is caused by using AbstractGraphQLHttpServlet class which doesn't not apply handler execution chain.

**Comment by oliemansm** [comment]
I'm not familiar with these interceptors, but looking at the StackOverflow issue and Google, you mean this Spring specific feature as described in the following article, correct? https://www.baeldung.com/spring-mvc-handlerinterceptor.

The `AbstractGraphQLHttpServlet` is plain Java, not framework specific. So it's not supposed to call any Spring related methods. It is wrapped in a `ServletRegistrationBean` by this spring starter to expose it to Spring. Since that brings it in the Spring ecosystem I would say that a correct configuration of those interceptors should work. Can you share an example in a repo reproducing this issue?

**Comment by pclnzwang** [comment]
Thank you for your explanation!

**Comment by seetharamani** [comment]
@pclnzwang Did this ever work for you?

**Comment by zhewang2** [comment]
Thank you for your input. We only need a way to trigger the interceptor with spring request. I created a customized filter and put into configuration class like below.

`class ApiInterceptorFilter : GenericFilterBean() {

    override fun doFilter( request: ServletRequest?, response: ServletResponse?, chain: FilterChain? ) {
        val apiInterceptor = APIInterceptor()

        val handler = HandlerMethod( EmptyHandler(), ClassUtils.getMethod( EmptyHandler::class.java, "handle" ) )

        apiInterceptor.preHandle( request as HttpServletRequest, response as HttpServletResponse, handler )

        chain?.doFilter( request, response )

        apiInterceptor.afterCompletion( request, response, handler, null )
    }

}
`

`@Configuration
open class ApiContextConfig @Autowired constructor( private val factory: AutowireCapableBeanFactory ) : WebMvcConfigurer {

    override fun configureDefaultServletHandling( configurer: DefaultServletHandlerConfigurer? ) {
        configurer?.enable()
    }

    @Bean
    open fun apiFilter(): FilterRegistrationBean<ApiInterceptorFilter> {
        return FilterRegistrationBean<ApiInterceptorFilter>().let {
            ApiInterceptorFilter().let { filter ->
                factory.autowireBean( filter )

                it.filter = filter
            }

            it.addUrlPatterns( "/graphql/*" )

            it.setName( ApiInterceptorFilter::class.java.simpleName )

            it.order = 1

            it
        }
    }

}
`

**Comment by Mu-YanG** [comment]
I use  springBoot   @WebFilter(urlPatterns = "/*", filterName = "test")   




@Component
@WebFilter(urlPatterns = "/*", filterName = "test")
public class TestFilter implements Filter {
 
	@Override
    public void init(FilterConfig arg0) throws ServletException {
		System.out.println(" Filter  init ");
	}
 
	@Override
	public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain filterChain)
			throws IOException, ServletException {
		System.out.printf(" Filter  do ");
		System.out.println(((HttpServletRequest) servletRequest).getRequestURI());
		filterChain.doFilter(servletRequest, servletResponse);
	}
 
	@Override
	public void destroy() {
		System.out.println(" Filter destroy");
	}
 
}

**Comment by qiulingyun** [comment]
I tried to inject the interceptor into the instrument and works
```

@Bean
    public Instrumentation authXInstrumentation(@Autowired AuthXInterceptor authXInterceptor, @Autowired ApplicationContext applicationContext) {
        BiFunction<FieldAndArguments, FieldValidationEnvironment, Optional<GraphQLError>> authRule = (fieldAndArguments, environment) -> {
            ExecutionContext context = environment.getExecutionContext();

            DataFetcher<?> dataFetcher = context.getGraphQLSchema().getCodeRegistry().getDataFetcher(
                    FieldCoordinates.coordinates(
                            fieldAndArguments.getParentType().getName(),
                            fieldAndArguments.getFieldDefinition().getName()
                    ),
                    fieldAndArguments.getFieldDefinition());

            HttpServletRequest request = context.getGraphQLContext().get(HttpServletRequest.class);
            HttpServletResponse response = context.getGraphQLContext().get(HttpServletResponse.class);
            Method resolverMethod = (Method)ReflectionUtils.getFieldVal(true, dataFetcher, "resolverMethod");
            HandlerMethod handlerMethod = new HandlerMethod(
                    applicationContext.getBean(resolverMethod.getDeclaringClass()),
                    resolverMethod
            );  // wrap method to Handler, used to adapt authXInterceptor

            boolean success = false;
            try {
                success = authXInterceptor.preHandle(request, response, handlerMethod);
            } catch (Exception e) {
                return Optional.of(environment.mkError("AuthXInterceptor exception: " + e.getMessage(), fieldAndArguments));
            }

            if (!success) {
                return Optional.of(environment.mkError("Authentication failed!", fieldAndArguments));
            }

            return Optional.empty();
        };

        SimpleFieldValidation fieldValidation = new SimpleFieldValidation();
        for (String path : graphqlAuthPathList) {
            fieldValidation.addRule(ResultPath.parse(path), authRule);
        }

        return new FieldValidationInstrumentation(fieldValidation);
    } 

```
