### ISSUE TITLE
Graphiql endpoint for subscriptions not working

### ISSUE THREAD

**Issue by senzzzi** [graphql-java-kickstart/graphql-spring-boot#122]
The property graphiql.endpoint.subscriptions looks like it doesn't map to anything or it doesn't have any effect although it shows on the documentation. I am using the latest release version "5.0.2". It there a release missing for graphiql starter?

**Comment by oliemansm** [comment]
There was a problem with getting the latest release out. Found the culprit though, so I'm hoping the next release will become available this week. The documentation shows the settings for 5.0.3 already.

**Comment by oliemansm** [comment]
Were you able to verify it's solved with 5.0.3 now?

**Comment by senzzzi** [comment]
yes @oliemansm, thanks. But the property doesn't appear on the meta-inf file and there's no intellisense for it.

**Comment by oliemansm** [comment]
Added the properties in the meta-inf file. Thanks for pointing it out.

**Comment by oliemansm** [comment]
@spencerolsen The `groupId` has been updated to `com.graphql-java-kickstart`. It's now available at: https://mvnrepository.com/artifact/com.graphql-java-kickstart/graphiql-spring-boot-starter.

**Comment by spencerolsen** [comment]
@oliemansm Thanks.
