### ISSUE TITLE
Disable schema introspection query 

### ISSUE THREAD

**Issue by alexcibotari** [graphql-java-kickstart/graphql-spring-boot#124]
Hello ,

Is there any possibility to disable GraphQL query? related to 
```
query {
__type {
...
}
__schema {
...
}
}
``` 

For example if I would like to hide my schema and types for outside world.

**Comment by oliemansm** [comment]
Where are you seeing this?

**Comment by oliemansm** [comment]
**graphql-java** has a feature to disable the introspection query: https://graphql-java.readthedocs.io/en/latest/execution.html?highlight=introspection#limiting-field-visibility. The do warn that it puts your server in contravention of the graphql specification and expectations of most clients so use this with caution. 

So we could add a property in the starter, e.g. `introspection.enabled=false`, pass it to **graphql-java-tools** somehow and use it when we build the `GraphQLSchema` in `SchemaObjects`.

**Comment by alexcibotari** [comment]
It will be very great if we can do it with one configuration field
