### ISSUE TITLE
Voyager static resources not served if app context is not root

### ISSUE THREAD

**Issue by pdemartino** [graphql-java-kickstart/graphql-spring-boot#125]
When the application has a context different than root Voyager fails to start because its static resources are not found 404. This is because the HTML is configured as they were always in the root directory which is not the case.

Steps to reproduce:
- Define a context for your application (eg. "abc")
- configure your context-path accordingly (server.servlet.context-path=/abc)
- start your application
- navigate to voyager (http://localhost:8080/abc/voyager
- start your application and specify a context: -Dserver.servlet.context-path=<your_context>
- navigate to http://localhost:8080/abc/voyager
> Static resources will fail with a 404
> Voyager won't start

**Comment by oburgosm** [comment]
I have this issue with version 5.8.1 and 5.9.0

**Comment by c7tt8nt2p** [comment]
> I have this issue with version 5.8.1 and 5.9.0

I still have the same issue with v 5.10.0
Adding `voyager.static.basePath=${server.servlet.context-path}/` should fix the issue. The `voyager.static.basePath` is not a known property because it is not in the `spring-configuration-metadata.json`

**Comment by den-ligin** [comment]
still have the same issue with 7.0.1

**Comment by ravikrn13** [comment]
still have the same issue with 8.1.1
