### ISSUE TITLE
graphql.servlet.use-default-objectmapper configuration

### ISSUE THREAD

**Issue by alexcibotari** [graphql-java-kickstart/graphql-spring-boot#140]
1.  How Can I have two separate ObjectMapper for Spring and GraphQL ?
2. How I can have one only ? only from Spring ? I would like to configure Jackson from application.yaml

At the moment after update to the latest version my test fail because of one deserialization configuration that is by default enabled in spring but not in GraphQL, and looks GraphQL objectmapper  override Spring objectmapper 

In spring we have next default configuration 
```new ObjectMapper()
  .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
```

error 
```
org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Unrecognized field "xxx" (class ObjectX), not marked as ignorable; nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "xxx" (class ObjectX), not marked as ignorable (one known property: "services"])
 at [Source: (ByteArrayInputStream); line: 3, column: 14] (through reference chain: java.util.ArrayList[0]->ObjectX["xxx"])
```

**Comment by senzzzi** [comment]
@alexcibotari you can create your own ObjectMapperProvider bean and configure the object mapper inside it as you need.

**Comment by alexcibotari** [comment]
ok, in this case, how i still have them both not conflicting.
Because after update all fail.

This is bad experience for any developer who will update to a news version

**Comment by oliemansm** [comment]
@alexcibotari Thanks for reporting, I'll try to reproduce this. I'm travelling this week though.

**Comment by kevcodez** [comment]
Upgrading from 5.0.2 to 5.0.4 broke my jackson object mapper aswell. As said, the spring object mapper seems to be overwritten by the one graphql provides.
