### ISSUE TITLE
Object Mapper getting replaced on 5.0.4

### ISSUE THREAD

**Issue by jmccaull** [graphql-java-kickstart/graphql-spring-boot#147]
After upgrading from 5.0.2 to 5.0.4 we began having serialization issues. Tracked the issue back to com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration overwriting our object mapper. Removing the bean definition: 
```
    @Bean
    @ConditionalOnMissingBean
    public ObjectMapper objectMapper() {
        return new ObjectMapper();
    }
```
fixes our problem. Not sure if this is in relation to the addition of the use-default-objectmapper property, but setting it either way does not have any effect on our problem.

**Comment by oliemansm** [comment]
@jmccaull This is a known issue and already solved in the upcoming release.
