### ISSUE TITLE
Subscriptions don't work

### ISSUE THREAD

**Issue by dodalovic** [graphql-java-kickstart/graphql-spring-boot#150]
Hi,
just spotted that the example provided in `example-graphql-subscription` submodule doesn't work for subscriptions:

![image](https://user-images.githubusercontent.com/6358061/47271039-7cb59e00-d574-11e8-829e-9e52b65a8cf9.png)

I think this used to work before. 
Anyways - thanks for really good project!

**Comment by thischke** [comment]
Same for me. v5.0.4 worked, in v5.0.5 it is broken, in DevConsole I can see:

WebSocket connection to 'ws://localhost:9000/subscriptions' failed: Error during WebSocket handshake: Unexpected response code: 404

**Comment by 8och** [comment]
Changing the @ConditionalOnBean annotation back to @ConditionalOnClass for the serverEndpointExporter bean in the GraphQLWebsocketAutoConfiguration class fixes the problem.

Change this: 
`  @Bean
    @ConditionalOnMissingBean
    @ConditionalOnBean(ServerContainer.class)
    public ServerEndpointExporter serverEndpointExporter() {
        return new ServerEndpointExporter();
    }
`

to: 

`  @Bean
    @ConditionalOnMissingBean
    @ConditionalOnClass(ServerContainer.class)
    public ServerEndpointExporter serverEndpointExporter() {
        return new ServerEndpointExporter();
    }
`
