### ISSUE TITLE
Release 5.0.5 to Maven Central?

### ISSUE THREAD

**Issue by ryanlewis** [graphql-java-kickstart/graphql-spring-boot#152]
Just wondering if 5.0.5 will be published to Maven Central any time soon? Notably looking to implement the fixes in graphql-java-servlet from this PR https://github.com/graphql-java-kickstart/graphql-java-servlet/pull/112

The latest version on Maven Central currently appears to be 5.0.2 as of writing this issue.

https://mvnrepository.com/artifact/com.graphql-java/graphql-spring-boot-starter

**Comment by oliemansm** [comment]
@ryanlewis You're looking at the previous group id, you need to update that one to `com.graphql-java-kickstart`. See https://mvnrepository.com/artifact/com.graphql-java-kickstart/graphql-spring-boot-starter
