### ISSUE TITLE
Autogenerate Pojos?

### ISSUE THREAD

**Issue by jdavey** [graphql-java-kickstart/graphql-spring-boot#158]
Currently the schema and object creation is two separate workflows. 

For example, I had an object type of `Foo` I wanted exposed I would include it in both my .graphqls file as well as implementing the pojo

```graphql
type Foo {
    bar: String
}
```

```java 
@Data
public class Foo {
     private final String bar;
}
```

Since the graphql tools are already inspecting the .graphqls file, it would be great to autogenerate this Foo pojo to avoid duplication

**Comment by oliemansm** [comment]
This isn't something we'll be implementing, since most use cases will have some actual logic to handle. They're two separate concepts.
