### ISSUE TITLE
WAR deployment to Tomcat 9 throws IllegalStateException exception

### ISSUE THREAD

**Issue by khteh** [graphql-java-kickstart/graphql-spring-boot#165]
IllegalStateException thrown when GraphQL project built as WAR deployed to Tomcat 9:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverEndpointExporter' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: javax.websocket.server.ServerContainer not available
```
Relevant bug and suggested fix in spring.io: https://jira.spring.io/browse/SPR-12109

**Comment by oliemansm** [comment]
@khteh You're referencing an apparently known bug in Spring about this. So sounds like they are working on a fix for that one. What do you expect by opening this issue here then? Is there something now that needs to be updated here to fix it?

**Comment by khteh** [comment]
@oliemansm, can you provide a link to the known issue in spring? Thanks.

**Comment by dengyuan1989** [comment]
I have the same issue by WAR deploy with Tomcat 8.5.35

**Comment by oliemansm** [comment]
@khteh I'm referring to the known issue and link you reported here yourself: https://jira.spring.io/browse/SPR-12109

**Comment by khteh** [comment]
https://jira.spring.io/browse/SPR-17599

**Comment by shinobi81** [comment]
Hi, I don't know if this info could be useful 
I got the same error:


> 2019-03-04 10:07:19.221 ERROR 4903 --- [           main] c.o.m.g.b.e.GraphQLErrorHandlerFactory   : Cannot load class graphQLServletRegistrationBean. Error creating bean with name 'graphQLServletRegistrationBean': Requested bean is currently in creation: Is there an unresolvable circular reference?
> 2019-03-04 10:07:19.246 ERROR 4903 --- [           main] c.o.m.g.b.e.GraphQLErrorHandlerFactory   : Cannot load class serverEndpointExporter. Error creating bean with name 'serverEndpointExporter' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebsocketAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: javax.websocket.server.ServerContainer not available


This is my configuration:
Spring boot version: **2.1.3.RELEASE**
graphql-spring-boot-starter version: **5.4.1 and later**


> java -version
> openjdk version "11" 2018-09-25
> OpenJDK Runtime Environment 18.9 (build 11+28)
> OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)


> mvn -version
> Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
> Maven home: /usr/local/Cellar/maven@3.5/3.5.4/libexec
> Java version: 11, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/openjdk-11.jdk/Contents/Home
> Default locale: en_IT, platform encoding: UTF-8
> OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

**Comment by oliemansm** [comment]
@shinobi81 Your issue should be fixed with the next release 5.7.2. And hopefully that will fix the issue for this original issue regarding WAR deployment as well, but not sure about that.

**Comment by khteh** [comment]
When is the estimated release date?

**Comment by oliemansm** [comment]
This weekend, maybe today even. Just going through the several projects to see if there are any issues I can fix and include. If you have a clone of the project you could pull in the latest changes and build a local snapshot to verify if it's working for you.

**Comment by unchai** [comment]
Hello~ I'm using dependencies below, but got error:

spring-boot version : **2.1.4.RELEASE**
graphql-spring-boot-starter version : **5.8.1**
tomcat version : **8.5.40**

> Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: javax.websocket.server.ServerContainer not available
	at org.springframework.web.context.support.ServletContextAwareProcessor.postProcessBeforeInitialization(ServletContextAwareProcessor.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:414)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	... 62 more

**Comment by unchai** [comment]
I avoided the error in the following ways.

```diff
-@SpringBootApplication
+@SpringBootApplication(exclude = {
+    GraphQLWebsocketAutoConfiguration.class
+})
public class Application extends SpringBootServletInitializer {
...
}
```

**Comment by sutra** [comment]
Seems issue resolved after I upgrade spring boot from 2.1.5 to 2.1.6.

**Comment by oliemansm** [comment]
Good to hear @sutra!

**Comment by oliemansm** [comment]
@khteh Can you verify that upgrading Spring Boot to 2.1.6.RELEASE fixes the issue for you too?

**Comment by khteh** [comment]
Ok. I will verify and close it if it works. Recently changed to .net core
role.

**Comment by sutra** [comment]
> Seems issue resolved after I upgrade spring boot from 2.1.5 to 2.1.6.

Seems not works every time.
Added `graphql.servlet.websocket.enabled=false` in `application.properties` now, and get it working. See 
```
@ConditionalOnProperty(value = "graphql.servlet.websocket.enabled", havingValue = "true", matchIfMissing = true)
```
in `com.oembedler.moon.graphql.boot.GraphQLWebsocketAutoConfiguration`.

**Comment by slavap** [comment]
Tomcat 8.5.35, Spring Boot 2.2.1, graphql-spring-boot-starter 5.11.0
Getting this error, only graphql.servlet.websocket.enabled=false helps.

**Comment by SledgeHammer01** [comment]
Tomcat 9.0.30 Spring Boot 2.2.1 Starter 6.0.1. I get this error too... if I add, my app starts, but /altair page is blank... source:


  | <!doctype html>
-- | --
  | <html>
  |  
  | <head>
  | <meta charset="utf-8">
  | <title>Altair</title>
  | <base href="/vendor/altair/">
  | <meta name="viewport" content="width=device-width, initial-scale=1">
  | <link rel="icon" type="image/x-icon" href="favicon.ico">
  | <link rel="stylesheet" href="styles.css"/>
  |  
  | </head>
  |  
  | <body>
  | <script>
  | var properties = JSON.parse(`{}`);
  |  
  | window.__ALTAIR_ENDPOINT_URL__ = `/dtms/graphql`;
  | window.__ALTAIR_SUBSCRIPTIONS_ENDPOINT__ = `/dtms/subscriptions`;
  | window.__ALTAIR_INITIAL_QUERY__ = `${properties.defaultQuery}`;
  | window.__ALTAIR_INITIAL_VARIABLES__ = `${properties.variables}`;
  | window.__ALTAIR_INITIAL_HEADERS__ = JSON.parse(`{"Accept":"application/json","Content-Type":"application/json"}`);
  |  
  | </script>
  | <app-root>
  | <style>
  | .loading-screen {
  | /*Prevents the loading screen from showing until CSS is downloaded*/
  | display: none;
  | }
  |  
  |  
  |  
  |  
  | </style>
  | <div class="loading-screen styled">
  | <div class="loading-screen-inner">
  | <div class="loading-screen-logo-container">
  | <img src="assets/img/logo_350.svg" alt="Altair">
  | </div>
  | <div class="loading-screen-loading-indicator">
  | <span class="loading-indicator-dot"></span>
  | <span class="loading-indicator-dot"></span>
  | <span class="loading-indicator-dot"></span>
  | </div>
  | </div>
  | </div>
  | </app-root>
  | <script type="text/javascript" src="runtime.js"></script>
  | <script type="text/javascript" src="polyfills.js"></script>
  | <script type="text/javascript" src="main.js"></script>
  | </body>
  |  
  | </html>
  |

**Comment by shinobi81** [comment]
Tomcat 9.0.31 should fix this bug
https://github.com/spring-projects/spring-framework/issues/22131

**Comment by azunke** [comment]
Thanks @slavap Your solution worked. Everything was ok with me locally using Oracle JDK. But as soon as i moved to OpenJDK, it started giving me error. The solution @slavap provided worked.

**Comment by oliemansm** [comment]
So proven solution is to set `graphql.servlet.websocket.enabled=false` for this situation.
