### ISSUE TITLE
GraphQLErrorHandlerFactory does not find ExceptionHandlers

### ISSUE THREAD

**Issue by juriad** [graphql-java-kickstart/graphql-spring-boot#166]
1) a method annotated with ExceptionHandler is not found if the bean is a CGLib proxy (e.g. Configuration) or if the method is defined in an ancestor

2) a bean may not be found in `context.getBean(className)` as the bean can be registered in the application context with a name different from its fully qualified name - this leads to NoSuchBeanDefinitionException and application failure

I managed to overcome both issues with:
```
@Component("com.company.x360.ExceptionHandlers")
class ExceptionHandlers {

    @ExceptionHandler(Throwable::class)
    fun handleException(e: Throwable): GraphQLError {
```

**Comment by Guchelkaben** [comment]
@juriad thanks for the solution but do i miss sth? my handleException got never called.

`@Component("de.hermes.myh.pro.orderlistservice.graphql.exception.Test")
public class Test {

    @ExceptionHandler({Throwable.class, Exception.class, CoercingSerializeException.class, UsernameNotFoundException.class})
    GraphQLError handleException(Throwable e) {
        System.out.println("Hello");
        return new ThrowableGraphQLError(e);
    }
}`

**Comment by oliemansm** [comment]
@Guchelkaben The exception handler is intended for exceptions that occur during execution of queries/mutations, but after the actual parsing. So those "internal" GraphQL handling exceptions are not covered by these. Think that's the reason it does work with your `UsernameNotFoundException`, but it doesn't with the `CoercingParseValueException`.

**Comment by Guchelkaben** [comment]
@oliemansm thx for your reply. Do you know how I can cover the "internal" GraphQL handling? Because these error messages from the "internal" GraphQL are not very accurate. Therefore I want to override them and assign better messages. 

Otherwise, our frontend must filter the returned string for explicit words, what kind of strange for me :D Instead I want to set a response code or sth else like bad request 400.

**Comment by oliemansm** [comment]
@Guchelkaben To be able to do this we need to extend the `GraphQLErrorFromExceptionHandler`. GraphQL throws various types of `GraphQLException` (the "internal" GraphQL errors I was mentioning), one of which is the `ExceptionWhileDataFetching`. That exception contains a certain `Throwable` cause, and the `@ExceptionHandler` annotation is currently used to find methods handling that specific cause.

What we could do is to also include the `GraphQLException` and its subclasses such as `CoercingParseValueException` in the search.

**Comment by oliemansm** [comment]
@Guchelkaben Could you try this again with 5.4.1-SNAPSHOT?

**Comment by Guchelkaben** [comment]
> @Guchelkaben Could you try this again with 5.4.1-SNAPSHOT?

How can I integrate 5.4.1-SNAPSHOT into my project?

**Comment by oliemansm** [comment]
Add the snapshot repository. See also https://www.graphql-java-kickstart.com/spring-boot/getting-started/

```
repositories {
    mavenCentral()
    maven { url "http://oss.jfrog.org/artifactory/oss-snapshot-local" }
}
```

**Comment by Guchelkaben** [comment]
> Add the snapshot repository. See also https://www.graphql-java-kickstart.com/spring-boot/getting-started/
> 
> ```
> repositories {
>     mavenCentral()
>     maven { url "http://oss.jfrog.org/artifactory/oss-snapshot-local" }
> }
> ```

Thx, and then replace the version of graphql-spring-boot-starter to 5.4.1-SNAPSHOT? Because if I do that maven don't download anything 🗡 

```
<dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-spring-boot-starter</artifactId>
            <version>5.4.1-SNAPSHOT</version>
        </dependency>
```

**Comment by oliemansm** [comment]
@Guchelkaben Apparently snapshots aren't configured properly for this project yet, thought it was sorry. I've released this in the meantime and it has already been confirmed to work now by other developers.
