### ISSUE TITLE
Is there any way to get HttpServletRequest from resolvers?

### ISSUE THREAD

**Issue by kentkrantz** [graphql-java-kickstart/graphql-spring-boot#169]
Context of HTTP is so important but we can not get it in resolvers, anyone have good idea?

**Comment by vincentDAO** [comment]
You only need add DataFetchingEnvironment parameter into your resolver method; then use Context of HTTP from there.

Normal resolver:
`public Account account(User user) {
    // your code here;
  }`

Resolver with DataFetchingEnvironment
`public Account account(User user, DataFetchingEnvironment env) {
    // your code here to extract http context from 'env';
    GraphQLContext context = env.getContext();
   Principal principal = context.getHttpServletRequest().get().getUserPrincipal();
  }`

**Comment by vincentDAO** [comment]
Can you check source of class https://github.com/graphql-java-kickstart/graphql-java-servlet/blob/master/src/main/java/graphql/servlet/GraphQLContext.java? the request is javax.servlet.http.HttpServletRequest

In my project, I can extract the IP; 

```
@Component
public class Mutate implements GraphQLMutationResolver {
     public Assessment start(GenericInput input, DataFetchingEnvironment env)  {
    graphql.servlet.GraphQLContext ctx = env.getContext();
    HttpServletRequest request = ctx.getHttpServletRequest().get();
    String submittedIp = request.getHeader("X-Forwarded-For");

```

**Comment by kentkrantz** [comment]
@vincentDAO I also used Spring Security, can't know where changed the HttpServletRequest.

**Comment by oliemansm** [comment]
@kentkrantz It's like @vincentDAO mentions, you can get it from that context. We're not doing anything special with it like setting a user agent or something..

**Comment by PhilippS93** [comment]
Seems that getHttpServletRequest does not exist anymore. Any advice?

**Comment by oliemansm** [comment]
See the release notes: https://github.com/graphql-java-kickstart/graphql-java-servlet/releases/tag/v8.0.0
