### ISSUE TITLE
Annotation Processor is missing on graphql-spring-boot-autoconfigure module

### ISSUE THREAD

**Issue by senzzzi** [graphql-java-kickstart/graphql-spring-boot#170]
The annotation processor is missing on build.gradle on the graphql-sping-boot-autoconfigure module. `annotationProcessor "org.springframework.boot:spring-boot-configuration-processor:$LIB_SPRING_BOOT_VER"`

**Comment by oliemansm** [comment]
@senzzzi You added this one in your PR right?

**Comment by senzzzi** [comment]
I did @oliemansm. It was easier for me to test.
