### ISSUE TITLE
Handling errors

### ISSUE THREAD

**Issue by triberraar** [graphql-java-kickstart/graphql-spring-boot#171]
I am trying to use the new feature to use ExceptionHandlers to map exceptions to nicer errors in graphql. I am not that successful with it though.  

I changed `graphql.servlet.exception-handlers-enabled` to true and see that errors are handled differently, so that is good.

I then made my own handler for my own exception type I tried both:
```
@Configuration
class ErrorConfig() {

    @ExceptionHandler
    fun handle(exception: ClientException): ThrowableGraphQLError {
        return ThrowableGraphQLError(exception, exception.description)
    }

}
```
and
```
@Configuration
class ErrorConfig() {

    @Bean
    fun customErrorHandler() = CustomErrorHandler()

}

class CustomErrorHandler() {

    @ExceptionHandler(ClientException::class)
    fun handle(exception: ClientException): GraphQLError {
        return ThrowableGraphQLError(exception, exception.description)
    }

}
```

Neither seems to work. I debugged a bit and `GraphQLErrorHandlerFactory` seems to be the factory that makes the errorhandlers, which are used in `GraphQLErrorFromExceptionHandler`. However this factory is called before my bean is created which leads `List<GraphQLErrorFactory> factories` to be empty and default back to the default error.

Do i miss something?

**Comment by oliemansm** [comment]
Is it possible for you to share a small example project to reproduce this?

**Comment by triberraar** [comment]
Hej,
I can't make an example project atm (too many dependencies on our own custom stuff) But i can show how i solved it. In the end i made a component that looks like this:
```

@Component(value = "com.package.backofficegateway.error.CustomErrorConfig")
class CustomErrorConfig {

    @ExceptionHandler(ClientException::class)
    fun handle(exception: ClientException) = GraphQLExceptionHandler.handle(exception)

    @ExceptionHandler(ServerException::class)
    fun handle(exception: ServerException) = GraphQLExceptionHandler.handle(exception)

    @ExceptionHandler(FeignException::class)
    fun handle(exception: FeignException) = GraphQLExceptionHandler.handle(exception)

}
```

It was very important to give it the name like that. I think this is because the spring default name would have been `customErrorConfig` and then the `GraphQLErrorHandlerFactory` says there is no bean called `com.package.backofficegateway.error.CustomErrorConfig`.
We have a seperate module for this stuff and it tried making this class an `@Configuration` that makes a bean of type `CustomErrorConfig` in several ways, but i couldn't get it to work with `@Configuration` so that we could use a custom spring boot starter for this. But i couldn't get it to work with @Configuration in any way so had to settle for @Component.

Hope this helps.

**Comment by triberraar** [comment]
Yeah i understand. Since i have a workaround, i don't think you should stress too much about this.
Time is scarce at this end too, that is keeping me from giving you an example :(

**Comment by JonathanIlk** [comment]
Spring Components with the GraphQLErrorHandler interface get called correctly with version 5.4.1, so this issue can be closed.
