### ISSUE TITLE
DataLoaderRegistry cannot be injected to Execution

### ISSUE THREAD

**Issue by kwang1** [graphql-java-kickstart/graphql-spring-boot#174]
When upgraded to GraphQL v11, the way to use dataloader has been changed.
Now, I don't find a way to inject the `DataLoaderRegistry ` to execution?
Is this a bug?

The version I have tried: 5.4

Thanks.

**Comment by oliemansm** [comment]
The way GraphQL Java uses dataloaders has changed, but the way to use it with graphql-spring-boot hasn't. The latest version is compatible with graphql-java v11 and has therefore been ugpraded to inect the `DataLoaderRegistry` in the execution. Just upgrading to the latest version of graphql-spring-boot should be sufficient.

Take a look at [example-request-scoped-dataloader](https://github.com/graphql-java-kickstart/graphql-spring-boot/tree/master/example-request-scoped-dataloader) for an example.

**Comment by oliemansm** [comment]
@kwang1 I'm assuming my comment was enough for you to get it working seeing I didn't see any response, so I'll close this issue. If it's not working for you yet, feel free to re-open the issue.

**Comment by kwang1** [comment]
Thanks, @oliemansm . 
Previously, I injected DataLoaderRegistry to instrumentation, this way doesn't work in latest version.
The problem was resolved by the way in the example. I think it will work.

Thanks,
Kyle.
