### ISSUE TITLE
GraphQL and Basic-Authentification

### ISSUE THREAD

**Issue by Thinkenterprise** [graphql-java-kickstart/graphql-spring-boot#184]
I would like to use Basic-Authentification and Method-Based-Security together with GraphQL. Since GraphQL is based on HTTP this should not be a problem similar to REST. Despite security configuration, however, I get back an error.

This is my security configuration
``` java
@Configuration
@EnableWebSecurity
@EnableGlobalMethodSecurity(prePostEnabled=true)
public class GraphQLSecurityConfiguration extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(AuthenticationManagerBuilder auth) throws Exception {      
   	 auth.inMemoryAuthentication()
        .withUser("user")
        .password("{noop}password")
        .roles("ADMIN");
    }
}
```

This is my query which returns 401.
```console
>curl -X POST -u user:password 'http://localhost:4000/graphql' -H 'Content-Type: application/json' -d '{"query":"{routes{id}}"}'
```
It is interesting that a normal @RestController in the same project works on / routes.

```console
curl -u user:password localhost:4000/routes
```

Any idea why that could be?

**Comment by oliemansm** [comment]
You're getting an access denied or forbidden error?

**Comment by Thinkenterprise** [comment]
@Thinkenterprise thanks for your answer. Here is an extract of the request and response header. It is 401 so UNAUTHORIZED.

```console
curl -X POST -u user:password 'http://localhost:4000/graphql' -H 'Content-Type: application/json' -v
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 4000 (#0)
* Server auth using Basic with user 'user'
> POST /graphql HTTP/1.1
> Host: localhost:4000
> Authorization: Basic dXNlcjpwYXNzd29yZA==
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> 
< HTTP/1.1 401 
< Set-Cookie: JSESSIONID=FD79BC41A88861B4FECC98F805D63DDD; Path=/; HttpOnly
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
* Authentication problem. Ignoring this.
< WWW-Authenticate: Basic realm="Realm"
< Content-Length: 0
< Date: Fri, 11 Jan 2019 11:27:47 GMT
< 
```

**Comment by Thinkenterprise** [comment]
I would like to protect the endpoint / graphql via Basic-Authentification. A permit on / graphql would prevent that.
``` java
 protected void configure(HttpSecurity http) throws Exception {

	http.httpBasic().and().authorizeRequests().antMatchers("/graphql").permitAll();
 }

```
If I do, however, I'll get the error 403 Forbidden next, even though I set @PreAuthorized. When I remove @PreAuthoized I get the same error 403.
``` java
public class RootQueryResolver implements GraphQLQueryResolver {

@PreAuthorize("hasRole('ADMIN')")
public List<Route> routes() {
	return routeRepository.findAll(); 
} 
```
@PreAuthorized works on the @RestController in the same project.

``` java
@RestController
public class RouteController {

 @GetMapping("routes")
 @PreAuthorize("hasRole('ADMIN')")
 public Iterable<Route> routes() {
       return routeRepository.findAll();
 }
```
Could it be a problem in the in your ```GraphQLWebAutoConfiguration```?
I push my security configuration on github.

**Comment by oliemansm** [comment]
You should disable CSRF, because otherwise posting won't work. So try something like this as your config:
```
@Configuration
public class GraphQLSecurityConfiguration extends WebSecurityConfigurerAdapter {

  @Override
  protected void configure(HttpSecurity http) throws Exception {
    http
        .csrf().disable()
        .authorizeRequests().anyRequest().authenticated()
        .and().httpBasic();

  }

  @Override
  protected void configure(AuthenticationManagerBuilder auth) throws Exception {
    auth.inMemoryAuthentication()
        .withUser("user")
        .password(passwordEncoder().encode("password"))
        .roles("ADMIN");
  }

  @Bean
  PasswordEncoder passwordEncoder() {
    return new BCryptPasswordEncoder();
  }
}
```

**Comment by Thinkenterprise** [comment]
@oliemansm **Thank you for the quick solution. Its working!!** I have not understood why `csrf` with `POST` are in trouble, but I'll make some research with that again. One realization for me is that the added servlets also have the same web security configuration. 

I have some question about GraphQL and webflux. Question: Is it planned to support webflux?
Should I open a new issue? 

Thanks again and a nice weekend.

**Comment by smfaizalkhan** [comment]
@oliemansm 

Thanks for your suggestion as i faced the same issue and it was solved .I have the same question as @Thinkenterprise 

@Thinkenterprise  Please share your research on why csrf with POST is in trouble.

Regards,
Faizal
