### ISSUE TITLE
Can't use a GraphQLSchemaProvider with the GraphQLWebAutoConfiguration

### ISSUE THREAD

**Issue by ryanjones71** [graphql-java-kickstart/graphql-spring-boot#192]
Commit 41fe82afd72ca7bb8cc72fae27beaa7dc9e966c3 changed the GraphQLWebAutoConfiguration from allowing a GraphQLSchemaProvider as an option. How do we continue to use a GraphQLSchemaProvider?

**Comment by oliemansm** [comment]
@ryanjones71 The current version in `master` still supports `GraphQLSchemaProvider`: https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/0da8ab6c9cc3706fc71a4692857a53689c49035b/graphql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.java#L191.

**Comment by oliemansm** [comment]
Closed due to inactivity.

**Comment by juriad** [comment]
I encountered the same issue. I want to provide my own GraphQLSchemaProvider bean while still using the autoconfiguration. It is not possible since the bean GraphQLSchema doesn't exist (it cannot exist since my schema is dynamic).
```
@ConditionalOnBean({GraphQLSchema.class})
public class GraphQLWebAutoConfiguration implements ApplicationContextAware {
```

**Comment by Blemicek** [comment]
The issue is also valid for the `GraphQLWebsocketAutoConfiguration`. The auto configurations should be conditional on `GraphQLSchema` or `GraphQLSchemaProvider`.

@oliemansm, could you reopen this issue or should we create a new one?
