### ISSUE TITLE
Where are the release notes after version 5.3.1?

### ISSUE THREAD

**Issue by breun** [graphql-java-kickstart/graphql-spring-boot#199]
I was tracking https://github.com/graphql-java-kickstart/graphql-spring-boot/releases to stay up to date, but just found that 5.4, 5.4.1, 5.5.0 and 5.6.0 have since been released to Maven Central. Where are the release notes for these versions? Could releases again be added to https://github.com/graphql-java-kickstart/graphql-spring-boot/releases so I can stay up to date via the GitHub RSS feed or is there now a new location to track releases?

**Comment by oliemansm** [comment]
There were some quick releases on request of contributors and didn't have enough time to update the release notes. Good to hear they are actually being used :) 
I'll update them and will do so in the future with new releases.
