### ISSUE TITLE
Upgrade from 5.5.0 to 5.6.0 breaks dependency injection

### ISSUE THREAD

**Issue by breun** [graphql-java-kickstart/graphql-spring-boot#200]
I have a working GraphQL application using version 5.5.0 of the GraphQL Spring Boot starter, but when I upgrade to version 5.6.0 my tests break with dependency injection errors like these:

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'graphQLContextBuilder' defined in URL [jar:file:/Users/breun/Projects/bol.com/PAL/pal-graphql-v1/target/pal-graphql-v1-1.0.0-SNAPSHOT.jar!/com/bol/service/pal/graphql/v1/GraphQLContextBuilder.class]: Unsatisfied dependency expressed through constructor parameter 5; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.dataloader.stats.StatisticsCollector' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

I do have an `@Configuration` class which has a `StatisticsCollector` bean, but it seems that's no longer found when using 5.6.0. Downgrading to 5.5.0 makes it all work again.

**Comment by oliemansm** [comment]
The main change between these two releases is the ability to customize batch request handling, which means the dependency to `graphql-java-servlet` was bumped to version 7.3.0 (which adds support for this). I would expect some more changes in `graphql-spring-boot` or `graphql-java-tools` to explain your issue. I'll run some tests to see if I can reproduce this.

**Comment by oliemansm** [comment]
@breun Do you explicitly specify versions of `graphql-java-servlet` and `graphql-java-tools` or do you rely on `graphql-spring-boot` to pull the correct versions in?

**Comment by oliemansm** [comment]
In 5.6.0 a bean named `graphQLConfiguration` is being created by `GraphQLWebAutoConfiguration` now. This has been changed because of that batch request handling support, but it conflicts with a bean in my own project with the same name. I'll change the name in the auto config class in the next release. Hope this'll fix the issue on your end too.

**Comment by breun** [comment]
Upgrading to 5.6.1 seems to work fine, thanks!
