### ISSUE TITLE
Missing Metrics Instrumentation readme section

### ISSUE THREAD

**Issue by senzzzi** [graphql-java-kickstart/graphql-spring-boot#203]
@oliemansm I forgot to add a section on Readme for this metrics instrumentation. Can you add a enhancement label to this issue and I will open a PR with the changes?

**Comment by oliemansm** [comment]
Tracing and metrics section has been added to the readme in the meantime: https://github.com/graphql-java-kickstart/graphql-spring-boot#tracing-and-metrics.
