### ISSUE TITLE
Add Altair starter

### ISSUE THREAD

**Issue by Sparow199** [graphql-java-kickstart/graphql-spring-boot#204]
@Sparow199 Yeah you can easily add Altair in a similar way as well. Here's a simple implementation on JsFiddle: https://jsfiddle.net/imolorhe/zrjh2x08/

The only difference is that the assets (CSS and JS) have versioning on them. You can look up the versioning information in https://cdn.jsdelivr.net/npm/altair-static@2.0.7/build/dist/stats.json while building, or you can just use the exact versioned file names, based on the version of altair you would be supporting.

**Comment by Sparow199** [comment]
@imolorhe , it will be a nightmare to manage custom Altair version via application properties due to the versioning of CSS && JS assets. Altair is dynamique project with lot off features at each release so support only a specific version is very pity .

**Comment by imolorhe** [comment]
@Sparow199 Alright. I would publish the assets in `altair-static` without the versioning from the next version. That should solve your issue.

**Comment by Sparow199** [comment]
@imolorhe this is the complete list of Altair variables ?
- window.__ALTAIR_ENDPOINT_URL__ = '';
- window.__ALTAIR_SUBSCRIPTIONS_ENDPOINT__ = '';
- window.__ALTAIR_INITIAL_QUERY__ = '{ hello { id }}';
- window.__ALTAIR_INITIAL_VARIABLES__ = '{"number": 2}';

**Comment by Sparow199** [comment]
@imolorhe do you have an idea about the release of new Altair static version (with new files naming) ?

**Comment by imolorhe** [comment]
@Sparow199 Yes that's the complete list of available variables. The new release would be within the next couple of days. Might even be today, if I can complete a few things.

**Comment by Sparow199** [comment]
I think that i have an issue with the current version of Altair:
`message: "Http failure response for http://localhost:9000/assets/i18n/en-US.json: 404 OK"`
I should have the possibility to cutomize the assets URL to fit Spring Boot starter logic. If i enable the full CDNs fetching resources.

**Comment by imolorhe** [comment]
@Sparow199 Check the href of the <base> element in the `index.html`. That would determine how relative URLs are called. The same way it is set in the jsfiddle.

If you would prefer a more synchronous (realtime) communication, you could come on gitter so we don't have to wait for email notifications 😄

https://gitter.im/altair-graphql/Lobby
