### ISSUE TITLE
GraphiQL: subscriptionClientTimeout is set in seconds instead of ms

### ISSUE THREAD

**Issue by blaugold** [graphql-java-kickstart/graphql-spring-boot#207]
The [docs](https://github.com/apollographql/subscriptions-transport-ws#subscriptionclient) for `SubscriptionClient` say `timeout` is interpreted as ms. [GraphiQLController](https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/95663d40d26e19f854d9aaf28fc8b8759ae28271/graphiql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphiql/boot/GraphiQLController.java#L57) uses a default of `30`, which I asume is meant as seconds. [Here](https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/95663d40d26e19f854d9aaf28fc8b8759ae28271/graphiql-spring-boot-autoconfigure/src/main/resources/graphiql.html#L128) is where the timeout is substituted in the html template.
With defaults I get a lot of this line in my logs:
```
2019-03-05 14:09:46.653  WARN 31066 --- [pool-1-thread-5] g.s.i.ApolloSubscriptionKeepAliveRunner  : Session appears to be closed. Aborting keep alive
```
Which can be fixed by adding this to `application.yaml`
```yaml
graphiql:
  subscriptions:
     timeout: 30000
```

Thanks for a great library.

**Comment by oliemansm** [comment]
Fixed by #211
