### ISSUE TITLE
Any plan to replace Grahiql with Playground

### ISSUE THREAD

**Issue by elenigen** [graphql-java-kickstart/graphql-spring-boot#212]
It would be nice to replace GraphiQL with Playground
https://github.com/prisma/graphql-playground

The main feature I would like to have:
- Interactive, multi-column schema documentation
- Configuration of HTTP headers (so we can unlock the API whith a Bearer token)
- Tabs

**Comment by imolorhe** [comment]
@Sparow199 added an Altair starter sometime ago. Maybe you could use that?

**Comment by elenigen** [comment]
Yes, I just noticed it right after asking the question, but I still prefer the multi-column schema documentation from playground.
Thanks for point that out!

**Comment by Sparow199** [comment]
@elenigen , i'll add GraphQL Playground starter asap.

**Comment by elenigen** [comment]
oh, nice thanks, that's a good news! Altair was already a nice step upgrade since we have API keys in our service and it let the opportunity to our clients to try the API very easily by modifying the HTTP header.

**Comment by Sparow199** [comment]
Altair is a very active project, don't hesitate to create issues on it's
repository.

**Comment by elenigen** [comment]
Not sure if it's really a good practice to copy all the features from one project to another, in this case why not simply using the original project?  In my case, I was using before Graphiql before, then I discovered Playground which they say is built on top of Graphiql, so I don't feel it's a good idea to tell Graphiql people "you should add Playground features".  Then I discovered Altair and the good news was, it's already integrated in this kickstart project, so I adopted it, but it still looks like Playground has better features.

**Comment by oliemansm** [comment]
This has been added in 5.9.1 thanks to @BlasiusSecundus
