### ISSUE TITLE
altair starter altair.static.basepath is not used anywhere

### ISSUE THREAD

**Issue by sukyology** [graphql-java-kickstart/graphql-spring-boot#218]
i am not sure what it suppose to do. 

this is what i assume.

if i put basePath same as servlet context path (say /a)
and access {domain:port}/a
loaded altair page must get related vendor files from {domain:port}/a/vendor/ right?

however, regardless of what i specify on basePath, it always try to load file from {domain:port}/vendor/

searched staticBasePath usage on your AltAirController and found none

**Comment by ntatsumi** [comment]
I'm having the same issue. This issue prevents us from setting the Servlet context path other than root.

**Comment by imolorhe** [comment]
@sukyology @ntatsumi Is the base path set in the HTML when you view source of the app?

**Comment by sukyology** [comment]
> @sukyology @ntatsumi Is the base path set in the HTML when you view source of the app?

no, it is not specified in the html page.

**Comment by imolorhe** [comment]
@sukyology What is the `href` value of the `<base>` tag in the HTML?

**Comment by sukyology** [comment]
> @sukyology What is the `href` value of the `<base>` tag in the HTML?

/vendor/altair

**Comment by imolorhe** [comment]
@sukyology And that was not the `baseURL` you set?

Cc @Sparow199

**Comment by Sparow199** [comment]
I'll update Altair to last version with support of headers injection and
fix this issue

**Comment by sukyology** [comment]
@imolorhe 

yes whatever i set for altair.static.basepath it is always same. 

thank u.

**Comment by Sparow199** [comment]
@sukyology , should be fixed with this [PR](https://github.com/graphql-java-kickstart/graphql-spring-boot/pull/222)

**Comment by oliemansm** [comment]
v5.7.1 syncing to central now which contains this fix
