### ISSUE TITLE
Altair subscriptions don't work

### ISSUE THREAD

**Issue by RusticFlare** [graphql-java-kickstart/graphql-spring-boot#221]
## The Bug 

When I subscribe through Altair no information comes through. The screen stays like this:

![Screen Shot 2019-03-26 at 12 07 23](https://user-images.githubusercontent.com/5823777/54995958-f9372780-4fbf-11e9-97f2-47424b0a2d1c.png)

## My Setup

I have a schema

```graphql
type Query {
    hello : String!
}

type Subscription {
    helloWorld : String!
}
```

and resolvers (in Kotlin)

```kotlin
import com.coxautodev.graphql.tools.GraphQLQueryResolver
import com.coxautodev.graphql.tools.GraphQLSubscriptionResolver
import org.reactivestreams.Publisher
import org.springframework.stereotype.Component
import reactor.core.publisher.Flux

@Component
class Query : GraphQLQueryResolver {
    fun hello() = "Hello World!"
}

@Component
class Subscription : GraphQLSubscriptionResolver {
    fun helloWorld(): Publisher<String> = Flux.just("Hello", "World!")
}
```

and dependencies in `build.gradle`

```groovy
dependencies {
    compile 'com.graphql-java-kickstart:graphql-spring-boot-starter:5.7.0'
    runtime 'com.graphql-java-kickstart:altair-spring-boot-starter:5.7.0'
}
```

In Altair my subscription URL is : `ws://localhost:8080/graphql/subscriptions`

![Screen Shot 2019-03-26 at 12 09 54](https://user-images.githubusercontent.com/5823777/54996032-24217b80-4fc0-11e9-94aa-9e88e69704bb.png)

### The Subscription Works With Altair's "Copy as cURL" Feature

Altair's "Copy as cURL" feature gave me this:

```shell
curl 'http://localhost:8080/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'Origin: http://localhost:8080' --data-binary '{"query":"subscription {\n  helloWorld\n}","variables":{}}' --compressed
```
Which worked!
```
data: {"data":{"helloWorld":"Hello"}}

data: {"data":{"helloWorld":"World!"}}
```

### Queries Work

![Screen Shot 2019-03-26 at 11 48 21](https://user-images.githubusercontent.com/5823777/54994821-1ae2df80-4fbd-11e9-9085-616bee6a324c.png)

**Comment by Sparow199** [comment]
I updated Altair starter to v2.1.4, this issue should be fixed. I'm waiting the merge of the PR by @oliemansm

**Comment by RusticFlare** [comment]
@Sparow199 I was using the wrong subscription URL - Thank you! 

`ws://localhost:8080/subscriptions` worked 👍
