### ISSUE TITLE
Altair spring boot application properties

### ISSUE THREAD

**Issue by mrcasablr** [graphql-java-kickstart/graphql-spring-boot#229]
I like Altair and was wondering if altair variables are available as application properties just like graphiql

    window.ALTAIR_ENDPOINT_URL = '';
    window.ALTAIR_SUBSCRIPTIONS_ENDPOINT = '';
    window.ALTAIR_INITIAL_QUERY = '{ hello { id }}';
    window.ALTAIR_INITIAL_VARIABLES = '{"number": 2}';

**Comment by Sparow199** [comment]
@mrcasablr, this feature is available and fixed in the last PR, just wait for the  next release 😊.

**Comment by oliemansm** [comment]
@Sparow199 Just released it in v5.7.3. Could you describe these relevant properties in the README?
