### ISSUE TITLE
Setting editorTheme property does not change theme

### ISSUE THREAD

**Issue by grrttedwards** [graphql-java-kickstart/graphql-spring-boot#235]
For `graphiql` starter, according to the README, it's possible to set the `editorTheme` property to change the styles to a custom theme. Setting this theme seems to have no effect, it appears that a stylesheet must be linked in the generated html document, and this property does not do that.

See https://github.com/graphql/graphiql#applying-an-editor-theme

Related to #156

**Comment by oliemansm** [comment]
Fixed in next release, thanks for reporting.
