### ISSUE TITLE
Option to enable tracing level metrics without full tracing 

### ISSUE THREAD

**Issue by jmccaull** [graphql-java-kickstart/graphql-spring-boot#239]
Is there any opposition to having the option to enable full tracing metrics without having trancing data returned to the consumer? Essentially we would like to have the bean TracingInsturmentation with tracing-enabled still = false

**Comment by jmccaull** [comment]
@oliemansm, thoughts? did a quick PR: https://github.com/graphql-java-kickstart/graphql-spring-boot/pull/240. We would like to replace some of our custom metrics instrumentation with this

**Comment by oliemansm** [comment]
I've merged your PR, had no problem with this. Just come to think of it after the merge: could you update the README to document the possible props?

**Comment by jmccaull** [comment]
@oliemansm I think this should cover it, lmk if you want any more in depth. Thanks!
https://github.com/graphql-java-kickstart/graphql-spring-boot/pull/241

**Comment by oliemansm** [comment]
@jmccaull That'll do, thanks!

**Comment by IvBre** [comment]
Hello @jmccaull @oliemansm 
Thank you for this feature, this is exactly what we need. 
I've noticed though that `additional-spring-configuration-metadata.json` is still expecting a `Boolean` for `graphql.servlet.tracingEnabled` field which doesn't allow our application.yml config to set it to `metrics-only` which is a string. Am I missing something? 🤔 
I don't have rights to push to this repo, but the change would be something like this:

additional-spring-configuration-metadata.json:
``` 
...
    {
      "name": "graphql.servlet.tracingEnabled",
      "defaultValue": false,
      "type": "java.lang.String"
    },
...
```

**Comment by kijanowski** [comment]
Hello, I've been hit by the same thing and provided a PR: https://github.com/graphql-java-kickstart/graphql-spring-boot/pull/337
