### ISSUE TITLE
Mixing programmatically created schema and .graphql schema with @Component classes

### ISSUE THREAD

**Issue by asfernandes** [graphql-java-kickstart/graphql-spring-boot#245]
I'm creating a schema that is partially created programmatically and partially created via standard spring-boot graphql way, using a .graphql file and `@Component` classes.

That works fine while both parts were independent.

Now I need that the .graphql file reference types created programmatically, as well make the Java classes to return that objects.

Problem 1 is that I found no way to make the .graphql parsing known about the existence of the dynamic types.

Problem 2 is that even when trying to fix the problem 1, I need the Java classes to return `Map<String, Object>` for the dynamic types, as the dynamic types really return then in runtime, but that type seems to be incompatible with the declared name used in the .graphql file.

**Comment by oliemansm** [comment]
From your description I understand you're trying to mix graphql-java-tools with programmatic usage? So you have certain classes representing GraphQL types that aren't Beans? Have you tried adding those to the graphql-java-tools dictionary? You could expose a `Bean` of `SchemaParserDictionary` to which you've added all those dynamic types if possible.

Otherwise you might want to share a minimal example somehow to show and better explain your use case.

**Comment by asfernandes** [comment]
I've tried to use the dictionary and have asked about the issues I found in others related github issues, but I had no answear. From the problems I had, the amount of things I debugged and lack of support for my questions, I had just to give up and created a generator app that create the java / graphqls files to make the thing work.

My project is about code SQL queries in custom yaml file and publish them as graphql.

**Comment by oliemansm** [comment]
Right. Based on the info available here I wouldn't know any other way of approaching your problem. Since you've implemented a solution now I guess we can close this issue now, or do you have more questions about this?

**Comment by asfernandes** [comment]
You can close the issue if the mentioned title is not a requirement for this project, but if it is, I'm sure there are bugs. But I can't participate in the moment anymore. My complaints while trying to make the thing work was there, but no one tried to help.

https://github.com/graphql-java-kickstart/graphql-java-tools/issues/239#issuecomment-490049301
https://github.com/graphql-java-kickstart/graphql-java-tools/issues/269
https://github.com/graphql-java-kickstart/graphql-java-tools/issues/134#issuecomment-488808527
https://github.com/graphql-java-kickstart/graphql-java-tools/issues/113#issuecomment-488647898

**Comment by oliemansm** [comment]
Closing this issue then seeing this isn't a requirement for this project.
