### ISSUE TITLE
introspection-enabled doen't work

### ISSUE THREAD

**Issue by alexcibotari** [graphql-java-kickstart/graphql-spring-boot#247]
Hello,

Steps :

1. Disable introspection
```
graphql:
  tools:
    introspection-enabled: false
```
2. execute "IntrospectionQuery"

Result : Introspection Result
Expected Result : Empty response

**Comment by oliemansm** [comment]
In `graphql-java-tools` 5.6.1 the config has been changed to use the `CodeRegistry` instead of the deprecated way of `graphql-java`. Can you verify that solves it?

**Comment by oliemansm** [comment]
Just tested this and it works as expected against graphql-java-tools 5.6.1

**Comment by KylinDC** [comment]
Can you show more detail how to use `CodeRegistry` to config graqhql introspection?

**Comment by harshitvijayvargia** [comment]
Can someone guide me on how to disable the introspection via CodeRegistry ? I am using graphql java tools version 6.1.0
