### ISSUE TITLE
Why voyager has no search fields function?

### ISSUE THREAD

**Issue by jakaiwu** [graphql-java-kickstart/graphql-spring-boot#250]
I integrated voyager to my springboot project, but it seems that it has no search field function after visiting localhost:8080/voyager. It's different from the Voyager official live demo. Is it the feature that hasn't been added yet?

**Comment by oliemansm** [comment]
Not sure if the live demo is using the same version as used by the spring boot starter? It's a basic implementation atm, so not all possible options available to Voyager are exposed in this starter right now. That would be an enhancement.

**Comment by oliemansm** [comment]
See also #214
