### ISSUE TITLE
env.getCodeRegistry() is null

### ISSUE THREAD

**Issue by apollo7733** [graphql-java-kickstart/graphql-spring-boot#255]
@Override
	  public GraphQLFieldDefinition onField(SchemaDirectiveWiringEnvironment<GraphQLFieldDefinition> env) {
		System.err.println(env.getCodeRegistry());
		return env.getElement();
	  }

    // to be removed in a future version when all code is in the code registry
    DataFetcher getDataFetcher() {
        return dataFetcherFactory.get(newDataFetchingFactoryEnvironment()
                .fieldDefinition(this)
                .build());
    }

but env.getCodeRegistry() is null in SchemaDirectiveWiring

**Comment by oliemansm** [comment]
In `graphql-java-tools` version 5.6.1 the `CodeRegistry` is now passed on when constructing custom directives. Can you check whether that indeed solves this problem for you?

**Comment by oliemansm** [comment]
Just verified that with 5.9.1 this is indeed resolved. See the updated sample for directives as well: https://github.com/graphql-java-kickstart/samples/blob/master/directives/src/main/java/directives/UppercaseDirective.java.
