### ISSUE TITLE
CORS feature is not working

### ISSUE THREAD

**Issue by fabiocarvalho777** [graphql-java-kickstart/graphql-spring-boot#261]
In early 2017 [this issue](https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/8) was opened to report a bug in CORS support.

Even though apparently that issue was solved, I believe at some point later it was reintroduced. The expectation is CORS to be enabled by default, but it is not. Actually, even when you do explicitly enable it (in the Spring Boot config file, like seen below) CORS still doesn't work.

```
graphql:
  servlet:
    corsEnabled: true
```

Maybe some change reintroduced this bug. Was there a regression test added when this was fixed originally?

I am reporting this bug against version 5.9.0.

Thanks.

**Comment by oliemansm** [comment]
I just tested this with that version and works for me... Maybe something else is overriding this setting in your case?
