### ISSUE TITLE
Request: a reactive GraphQL Spring Boot starter

### ISSUE THREAD

**Issue by breun** [graphql-java-kickstart/graphql-spring-boot#265]
Currently `graphql-spring-boot-starter` makes it easy to setup a GraphQL server, but this starter uses `graphql-java-servlet` which depends on the Servlet API, which uses blocking I/O, and therefore cannot run on a non-blocking reactive runtime like the Netty-based Spring WebFlux.

For high concurrency use cases it would be great to be able to get away from the blocking one-thread-per-request model and be able to use reactive programming (or for instance Kotlin coroutines, which will be supported out of the box in Spring Boot 2.2) to implement a GraphQL server.

**Comment by breun** [comment]
I see https://github.com/graphql-java/graphql-java-spring does offer a WebFlux option, I might have to look into that.

**Comment by oliemansm** [comment]
Correct. First step for this project is refactoring the servlet lib to allow re-use of certain components, and then will look at supporting WebFlux.

Groeten,
Michiel
________________________________
Van: Nils Breunese <notifications@github.com>
Verzonden: Tuesday, July 2, 2019 12:57:38 PM
Aan: graphql-java-kickstart/graphql-spring-boot
CC: Subscribed
Onderwerp: Re: [graphql-java-kickstart/graphql-spring-boot] Request: a reactive GraphQL Spring Boot starter (#265)


I see https://github.com/graphql-java/graphql-java-spring does offer a WebFlux option, I might have to look into that.

**Comment by ahulyk** [comment]
any info on that?

**Comment by oliemansm** [comment]
Started to split up graphql-java-servlet to remove the servlet dependency: https://github.com/graphql-java-kickstart/graphql-java-servlet/pull/217

Extracted a separate graphql-java-tools starter that could be used with the webflux starter provided by graphql-java team: https://github.com/graphql-java-kickstart/graphql-spring-boot/pull/301

Started a sample using webflux with the graphql-java-kickstart libs: https://github.com/graphql-java-kickstart/samples/tree/master/spring-boot-webflux. This will be moved into a separate starter at some point. No support for batch requests or subscriptions yet.

Any contributions are appreciated.

**Comment by oliemansm** [comment]
Created a starter for webflux including support for subscriptions (based on websockets). Batched queries not yet supported though. 

It's not yet released, but you can see how it's used in the sample: https://github.com/graphql-java-kickstart/samples/tree/master/spring-boot-webflux

**Comment by cashZhang27** [comment]
> Created a starter for webflux including support for subscriptions (based on websockets). Batched queries not yet supported though.
> 
> It's not yet released, but you can see how it's used in the sample: https://github.com/graphql-java-kickstart/samples/tree/master/spring-boot-webflux

When will it be released ? Or a snapshot version is available

**Comment by oliemansm** [comment]
Released the starter just now. Can take a bit before it's available from maven central though.

**Comment by rajib77bd** [comment]
do you know when batch queries is going to be supported on webflux?
