### ISSUE TITLE
How to test in GraphQL Spring Boot 

### ISSUE THREAD

**Issue by alioth865** [graphql-java-kickstart/graphql-spring-boot#267]
Hello, im new in GraphQL world, I'm doing my first API with this technology and I have one doubt. It's possible with JUnit do testing for my GraphQLResolver, GraphQLMutationResolver or GraphQLQueryResolver? Or simply don't have sence doing? If is possible doing, please can you share me someone class than example? 
Sorry for my bad english! 
Best regards

**Comment by oliemansm** [comment]
As mentioned in the documentation there's a test starter available which exposes the `@GraphQLTest` annotation. Take a look at https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/master/example-graphql-tools/src/test/java/com/graphql/sample/boot/GraphQLToolsSampleApplicationTest.java for an example how to use it.

**Comment by anrolmar** [comment]
Hi. I used the example, but I retrieved a 404 error. If I look around the code, the error is this piece of code: 
`ResponseEntity<String> response = this.restTemplate.exchange(this.graphqlMapping, HttpMethod.POST, request, String.class, new Object[0]);`

`this.graphqlMapping` has the value /graphql.

Is this correct?

**Comment by FranBisquerra** [comment]
Hi! I'm trying to use the test library as I found it pretty easy and useful and I'm facing the same 404 error.. In my case I found that is related with the

`@RunWith(SpringRunner::class) @GraphQLTest`

annotations, if I use the 

`@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)` 

it works perfectly, I can't seem to find the reason as `@GraphQLTest` is supposed to configure the environment the same way. 

Anyone that knows what the problem might be?

Thx!

**Comment by oliemansm** [comment]
[This test class](https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/4c7cdbaa8b576134bad0370add9241207e267904/example-graphql-tools/src/test/java/com/graphql/sample/boot/GraphQLToolsSampleApplicationTest.java) uses `@GraphQLTest` too without specifying RANDOM_PORT specifically either and is working fine.

You shouldn't have to add this:
```java
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
```
since that's already set on the `@GraphQLTest` annotation.

Maybe it's a Kotlin config issue?

**Comment by FranBisquerra** [comment]
Hi! I've been trying for a while to find the problem but didn't find anything.. Reading the annotation doc I realized that It was not loading the full application context, and I need it anyway, so I ended up using the `@SpringBootTest` annotation. 

Thank you for the support!

**Comment by KurtStauffer** [comment]
Hi, I'm trying to use `@GraphQLTest` annotation and receiving the following error...

```
Caused by: com.coxautodev.graphql.tools.SchemaClassScannerError: No Root resolvers for mutation type 'Mutation' found!  Provide one or more com.coxautodev.graphql.tools.GraphQLMutationResolver to the builder.
```

My resolvers are set up properly and work without issue when running the app locally. Just not working with this test annotation. Here's my simple test class causing the failure...

```
@GraphQLTest
public class MyTest {
  @Autowired private GraphQLTestTemplate graphQLTestTemplate;

  @Test
  public void test() throws IOException { }
}
```
Any help would be appreciated. Thanks!

**Comment by khteh** [comment]
What package to include in pom.xml for `GraphQLTest`?

**Comment by imamika** [comment]
Hello! I am working on building GraphQL Webflux api using graphql-kickstart-spring-boot-starter-webflux. I tried finding resources on how i could test this. Any pointers in this regard are helpful. Thanks!

**Comment by imamika** [comment]
I think i found what i am looking for. 

[https://github.com/graphql-java-kickstart/graphql-spring-webclient/blob/master/graphql-webclient/src/test/java/graphql/kickstart/spring/webclient/boot/GraphQLWebClientTest.java](url)

**Comment by mustafa-qamaruddin** [comment]
I am trying the following test:
`
@GraphQLTest
public class UserTest {
  @Autowired
  private GraphQLTestTemplate graphQLTestTemplate;

  @Test
  public void createUser() throws IOException {
    GraphQLResponse response = graphQLTestTemplate.postForResource("graphql/register.graphql");
    assertNotNull(response);
    assertTrue(response.isOk());
    assertEquals("1", response.get("$.data.post.id"));
  }
}
`
and I get the following response:
`
<404,<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> The requested resource [&#47;api&#47;graphql] is not available</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/9.0.37</h3></body></html>,[Content-Type:"text/html;charset=utf-8", Content-Language:"en", Content-Length:"766", Date:"Sun, 08 Nov 2020 00:18:11 GMT", Keep-Alive:"timeout=60", Connection:"keep-alive"]>
`

Any help is appreciated ...

**Comment by EriRan** [comment]
@mustafa-qamaruddin That test class is correct. There is something wrong with the servlet, possibly due to the graphql not being available in *URI*/graphql

**Comment by mustafa-qamaruddin** [comment]
Thank you, I have my /graphql pointing to /api/graphql, shouldn't the test detect it automaticaly, and from debugging I think it hits /api/graphql
```
graphql:
  tools:
    schema-location-pattern: "**/*.graphqls"
    introspection-enabled: true
  servlet:
    mapping: /api/graphql
    enabled: true
```
Also, I @GraphQLTest should be initializing the servlet?
