### ISSUE TITLE
How to get HttpServletRequest in resolvers?

### ISSUE THREAD

**Issue by alex-duitsev** [graphql-java-kickstart/graphql-spring-boot#272]
I need to extract some headers from HttpServletRequest. I am trying to use DataFetchingEnvironment as a parameter in resolver method, but it gives me an error:

`
env.getContext<GraphQLContext>() 
`
`//java.lang.ClassCastException: graphql.GraphQLContext$Builder cannot be cast to graphql.servlet.GraphQLContext`

graphql-springboot version: 5.9.0

**Comment by apollo7733** [comment]
i use 5.10.0,
// DataFetchingEnvironment dataFetchingEnvironment
dataFetchingEnvironment.<DefaultGraphQLServletContext>getContext().getHttpServletRequest();

or 

you can use spring to get HttpServletRequest 

		RequestAttributes requestAttributes = RequestContextHolder.getRequestAttributes();
		return (HttpServletRequest) requestAttributes.resolveReference(RequestAttributes.REFERENCE_REQUEST);

**Comment by apollo7733** [comment]
dataFetchingEnvironment.<DefaultGraphQLServletContext>getContext().getHttpServletRequest()

**Comment by alex-duitsev** [comment]
There is no getHttpServletRequest() method anymore: https://github.com/graphql-java-kickstart/graphql-java-servlet/releases/tag/v8.0.0
Any tips on how to use this?

**Comment by oliemansm** [comment]
Cast the context to `GraphQLServletContext` and grab the `HttpServletRequest` from there.

**Comment by alex-duitsev** [comment]
But the `DataFetchingEnvironment` contains `graphql.GraphQLContext` - not the `graphql.servlet.context.GraphQLContext`, so it cannot be casted to `GraphQLServletContext `

**Comment by oliemansm** [comment]
You need to update to 5.10.0 then. Otherwise the getHttpServletRequest should just be there depending on the graphql-java-servlet version you're using.

**Comment by alex-duitsev** [comment]
I have updated and still getting the class cast exception - my previous comment is for 5.10.0.
And for version 5.9.0 its even more strange:
`java.lang.ClassCastException: graphql.GraphQLContext$Builder cannot be cast to graphql.servlet.GraphQLContext`
How is it possible that there is a `Builder` in Context?

**Comment by oliemansm** [comment]
That's not correct. graphql-spring-boot pulls in version 8.0.0 of graphql-java-servlet, not 7.5.0. So something is overriding it. You should not be including graphql-java-servlet or graphql-java-tools yourself, but just let graphql-spring-boot pull that in. Sounds like something is pulling in incompatible versions now which is causing this.

**Comment by alex-duitsev** [comment]
The only dependencies i have are: `graphql-spring-boot-starter`, `graphiql-spring-boot-starter` and `graphql-spring-boot-starter-test`.
If I specify the 5.9.0 version - it pulls 7.5.0 `graphql-java-servlet` and `getContext()` returns `graphql.GraphQLContext$Builder`
If I specify 5.10.0 - it pulls 8.0.0 `graphql-java-servlet` and `getContext()` returns `graphql.GraphQLContext`
The problem that in both cases `getContext()` returns incorrect objects

**Comment by oliemansm** [comment]
5.10.0 uses graphql-java 13.0, which defines this method as follows:
```
<T> T getContext();
```
See https://github.com/graphql-java/graphql-java/blob/c454ba295f27de6e814c3a5c1af0e2b2d83cd699/src/main/java/graphql/schema/DataFetchingEnvironment.java#L73.

I'm using these versions like this without any problems in multiple projects.

**Comment by alex-duitsev** [comment]
I think I found the problem. I was getting these results in my Integrations tests, where i was executing queries via `GraphQL.execute(executionInput)` and instead of that i should have used `GraphQLTestTemplate`. Thanks!

**Comment by jinyanghuang** [comment]
I don't get how this is solved. I run into the same issue, the version I use is 6.1.3 of graphql-java-servlet under com.graphql-java and 15.0 for graphql-java. The error I got is `class graphql.GraphQLContext cannot be cast to class graphql.servlet.GraphQLContext` . Is that a version thing?

**Comment by pstarritt-evooq** [comment]
> I don't get how this is solved. I run into the same issue, the version I use is 6.1.3 of graphql-java-servlet under com.graphql-java and 15.0 for graphql-java. The error I got is `class graphql.GraphQLContext cannot be cast to class graphql.servlet.GraphQLContext` . Is that a version thing?

Maybe my video on custom context will help you. 
You can pull the HttpServletRequest from the context: https://www.youtube.com/watch?v=YsM2VSnWUcg

**Comment by GayathriRaj** [comment]
> > I don't get how this is solved. I run into the same issue, the version I use is 6.1.3 of graphql-java-servlet under com.graphql-java and 15.0 for graphql-java. The error I got is `class graphql.GraphQLContext cannot be cast to class graphql.servlet.GraphQLContext` . Is that a version thing?
> 
> Maybe my video on custom context will help you.
> You can pull the HttpServletRequest from the context: https://www.youtube.com/watch?v=YsM2VSnWUcg

Thanks for the detailed video. I have referred and implemented the same to get the context from the DataFetchingEnvironment. But I am getting this error. context.CustomGraphQLContext cannot be cast to graphql.kickstart.servlet.context.DefaultGraphQLServletContext. Could you please assist me with this? Thanks.

**Comment by GayathriRaj** [comment]
> > > I don't get how this is solved. I run into the same issue, the version I use is 6.1.3 of graphql-java-servlet under com.graphql-java and 15.0 for graphql-java. The error I got is `class graphql.GraphQLContext cannot be cast to class graphql.servlet.GraphQLContext` . Is that a version thing?
> > 
> > 
> > Maybe my video on custom context will help you.
> > You can pull the HttpServletRequest from the context: https://www.youtube.com/watch?v=YsM2VSnWUcg
> 
> Thanks for the detailed video. I have referred and implemented the same to get the context from the DataFetchingEnvironment. But I am getting this error. context.CustomGraphQLContext cannot be cast to graphql.kickstart.servlet.context.DefaultGraphQLServletContext. Could you please assist me with this? Thanks.

This issue is resolved now. I have made a mistake in the dependency list and import.

**Comment by driatv** [comment]
Hello,

I'm getting a similar error... @oliemansm , when trying to use your sample https://github.com/graphql-java-kickstart/samples/tree/master/subscription-with-authentication :

"message": "class graphql.servlet.GraphQLContext cannot be cast to class graphql.kickstart.servlet.context.GraphQLWebSocketContext (graphql.servlet.GraphQLContext and graphql.kickstart.servlet.context.GraphQLWebSocketContext are in unnamed module of loader 'app')"

Any idea of how to resolve it? The problem is appearing here:
GraphQLWebSocketContext context = env.getContext();

Thanks in advance !

**Comment by abhilashp77** [comment]
> 5.10.0 uses graphql-java 13.0, which defines this method as follows:
> 
> ```
> <T> T getContext();
> ```
> 
> See https://github.com/graphql-java/graphql-java/blob/c454ba295f27de6e814c3a5c1af0e2b2d83cd699/src/main/java/graphql/schema/DataFetchingEnvironment.java#L73.
> 
> I'm using these versions like this without any problems in multiple projects.

I'm using graphQL:
			```
"com.graphql-java-kickstart:graphql-spring-boot-starter:12.0.0",
			"com.graphql-java-kickstart:graphql-java-tools:12.0.0",
```
getContext(); is deprectated, how can I retrieve HttpServletRequest from DataFetchingEnvironment

**Comment by abhi170392** [comment]
@oliemansm/ @vojtapol  Can you kindly help and provide a way to tackle this?
I'm using graphQL:

**"com.graphql-java-kickstart:graphql-spring-boot-starter:12.0.0",
"com.graphql-java-kickstart:graphql-java-tools:12.0.0",**

getContext(); is deprecated, how can I retrieve HttpServletRequest from DataFetchingEnvironment?
An example would surely help.

**Comment by stojsavljevic** [comment]
I'm having the same issue as @abhi170392 
Javadoc states that `getGraphQlContext()` should be used instead but it can't be used in the same way as `getContext()`. Any example on how to retrieve `HttpServletRequest` would be highly appreciated.

**Comment by abrugiafredodw** [comment]
Hello,

GraphQLContext context = env.getGraphQlContext();
		var httpServelet=context.getOrEmpty(HttpServletRequest.class).orElseThrow(() -> new Exception(""));
		return (HttpServletRequest) httpServelet;
		
this worked for me
