### ISSUE TITLE
How to handle AccessDeniedException from @Secured annotation in GraphQL response?

### ISSUE THREAD

**Issue by shahdadpuri-varun** [graphql-java-kickstart/graphql-spring-boot#276]
```
 @Secured("ROLE_ADMIN")
  Response createResponse(Map<String, Object> createInput) {
    return responseService.create(createInput);
  }
```
This piece of code throws an AccessDeniedException when logged-in user does not have the required roles. 
I am using Spring Security here.
How can I catch this exception and provide a meaningful response from my `/graphql` endpoint?
Currently, I just get a `Internal Server Error` message in my response.

**Comment by zt1983811** [comment]
I am also dealing the same problem.
I implemented `OncePerRequestFilter` filter to check if the token is good. When it is not I throw exception for `InvalidAuthExcetpion` . However it seem I always get this error 
```
{
  "error": "Unexpected end of JSON input"
}
``` 
My guess it's because the exception can't handle in the filter level for graphql

**Comment by oliemansm** [comment]
Try enabling the exception handlers. Instead of getting an Internal Server Error every time it returns the actual exception. If that's not enough, you could add your own custom `GraphQLError` and populate the extensions map to contain an error code for example.

```yaml
graphql:
  servlet:
    exception-handlers-enabled: false
```

**Comment by oliemansm** [comment]
Assuming my last comment answered your question. If not and you have follow-up questions, feel free to re-open.
