### ISSUE TITLE
Import external types into schema

### ISSUE THREAD

**Issue by pradeeptg** [graphql-java-kickstart/graphql-spring-boot#277]
Hi
I am curious to know how we can use a complex type defined by a 3rd party vendor in the graphql schema. Since this POJO is owned by the vendor, i don't want to re-define it in the schema file. Any thoughts?

**Comment by oliemansm** [comment]
Totally agree with @MFoster. You'd want to put in an ACL instead of tying your own schema directly to these foreign entities.
