### ISSUE TITLE
How to run multiple mutations in a single transaction?

### ISSUE THREAD

**Issue by Selectorrr** [graphql-java-kickstart/graphql-spring-boot#282]
I have multiple mutations that correspond to individual procs. I want to execute these mutations in a single transaction. How to do that?

**Comment by MFoster** [comment]
You mean in a single request?  You would define two mutations as part of the post body...
```graphql
mutation first {
  someMutation {
     id: 123
  }
}
mutation second {
   someMutation {
      id: 456
   }
}
```

**Comment by Selectorrr** [comment]
o, I mean: two mutations in one request in a single transaction. If an error occurs in one of the mutations, it is necessary to roll back all the changes made by this request.

**Comment by Selectorrr** [comment]
I found a solution, I had to implement custom queryInvoker:
I think it's a little tricky. Is this normal or not?
```
@Component
public class CustomGraphQLQueryInvoker extends GraphQLQueryInvoker {

    private final TransactionTemplate transactionTemplate;

    @Autowired
    public CustomGraphQLQueryInvoker(ExecutionStrategyProvider executionStrategyProvider, TransactionTemplate transactionTemplate) {
        super(() -> executionStrategyProvider,
                () -> SimpleInstrumentation.INSTANCE,
                () -> NoOpPreparsedDocumentProvider.INSTANCE,
                DataLoaderDispatcherInstrumentationOptions::newOptions);
        this.transactionTemplate = transactionTemplate;
    }

    @Override
    public ExecutionResult query(GraphQLSingleInvocationInput singleInvocationInput) {
        return transactionTemplate.execute(status -> {
            ExecutionResult result = super.query(singleInvocationInput);
            if (!result.getErrors().isEmpty()) {
                status.setRollbackOnly();
            }
            return result;
        });
    }

    @Override
    public List<ExecutionResult> query(List<GraphQLSingleInvocationInput> batchedInvocationInput, ContextSetting contextSetting) {
        return transactionTemplate.execute(status -> {
            List<ExecutionResult> results = super.query(batchedInvocationInput, contextSetting);
            if (results.stream().anyMatch(i -> !i.getErrors().isEmpty())) {
                status.setRollbackOnly();
            }
            return results;
        });
    }
}
```

**Comment by phuongphally** [comment]
@Selectorrr Can you profile full code? I need it too.

**Comment by Selectorrr** [comment]
@phuongphally  Unfortunately I can not because of the license. In fact, all you need to do is register this bean.

**Comment by phuongphally** [comment]
@Selectorrr  Thanks

**Comment by phuongphally** [comment]
`TransactionTemplate ` is can handle multiple transaction ? 

I have multiple mutation likes 

```javascript
mutation{
   createUser(...)...
   createArtist(...)...
   updatePassword(...)...
}

```


It has own transaction in-service data fetcher

`CreateUser` has `@Transaction` 
```java 
@Transaction
public boolean createUser(User user) { ....
```
`CreateArtist` has `@Transaction` 

```java 
@Transaction
public boolean createArtist(Aritst artist) { ....
```

`UpdatePassword` has `@Transaction` 
```java 
@Transaction
public boolean updatePassword(Aritst artist) { ....
```



So the questions are 


Is `TransactionTemplate` can rollback if two operation   `createUser(...)...`
 and  `createArtist(...)...` completed  but `updatePassword(...)...` error then we do rollback

**Comment by Selectorrr** [comment]
@phuongphally You do not need to use @Transactional annotation if you use programmatic transaction management (like TransactionTemplate).
see https://docs.spring.io/spring/docs/current/spring-framework-reference/data-access.html#transaction-programmatic
Just remove it and then you can control when you need to roll back the transaction
```
  if (!result.getErrors().isEmpty()) { // updatePassword error included there
                status.setRollbackOnly();
            }
```
