### ISSUE TITLE
Uploading files

### ISSUE THREAD

**Issue by morrowyn** [graphql-java-kickstart/graphql-spring-boot#287]
Hi, 

I'm trying to upload files using graphql. According to the servlet kickstart do I need to create a servlet manually or is this already done by this spring boot? And if so, how do I go about it? I'm seeing this Upload type in the apollo server. How do I enable this?

**Comment by oliemansm** [comment]
Try the accepted answer here: https://stackoverflow.com/questions/57372259/how-to-upload-files-with-graphql-java.

**Comment by oliemansm** [comment]
See the sample application: https://github.com/graphql-java-kickstart/samples/tree/master/file-upload

**Comment by hantsy** [comment]
@oliemansm  I tried to use `GraphQLTestTemplate` to upload a file but failed. The `postMultipart` only accepts a `JSON` string as a `variables` parameter.  


```java
    @SneakyThrows
    @Test
    public void uploadFile() {
        var part = """
                 {
                      "query": "mutation upload($file:Upload!){
                           upload(file:file)
                      }"
                 }
                """;
        var variables = Map.of("file", new MockPart("test", "test.txt", "test content".getBytes()).getInputStream());
        GraphQLResponse response = testTemplate.postMultipart(part, objectMapper.writeValueAsString(variables));
        assertNotNull(response);
        assertThat(response.isOk()).isTrue();
        assertThat(response.get("$.data.upload", Boolean.class)).isTrue();
    }
```

**Comment by ayush11-11** [comment]
Bad POST multipart request: no part named "graphql" or "query" getting this by sending request through postman
