### ISSUE TITLE
Add Support for Authentication / AuthenticationPrincipal injection for Resolvers

### ISSUE THREAD

**Issue by sijakubo** [graphql-java-kickstart/graphql-spring-boot#293]
It would be very nice, if we could just inject the `Authentication` or `AuthenticationPrincipal` into a resolver like in Rest-Controller. This would highly improve testability of our resolvers when we do not need to use the global SecurityContextHolder

e.g. Currently we need to do something like this:

```
import static org.springframework.security.core.context.SecurityContextHolder.getContext;

@Service
public class ReportResolver implements GraphQLQueryResolver {

    public ReportResource reports(LocalDate workDay) {
        String employeeEmail = getContext().getAuthentication().getName();
        ...
}
```

It would be nice to write it like this:
```
import org.springframework.security.core.Authentication;

@Service
public class ReportResolver implements GraphQLQueryResolver {

    public ReportResource reports(LocalDate workDay, Authentication authentication) {
        String employeeEmail = authentication.getName();
        ...
}
```

This would make it much more readable and we would get rid of the static dependency to the `spring.SecurityContextHolder`

**Comment by oliemansm** [comment]
Agreed. The problem though is that `GraphQLQueryResolver` is part of **graphql-java-tools** which knows nothing abouth Spring nor Spring Security. It does allow exposure of the `DataFetchingEnvironment` as an additional parameter which contains a `GraphQLContext`. And you're able to customize the way the `GraphQLContext` is created. So the solution might be to have a separate `graphql-spring-security-starter` module in here that could create a custom`GraphQLContext` for exposing the `Authentication`.  You wouldn't have it as a direct parameter then though, but would have to get it like:
```
public ReportResource reports(LocalDate workDay, DataFetchingEnvironment env) {
  ((SecureContext) env.getContext()).getAuthentication();
```
Which in the end isn't that much of an improvement compared to the way you currently get a hold of the `Authentication` through the static dependency...

**Comment by ieugen** [comment]
Hi, 

I'm also working on this. I've setup my app with graphql-spring-boot and we ran into the security issues since our authentication is null. 
This happens because of our use of CompletableFuture and thread pools.

See https://github.com/spring-projects/spring-security/issues/6856 for reference.
We don't have a solution right now. What happens is that some requests have the context and some do not and they fail.

**Comment by lookis** [comment]
@ieugen may be wrap with [DelegatingSecurityContextRunnable](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#delegatingsecuritycontextrunnable) or [DelegatingSecurityContextExecutor](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#delegatingsecuritycontextexecutor) is a solution?

**Comment by ieugen** [comment]
We did just that:

```
  @Bean
  public ThreadPoolTaskExecutor threadPoolTaskExecutor() {
    ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
    executor.setCorePoolSize(10);
    executor.setMaxPoolSize(100);
    executor.setQueueCapacity(50);
    executor.setThreadNamePrefix("async-");
    executor.setTaskDecorator(runnable -> new DelegatingSecurityContextRunnable(runnable));
    return executor;
  }
```

And:

```
  @Override
  public CompletionStage<Map<Long, Account>> load(Set<Long> keys, BatchLoaderEnvironment ble) {
    return supplyAsync(() -> accountService.findAccountsByIds(keys), threadPoolTaskExecutor);
  }
}
```

**Comment by lookis** [comment]
> Agreed. The problem though is that `GraphQLQueryResolver` is part of **graphql-java-tools** which knows nothing abouth Spring nor Spring Security. It does allow exposure of the `DataFetchingEnvironment` as an additional parameter which contains a `GraphQLContext`. And you're able to customize the way the `GraphQLContext` is created. So the solution might be to have a separate `graphql-spring-security-starter` module in here that could create a custom`GraphQLContext` for exposing the `Authentication`. You wouldn't have it as a direct parameter then though, but would have to get it like:
> 
> ```
> public ReportResource reports(LocalDate workDay, DataFetchingEnvironment env) {
>   ((SecureContext) env.getContext()).getAuthentication();
> ```
> 
> Which in the end isn't that much of an improvement compared to the way you currently get a hold of the `Authentication` through the static dependency...

not agree, spring security already provided wrapper for async executors, no need to inject into DataFetchingEnvironment, It's easy to config like this:
``` java
  @Bean
  public GraphQLConfiguration graphQLServletConfiguration(
      GraphQLInvocationInputFactory invocationInputFactory, GraphQLQueryInvoker queryInvoker,
      GraphQLObjectMapper graphQLObjectMapper) {
    Builder builder = GraphQLConfiguration.with(invocationInputFactory)
        .with(queryInvoker)
        .with(graphQLObjectMapper)
        .with(listeners)
        .with(graphQLServletProperties.isAsyncModeEnabled())
        .with(graphQLServletProperties.getSubscriptionTimeout())
        .with(batchInputPreProcessor)
        .with(graphQLServletProperties.getContextSetting());
    if (graphQLServletProperties.isAsyncModeEnabled()) {
      DelegatingSecurityContextExecutor delegatingSecurityContextExecutor = new DelegatingSecurityContextExecutor(
          Executors.newCachedThreadPool(new GraphQLThreadFactory()));
      builder.with(delegatingSecurityContextExecutor);
    }
    return builder.build();
  }
```
https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/95e9395a5e4b9c603a9e1836199d9cb3306c3328/graphql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.java#L263-L275

**Comment by benneq** [comment]
How about automatically injecting Spring Beans as method parameters?

```
public String getFoo(String methodParam, SomeSpringBean bean) {
  String result = bean.doSomething(methodParam);
  return result;
}
```

Axon Framework uses a similar technique. They inject all well-known parameters, and for every unknown parameter they look up the Spring Context for a matching bean. And if nothing matches: Throw an exception.

For graphql this would mean:
```
for(MethodParam param : methodParams) {
  if(param matches paramFromGraphqlSchema) {
    // use jackson to deserialize
  } else if (param is DataFetchingEnvironment) {
    // inject it
  } else {
    // look up spring context and inject it
    // else throw exception
  }
}
```

**Comment by ubarua123** [comment]
Why not try out Aspect to invoke authentication method _before_ a graphql method. It can then throw an "Unauthorised" exception if credentials/token doesn't validate. Inside that you can write you entire implementation of Spring Security. 
Yes, it's a workaround but works well. 

Define a pointcut:
```
@Pointcut("target(com.coxautodev.graphql.tools.GraphQLResolver)")
    public void graphqlMethods() { }
```

```
@Before("graphqlMethods() && args(.., dataFetchingEnvironment)")
public void authenticateUser(DataFetchingEnvironment dataFetchingEnvironment) {

        LOGGER.info("Authenticating --------- [Thread]" + Thread.currentThread());

        DefaultGraphQLServletContext defaultGraphQLServletContext = dataFetchingEnvironment.getContext();
        // Get the servlets
        HttpServletRequest  httpServletRequest  = defaultGraphQLServletContext.getHttpServletRequest();
        HttpServletResponse httpServletResponse = defaultGraphQLServletContext.getHttpServletResponse();
 // Get header and authenticate
}
```

**Comment by oliemansm** [comment]
@ubarua123 Spring Security already provides similar methods that can even be customized with custom expressions. See https://www.baeldung.com/spring-security-create-new-custom-security-expression. 

I think that's actually the way to go here. To really get the `org.springframework.security.core.Authentication` object as a method parameter is quite a lot of work that I don't see myself investing any time soon (if ever). It would require:

1. Creating a separate graphql-tools-spring-security starter specifically for this purpose, since graphql-java-tools must have no dependency on spring security.
2. Provide hook for graphql-java-tools to provide own implementation or extension for resolving methods and fields (not a bad idea to have this in the first place).
3. Actually send along the Authentication from the context when calling these methods.

If anyone has a better idea and/or has the time to create a PR for it I'm happy to accept it. Otherwise I'll close the issue marked as "not doing" in the near future.

**Comment by oliemansm** [comment]
Not doing according to my previous comment.
