### ISSUE TITLE
Websocket Overrides

### ISSUE THREAD

**Issue by mluis** [graphql-java-kickstart/graphql-spring-boot#295]
I'm trying to override methods to group websocket sessions with other variables at the moment of connection opening but can't find the class neither the method or the documentation. Can anyone give some hints?

Already tried extending:
TextWebSocketHandler
AbstractWebSocketHandler

**Comment by oliemansm** [comment]
You could add a bean implementing `ApolloSubscriptionConnectionListener`. That exposes several methods which are called in the session lifecycle, `onConnect` being one.

**Comment by oliemansm** [comment]
I'm assuming you were able to solve it with my latest comment. If not, feel free to re-open the issue with a follow-up question.
