### ISSUE TITLE
Accessing Cookies Via Subscription

### ISSUE THREAD

**Issue by MarkNenadov** [graphql-java-kickstart/graphql-spring-boot#296]
Is there a way with graphql-spring-boot-starter that you can access cookies within a subscription?

I currently have mutations and queries receiving a cookie in order to take care of authentication. I've used GraphQLContextBuilder to accomplish that.

However, when I've implemented subscriptions, the GraphQLContextBuilder's build() method only takes in a Session and a HandshakeRequest and there doesn't appear to be a way to access cookies.

I see that in other (non graphql related) websocket contexts, people are using a HandshakeInterceptor to access cookies with the beforeHandshake() override.

However, I don't see a way to do this with graphql-spring-boot-starter's websocket implementation.

Is there a way for me to use HandshakeInterceptor with graphql-spring-boot-starter, or is there some alternate way I can access my cookies within the subscription's resolver or publisher?

**Comment by MarkNenadov** [comment]
My setup was assuming some things about graphql-java that are no longer true. And I was not familiar with the websocket context.

The solution is to use GraphQLWebSocketContext, which provides HandshakeRequest, allows you to do:

graphQLWebSocketContext.getHandshakeRequest().getHeaders().get( "cookie" )

**Comment by mluis** [comment]
Hello @MarkNenadov , I'm trying to achieve something similar but overriding Open and Close requests.. Would you mind taking a look at https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/295 please? Thank you.

**Comment by neerajsu** [comment]
@MarkNenadov : I don't think websocket protocol uses cookies. Infact it is anti-pattern.The first request is a http(s) request where you can do the authentication and then it is upgraded to a websocket, but by the time you get the GraphQLWebSocketContext, it no longer has the cookies.

If you need to authenticate using cookies (like JSESSIONID), you can follow [this](https://coletiv.com/blog/using-websockets-with-cookie-based-authentication/) article. It is not Java specific, but it can be translated into your project.


I'd also recommend reading [this ](https://developer.okta.com/blog/2019/10/09/java-spring-websocket-tutorial) article to understand how authentication works in Websocket.
