### ISSUE TITLE
Spring security: introspection query without authentication

### ISSUE THREAD

**Issue by chrisae** [graphql-java-kickstart/graphql-spring-boot#300]
More a question than an issue and I'm wondering if this might work as a configuration with graphql-spring-boot: I'm securing my GraphQL endpoint with Spring security (obvious) but I need the introspection query to work without authentication. Is this somehow intended to work as a config for the kickstart project?

Thanks for any help.

**Comment by oliemansm** [comment]
I tend to use `permitAll()` on the graphql endpoint and use method based security in the resolvers. That basically results in the security you have in mind here. But you probably figured that out already..

**Comment by oliemansm** [comment]
I'm assuming you were able to solve it with my latest comment. If not, feel free to re-open the issue with a follow-up question.
