### ISSUE TITLE
Loading and Accessing Custom GraphQLContext class in DataFetchingEnvironment

### ISSUE THREAD

**Issue by harry2190** [graphql-java-kickstart/graphql-spring-boot#302]
Hi,

Been checking out post and potential documentation on how to properly load my custom GraphQLContext unfortunately though most have answer, it do not discuss how Spring Boot will be able to read, load and access the created context without the use of GraphQLEndpoint class  like [here](https://github.com/howtographql/graphql-java/blob/master/src/main/java/com/howtographql/hackernews/GraphQLEndpoint.java). 

I am using graphql-spring-boot-starter 5.8.2 and graphql-java-tools 5.5.0. Basically I just wanted to access my class below to get the login user details like id and name from the DataFetchingEnvironment for each Resolver I have (for sample purposes only):

public class AuthorizationContext extends GraphQLContext {
	
    private final User user;
    
    public AuthorizationContext(User user, HttpServletRequest request, HttpServletResponse response) {
        super(request, response);
        this.user = user;
    }

    public User getUser() {
        return user;
    }
}

on my QueryResolver class for example, I wanted to be able to access and get the AuthorizationContext via the DataFetchingEnvironment.

public List<Friends> getFriends(DataFetchEnvironment env){
     AuthorizationContext authCtx = (AuthorizationContext) env.getContext();
     return    friendsService.getFriends(authCtx .getUser());
}

Hopefully what I am referring here make sense.

**Comment by drakir** [comment]
I found a way. 
You have a AutoConfiguration class called `GraphQLWebAutoConfiguration` in your classpath. That one is trying to load contextBuilders, so what you can do is to add a component which implements `GraphQLContextBuilder`. In the example below I am returning an instance of a similar class like in your example.


```
@Component
public class JwtGraphQLContextBuilder implements GraphQLContextBuilder {

    public static final String BEARER_PREFIX = "Bearer ";
    private final JwtValidator validator;

    @Autowired
    public JwtGraphQLContextBuilder(JwtValidator validator) {
        this.validator = validator;
    }

    @Override
    public GraphQLContext build(HttpServletRequest httpServletRequest) {
        JwtUser jwtUser = getJwtToken(httpServletRequest).flatMap(validator::validate).orElse(null);
        return new AuthGraphQLContext(httpServletRequest, jwtUser);
    }

    @Override
    public GraphQLContext build(HandshakeRequest handshakeRequest) {
        return new AuthGraphQLContext(handshakeRequest);
    }

    @Override
    public GraphQLContext build() {
        return new AuthGraphQLContext();
    }

    private Optional<String> getJwtToken(HttpServletRequest httpServletRequest) {
        String header = httpServletRequest.getHeader("Authorization");
        if (header != null && header.startsWith(BEARER_PREFIX)) {
            return Optional.of(header.substring(BEARER_PREFIX.length()));
        }
        return Optional.empty();
    }
}
```

**Comment by oliemansm** [comment]
Thanks @drakir, that would indeed be the way to do it. 
@harry2190 If this didn't answer your question properly feel free to re-open the issue.

**Comment by spandanankfief** [comment]
I'm always getting env.getContext(); as null from DataFetchingEnvironment..any idea why? @oliemansm @drakir
