### ISSUE TITLE
Description ignored

### ISSUE THREAD

**Issue by tvendelin** [graphql-java-kickstart/graphql-spring-boot#303]
Are type / field / args / etc. descriptions supported? 

According to [specs](https://graphql.github.io/graphql-spec/June2018/#sec-Descriptions), given

```
type MyType{
  "The ID of whatever"
  id: String!
}
```
... when I send introspection query

```
{
  __type(name: "MyType"){
    description
    fields{
      name
      description
    }
  }
}
```
... I should get the description of documented types / fields / args / etc., but they are still empty. The rest of the schema works fine.

The relevant part of my `build.gradle`
```

implementation group: 'com.graphql-java', name: 'graphql-spring-boot-starter', version: '5.0.2'
implementation group: 'com.graphql-java', name: 'graphiql-spring-boot-starter', version: '5.0.2'
implementation group: 'com.graphql-java', name: 'graphql-java-tools', version: '5.2.4'
```

I'm using *.grphqls files to generate the schema.

**Comment by oliemansm** [comment]
That should be supported, but you're not using the latest versions. You're using very old versions instead, so try upgrading first.

**Comment by tvendelin** [comment]
Indeed, I have confused the Maven groups, using the "latest" version from `com.graphql-java` instead of `com.graphql-java-kickstart`. Now everything works fine with dependencies as below:

```
implementation group: 'com.graphql-java-kickstart', name: 'graphql-spring-boot-starter', version: '5.11.1' 
implementation group: 'com.graphql-java-kickstart', name: 'graphql-java-tools', version: '5.7.1'
testImplementation group: 'com.graphql-java-kickstart', name: 'graphql-spring-boot-starter-test', version: '5.11.1'
runtimeOnly group: 'com.graphql-java-kickstart', name: 'graphiql-spring-boot-starter', version: '5.11.1'
```

**Comment by oliemansm** [comment]
Btw: you don't have to explicitly define the `graphql-java-tools` dependency. `graphql-spring-boot-starter` pulls it in automatically.
