### ISSUE TITLE
@ExceptionHandler is ignored

### ISSUE THREAD

**Issue by Sam-Kruglov** [graphql-java-kickstart/graphql-spring-boot#309]
Hi!

Looking at https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/166, I found that `graphql.kickstart.spring.error.ReflectiveMethodValidator#isGraphQLExceptionHandler` is only called for classes which are returned from `org.springframework.beans.factory.ListableBeanFactory#getBeanDefinitionNames` at the time of `ContextRefreshedEvent`.

So, at this time, my `@Configuration` class is not there, in fact, at this time there are about 20 entries there. After the application has started, this method returns 700+ entries including my thing. Could that be the issue? I tried declaring it in the `@Componenet` as well

The whole thing happens in `graphql.kickstart.spring.error.GraphQLErrorStartupListener` that calls `GraphQLErrorHandlerFactory`

**Comment by oliemansm** [comment]
Solved by #305
