### ISSUE TITLE
Cancel subscriptions

### ISSUE THREAD

**Issue by calvernaz** [graphql-java-kickstart/graphql-spring-boot#313]
How can we cancel an on-going subscription?

**Comment by oliemansm** [comment]
From the server side you mean?

**Comment by calvernaz** [comment]
This was a few months ago so I don't clear remember this, but I guess so. It's possible that I couldn't cancel an on-going subscription.

**Comment by oliemansm** [comment]
In case this situation ever pops up again feel free to re-open, but since it's not an active case for you and nobody else seems to be having questions/problems with this atm I'll close it for now.
