### ISSUE TITLE
GraphQLQueryResolver hasn't supported UTF-8

### ISSUE THREAD

**Issue by HTipi** [graphql-java-kickstart/graphql-spring-boot#314]
Could you help check why others language not supported on QUERY?
For mutation, it's working fine. it means we can insert but can't retrieve the value back.

<img width="1186" alt="Screen Shot 2019-12-22 at 6 02 26 PM" src="https://user-images.githubusercontent.com/26158791/71320931-63e0a980-24e5-11ea-8b82-985fbd2d959c.png">

data in db after mutation:
<img width="1041" alt="Screen Shot 2019-12-22 at 6 10 47 PM" src="https://user-images.githubusercontent.com/26158791/71321046-96d76d00-24e6-11ea-8529-de89dcdd9a3b.png">

**Comment by oliemansm** [comment]
There used to be a bug in 9.0.0 of graphql-java-servlet. Updating graphql-spring-boot-starter to 7.0.1 should fix your problem.
