### ISSUE TITLE
How to implement asynchronous query execution ?

### ISSUE THREAD

**Issue by roger-gl** [graphql-java-kickstart/graphql-spring-boot#315]
if have a query that looks like 

{ fetchFromRestEndpoint1 { name }
 fetchFromRestEndpoint2 { name } }

I'm using Spring Boot restTemplate in the QueryResolver. That works so far. Now I'm wondering how to implement asynchronous fetching and return the grahql result if both results are received ?

Is there already support for this in the  QueryResolver without using a Webflux based approach ? 

The problem is that I have to integrate the GraphQL stuff into an existing REST based server that uses Tomcat and I can not change that right now.

**Comment by oliemansm** [comment]
The default execution strategy used is the `AsyncExecutionStrategy` which should do exactly what you need. See the more detailed explanation in the relevant section here: https://www.graphql-java.com/documentation/v11/execution/.

I'm assuming that you tried it out in the meantime though and already figured out it works that way. Feel free to re-open if you have a follow-up question.
