### ISSUE TITLE
Question: Coroutine drawbacks in resolvers and recommended implementation?

### ISSUE THREAD

**Issue by bsara** [graphql-java-kickstart/graphql-spring-boot#321]
I noticed that graphql-java-tools supports coroutines (suspend functions) in resolvers and was curious of two things:

1. are there any potential drawbacks to using `suspend` over a normal `CompletableFuture.supplyAsync` in query/type resolvers? _(it seems to use `GlobalScope` which, the Kotlin docs make sound like should be avoided in most cases, but I'm still working on understanding it fully)_
2. is there a recommended implementation for using suspend functions in query/type resolvers? _(like providing your own coroutine context or just allowing the default, etc.)_

**Comment by oliemansm** [comment]
@bsara I'm no kotlin expert myself unfortunately, so hopefully somebody else is able to shed light on this. @vojtapol Any thoughts from you perhaps?

**Comment by vojtapol** [comment]
@bsara 
1. I am not aware of any drawbacks to using `suspend`. As you are aware it is not always a good idea to use `GlobalScope` and that's why the coroutine scope is now fully configurable (https://github.com/graphql-java-kickstart/graphql-java-tools/pull/350)
2. The regular Kotlin coroutine conventions still apply, pinging @elizarov in case he can offer additional insight.

**Comment by vojtapol** [comment]
@bsara 
1. I am not aware of any drawbacks to using `suspend`. 
2. The regular Kotlin coroutine conventions still apply, pinging @elizarov in case he can offer additional insight.

**Comment by bsara** [comment]
Well, after my own research, the only real concern seemed to be using GlobalScope, because you the failure/cancellation of a parent coroutine wouldn't force the GlobalScope coroutine to cancel. But I've already submitted a PR to change that, and it was merged. Thanks for your responses though.
