### ISSUE TITLE
Make GraphQLTestTemplate.post method public

### ISSUE THREAD

**Issue by egormasalitin** [graphql-java-kickstart/graphql-spring-boot#323]
For some integration tests, it is reasonable not to create a separate file with a query, for example:
```
{client(id:1){name}}
```
And it would be nice to have a method that can work with sting input instead of a resource. 
What do you think?

That is why I would like to make the post method public:
https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/6ca57e258c874537bbef660694ddf5f5b97947ab/graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/GraphQLTestTemplate.java#L111

**Comment by johnloven** [comment]
Why was this closed?
