### ISSUE TITLE
graphql.kickstart.spring.AbstractGraphQLController fails to find json

### ISSUE THREAD

**Issue by Sam-Kruglov** [graphql-java-kickstart/graphql-spring-boot#328]
Hi, I am trying to connect to kickstart spring boot project using [Apollo Android Client ](https://github.com/aoudiamoncef/apollo-client-maven-plugin/issues/12) and I get 422 HTTP status response.

Using a debugger I found that Apollo uses `application/json; charset=utf-8` content type but `graphql.kickstart.spring.AbstractGraphQLController` only checks for `application/json` and thus does not recognize it as JSON. 

https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/08395c9c458f00cdc68076ed4926162f063b1251/graphql-kickstart-spring-support/src/main/java/graphql/kickstart/spring/AbstractGraphQLController.java#L51

**Comment by aoudiamoncef** [comment]
Hi @oliemansm, @Sam-Kruglov ,
I have my own implementation of the GraphQL controller which could resolve this issue.

**Comment by Sam-Kruglov** [comment]
my workaround is to forcibly write this header as `application/json` in the client code:
```
OkHttpClient.Builder()
            .addNetworkInterceptor { chain ->
                chain.proceed(
                        chain.request()
                                .newBuilder()
                                .removeHeader(HttpHeaders.CONTENT_TYPE)
                                .header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
                                .build()
                )
            }.build()
```

**Comment by aoudiamoncef** [comment]
The modification should be done in server side. We should handle all the
possible cases.

**Comment by Sam-Kruglov** [comment]
added some comments yo your commit. Also, did you forget to make a PR for it? I can't see one
