### ISSUE TITLE
altair.static.basePath not recognized in STS4

### ISSUE THREAD

**Issue by SledgeHammer01** [graphql-java-kickstart/graphql-spring-boot#331]
I'm using STS4 and altair.static.basePath is not recognized if I open the application.properties file. It gets a yellow squiggle and a Warning icon on the file. Normally, I can add the property to my additional-spring-configuration-metadata file and it fixes it, but there seems to be something different about this particular property.

**Comment by oliemansm** [comment]
Just tried it with 7.1.0-SNAPSHOT where it's working for me.
