### ISSUE TITLE
How to disable graphql-tools

### ISSUE THREAD

**Issue by michael-fl** [graphql-java-kickstart/graphql-spring-boot#333]
Hi,

how can I disable `graphql-tools` (or completely exclude it) when using `graphql-spring-boot-starter`? I don't need graphql-tools and it causes problems when on the classpath. Thanks.

**Comment by oliemansm** [comment]
The only option at the moment is to exclude it when importing `graphql-spring-boot-starter`.

When using maven it would look like:
```
<dependency>
      <groupId>com.graphql-java-kickstart</groupId>
      <artifactId>graphql-spring-boot-starter</artifactId>
      <version>6.0.1</version>
      <exclusions>
        <exclusion>
          <groupId>com.graphql-java-kickstart</groupId>
          <artifactId>graphql-java-tools</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

The webflux starter doesn't import it automatically, so you could also switch to that one instead (`graphql-kickstart-spring-boot-starter-webflux`).

Feel free to reopen the issue if you have further questions about this.
