### ISSUE TITLE
How to set global context?

### ISSUE THREAD

**Issue by michael-fl** [graphql-java-kickstart/graphql-spring-boot#334]
Hi,

I have the need to store global context information once whenever a new GraphQL request is executed. When using plain vanilla `graphql-java`, one just creates an own context object and sets it via `ExecutionInput.newExecutionInput().context(context)`. When using `graphql-spring-boot` however, the context is automatically created via the framework and is of type `DefaultGraphQLServletContext`.

How can I either

* set an own context (without breaking the GraphQL servlet),
* extend DefaultGraphQLServletContext or
* attach some arbitrary user object to a request?

Thanks for any help!

**Comment by oliemansm** [comment]
You can create your own `GraphQLServletContextBuilder` bean for this purpose. See (CustomGraphQLContextBuilder)[https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/8ee147931e7d9c1e489ab87d5cb961e87717c875/example-request-scoped-dataloader/src/main/java/graphql/servlet/examples/dataloader/requestscope/CustomGraphQLContextBuilder.java] for an example.

You implement the following methods:

```java
// Used for regular queries and mutations
GraphQLContext build(HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse);

// Used for subscriptions using websockets
GraphQLContext build(Session session, HandshakeRequest handshakeRequest);
```

**Comment by Thinkenterprise** [comment]
Extending the `GraphQLServletContextBuilder` with your own implementation is not sufficient. 
It is also necessary to expand the `DefaultGraphQLServletContext` to create your own context with your own data.
In the current version this is not possible because the constructor of the class `DefaultGraphQLServletContext` is private.
This is new and probably has its reason in the builder pattern. In older versions there was no builder pattern and it was easier to introduce your own context. I posted a ticket https://github.com/graphql-java-kickstart/graphql-java-servlet/issues/266 and asked if the constructor can be made private. Then a separate context should be possible. I think the feature is very important.

**Comment by oliemansm** [comment]
It's not necessary to expand the `DefaultGraphQLServletContext` since you can just provide your own implemenation of `GraphQLServletContext` without it. It does make it a bit easier, so changed the visibility of that constructor now.

**Comment by Thinkenterprise** [comment]
This means you lose the useful default implementation and you have to copy and paste it into your own implementation. 
But right, it would work:-) Necessary is wrong!!

**Comment by pstarritt-evooq** [comment]
https://www.youtube.com/watch?v=YsM2VSnWUcg

> Hi,
> 
> I have the need to store global context information once whenever a new GraphQL request is executed. When using plain vanilla `graphql-java`, one just creates an own context object and sets it via `ExecutionInput.newExecutionInput().context(context)`. When using `graphql-spring-boot` however, the context is automatically created via the framework and is of type `DefaultGraphQLServletContext`.
> 
> How can I either
> 
>     * set an own context (without breaking the GraphQL servlet),
> 
>     * extend DefaultGraphQLServletContext or
> 
>     * attach some arbitrary user object to a request?
> 
> 
> Thanks for any help!

I created a video on implementing a custom context. Hopefully it helps you: https://www.youtube.com/watch?v=YsM2VSnWUcg

**Comment by Thinkenterprise** [comment]
Thank you for sharing the video with us. Really very good videos. Great!! An extension of the `DefaultGraphQLServletContext` is only possible from GraphQL Servlet 9.3. The current Graphql Spring Boot 7.1.0 only delivers 9.2 :-) But it doesn't matter, placing an instance in the 'CutomGraphQLServletContext` is a good idea.
