### ISSUE TITLE
Migration guide from 5.x.x to 6.x.x available? 

### ISSUE THREAD

**Issue by d4nyel** [graphql-java-kickstart/graphql-spring-boot#353]
Hey there,
Is there any migration guide available to migrate from 5,x,x to 6.x.x?

I noticed that the package name has changed from `com.coxautodev.graphql` to `graphql.kickstart`
Further: after changing the version and the package imports it seems that the schema files *.graphqls do not get discovered anymore. Before the change to 6.x.x every  *.graphqls file was discovered correctly and the query and mutation "endpoints" were available. After the change it seems that the schema files do not get resolved anymore. That leads to the problem that no mutation or query is available anymore.

PS:
Is there any real world example available for the DataLoader / BatchLoader?
Thanks!

**Comment by feitian124** [comment]
same here.
i am a fresh man here so i wasted days but failed to finish the guide, then i notice the version issue..

**Comment by vojtapol** [comment]
It seems like this bug has been introduced in the recent upgrade. We will fix this.

**Comment by vojtapol** [comment]
From the linked issue it looks like you are setting the `graphql-java-tools` manually:

```xml
<dependency>
    <groupId>com.graphql-java-kickstart</groupId>
    <artifactId>graphql-spring-boot-starter</artifactId>
    <version>6.0.1</version>
</dependency>
<dependency>
    <groupId>com.graphql-java-kickstart</groupId>
    <artifactId>graphql-java-tools</artifactId>
    <version>6.0.0</version>
</dependency>
```

Do not do this as these two version are not compatible. Wait for the next release of `graphql-spring-boot-starter` which will also bring an updated version of `graphql-java-tools`.

Also note that `DataLoader` is available in the current version already.

**Comment by anoop4tech** [comment]
> Do not do this as these two version are not compatible. Wait for the next release of `graphql-spring-boot-starter` which will also bring an updated version of `graphql-java-tools`.

Do you have any ETA for the next release of graphql-spring-boot-starter including the latest graphql-java-tools?
