### ISSUE TITLE
Voyager Webflux

### ISSUE THREAD

**Issue by maxdavidguenther** [graphql-java-kickstart/graphql-spring-boot#354]
`voyager-spring-boot-autoconfigure` currently doesn't support Webflux. Would you guys be open for a PR?

I think my approach would be refactor the replacement logic in the `VoyagerController` into a separate component and use that from a MVC and a Webflux controller.

**Comment by oliemansm** [comment]
Definitely open for a PR, thanks!

Groeten,
Michiel
________________________________
Van: Max Günther <notifications@github.com>
Verzonden: Sunday, March 1, 2020 4:31:10 PM
Aan: graphql-java-kickstart/graphql-spring-boot <graphql-spring-boot@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [graphql-java-kickstart/graphql-spring-boot] Voyager Webflux (#354)


voyager-spring-boot-autoconfigure currently doesn't support Webflux. Would you guys be open for a PR?

I think my approach would be refactor the replacement logic in the VoyagerController into a separate component and use that from a MVC and a Webflux controller.

**Comment by maxdavidguenther** [comment]
PR: #355
