### ISSUE TITLE
Question: What is altair-spring-boot-starter?

### ISSUE THREAD

**Issue by michael-fl** [graphql-java-kickstart/graphql-spring-boot#357]
Could somebody please explain the purpose of the starter "altair-spring-boot-starter"?

I removed it from my dependencies and my GraphQL microservice was running still fine. So what is it used for?

**Comment by BlasiusSecundus** [comment]
Altair is a GraphQL client, akin to GraphiQL and GraphQL Playground, which can be used either as a standalone app or integrated into the GraphQL Server directly. The starter you mentioned does this integration. It is not required for your GraphQL server to work.

See: https://github.com/imolorhe/altair
