### ISSUE TITLE
Library source does not match the bytecode for class GraphQLJavaToolsAutoConfiguration

### ISSUE THREAD

**Issue by conanchen** [graphql-java-kickstart/graphql-spring-boot#362]
# env
1. gradle.properties:
kotlin.version=1.3.35
graphqlSpringBootStarterVersion=6.0.1
graphqlJavaToolsVersion=6.0.0
2. the root project build.gradle
            dependency "com.graphql-java-kickstart:graphql-java-tools:${graphqlJavaToolsVersion}"
            dependency "com.graphql-java-kickstart:graphql-spring-boot-starter:${graphqlSpringBootStarterVersion}"
3. the sub project build.gradle
    compile ("com.graphql-java-kickstart:graphql-java-tools"){exclude group: 'ch.qos.logback'}
    compile ("com.graphql-java-kickstart:graphql-spring-boot-starter"){
        exclude group: 'ch.qos.logback'
    }
4. start the Application and get the error log:
The following candidates were found but could not be injected:
        - Bean method 'graphQLSchema' in 'GraphQLJavaToolsAutoConfiguration' not loaded because @ConditionalOnClass did not find required class 'com.coxautodev.graphql.tools.SchemaParser'

5. found intellij compliant message [Library source does not match the bytecode for class GraphQLJavaToolsAutoConfiguration]: 

> import com.coxautodev.graphql.tools.GraphQLResolver;
> import com.coxautodev.graphql.tools.PerFieldObjectMapperProvider;
> import com.coxautodev.graphql.tools.SchemaParser;
> import com.coxautodev.graphql.tools.SchemaParserBuilder;
> import com.coxautodev.graphql.tools.SchemaParserDictionary;
> import com.coxautodev.graphql.tools.SchemaParserOptions;
> import com.coxautodev.graphql.tools.TypeDefinitionFactory;
> 
/**
 * @author Andrew Potter
 */
@Slf4j
@Configuration
@ConditionalOnClass(SchemaParser.class)
@AutoConfigureAfter({JacksonAutoConfiguration.class})
@EnableConfigurationProperties(GraphQLToolsProperties.class)
public class GraphQLJavaToolsAutoConfiguration {

6. also try to remove the gradle cache of ~/.gradle/caches/modules-2/files-2.1/com.graphql-java-kickstart, the above error stays there the same. 

7. looked into the cached file: graphql-kickstart-spring-boot-autoconfigure-tools-6.0.1.pom , found dependency graphql-java-tools:5.7.1, this should be 6.0.0 ?  
  <version>6.0.1</version>
  <dependencies>
    <dependency>
      <groupId>com.graphql-java-kickstart</groupId>
      <artifactId>graphql-java-tools</artifactId>
      <version>**5.7.1**</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-autoconfigure</artifactId>
      <version>2.2.1.RELEASE</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
  <name>graphql-spring-boot</name>

**Comment by oliemansm** [comment]
Don't mix graphql-java-tools 6.0.0 with 6.0.1 of spring-boot-starter. Those aren't compatible. Instead you should rely on spring-boot-starter to pull in the right graphql-java-tools for you. Version 7.0.0 should be released soon which is compatible with that version of graphql-java-tools.

**Comment by rwilliams-r7** [comment]
Any news on the 7.0.0 release?

**Comment by oliemansm** [comment]
I want to have this bug fixed first: https://github.com/graphql-java-kickstart/graphql-java-tools/issues/367. So as soon as I or anybody else has found the time to fix that one we can move forward.

**Comment by oliemansm** [comment]
Version 7.0.0 has been released https://github.com/graphql-java-kickstart/graphql-spring-boot/releases/tag/v7.0.0
