### ISSUE TITLE
"com.graphql-java-kickstart:graphql-spring-boot-starter" doesn't work

### ISSUE THREAD

**Issue by Johnie-Yeo** [graphql-java-kickstart/graphql-spring-boot#363]
I've just tried graphql tutorial for several days.
and I just got a problem with graphql-spring-boot-starter.
It seems the path `/graphql`  has never opened.

I just follow this [blog](https://auth0.com/blog/building-graphql-apis-with-kotlin-spring-boot-and-mongodb/), so I have the exact same code with that blog.
The only difference is I set the dependencies like
```
implementation("com.graphql-java-kickstart:graphql-spring-boot-starter:6.0.1")
implementation("com.graphql-java-kickstart:graphiql-spring-boot-starter:6.0.1")
implementation("com.graphql-java-kickstart:graphql-java-tools:6.0.0")
```

And here is the result

![image](https://user-images.githubusercontent.com/39961261/76200772-873e0980-6235-11ea-8ffd-9a957649b785.png)

**Comment by oliemansm** [comment]
You shouldn't include the `graphql-java-tools` lib manually, but instead rely on `graphql-spring-boot-starter` to pull that in. The blog is incorrect about that one.

Version 6.0.0 of graphql-java-tools is not compatible with 6.0.1 of spring-boot-starter. That's most likely why you're having this problem.

**Comment by Johnie-Yeo** [comment]
It works! Thank you very much. 

But here is a just suggestion, I think you should update the [Document](https://www.graphql-java-kickstart.com/spring-boot/) because the document also makes me really confused. (most of the reason is the document suggests version 5.2 but repository's README includes 6.0.1) I'm talking this as a representative for the people who are newb on GraphQL. If you were available to provide an updated document, many people would not be in a struggle like me.😁

**Comment by oliemansm** [comment]
Yeah, the documentation indeed needs to be updated.

**Comment by bhuvana-guna** [comment]
Even I'm facing the same issue. Letting the spring-boot-starter choose graphql-tools works but I need the latest graphql-tools for my project. What to do?
