### ISSUE TITLE
Support for JWT?

### ISSUE THREAD

**Issue by MoisesSC** [graphql-java-kickstart/graphql-spring-boot#368]
**how can i add jwt support to my graphql api?**

**Comment by oliemansm** [comment]
That's a very broad question involving multiple technologies and isn't specific to this project. So if you're unable to find a tutorial or sample project online and need more help I suggest to open an issue on StackOverflow or something.

I tend to use Spring Security with a custom JWT filter in the security chain to populate the security context and use its regular method based authentication to secure the resolvers.
