### ISSUE TITLE
The bean 'graphiQLController', defined in class path resource

### ISSUE THREAD

**Issue by rastann** [graphql-java-kickstart/graphql-spring-boot#377]
Hi,

I am having the following graphql dependencies and their version:

`
<dependency>
  <groupId>com.graphql-java</groupId>
  <artifactId>graphql-spring-boot-starter</artifactId>
  <version>5.0.2</version>
</dependency>
<dependency>
  <groupId>com.graphql-java</groupId>
  <artifactId>graphql-java-tools</artifactId>
  <version>5.2.4</version>
</dependency>
<dependency>
  <groupId>com.graphql-java</groupId>
  <artifactId>graphiql-spring-boot-starter</artifactId>
  <version>5.0.2</version>
</dependency>
`

When I am trying to start the application, I have the following error:

`
Description:

The bean 'graphiQLController', defined in class path resource [com/oembedler/moon/graphiql/boot/GraphiQLAutoConfiguration.class], could not be registered. A bean with that name has already been defined in URL [jar:file:/C:/Users/rastan/.m2/repository/com/graphql-java/graphiql-spring-boot-autoconfigure/5.0.2/graphiql-spring-boot-autoconfigure-5.0.2.jar!/com/oembedler/moon/graphiql/boot/GraphiQLController.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
`

Could you please let me know if this a dependency problem and how this can be fixed ?

Thank you !

Best Regards

**Comment by oliemansm** [comment]
You're using very old deprecated versions. Please update to the latest version of the graphql-spring-boot-starter (7.0.1), and remove your dependency on tools and graphql-java. Only rely on the starters and try again.

You're using the wrong groupId too.

**Comment by rastann** [comment]
Yes, this is it :)
I didn't know that I am using old version of graphql :|
Thank you for your help.
