### ISSUE TITLE
Subscription does not handle properly NonNullableFieldWasNullException

### ISSUE THREAD

**Issue by BlasiusSecundus** [graphql-java-kickstart/graphql-spring-boot#378]
`NonNullableFieldWasNullException`s are apparently not properly handled in case of subscriptions. Take the following schema as an example:

```graphql

type Foo {
    bar: String!
}

type Query {
    foo: Foo!
}

type Subscription {
    foo: Foo!
}
```

If `Foo.bar` is `null`, the query returns the following specification-compliant response:

```JSON
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable type: 'String' within parent 'Foo' (/foo/bar)",
      "path": [
        "foo",
        "bar"
      ],
      "extensions": {
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": null
}
```

However, the subscription only sends the following message to the client:

```JSON
{"type":"error","id":"1"}
```

GraphQL Playground displays the following error message:

```JSON
{
  "error": {
    "name": "FormatedError",
    "message": "Unknown error"
  }
}
```
Other clients, however, may go into an infinite loading/waiting state, not recognizing that an error occurred.

Tested version: 7.0.1

**Comment by oliemansm** [comment]
This has already been fixed in the current version. Version 8.1.0 will have a slight improvement that it'll include the correct `path` too in case of a non nullable exception.
