### ISSUE TITLE
Custom implementation of GraphQLErrorHandler no longer supported?

### ISSUE THREAD

**Issue by pstarritt-evooq** [graphql-java-kickstart/graphql-spring-boot#379]
Hi,

Previously you could bring your own implementation of GraphQLErrorHandler.

Now, this is always set to the DefaultGraphQLErrorHandler.

The correct custom implementation is still created and injected into the objectmapper etc.
But when the GraphQLErrorStartupListener executes onApplicationEvent, the injected ErrorHandlerSupplier (with the correct custom implementation variable at this point) is always overridden with the exception handlers (org.springframework.web.bind.annotation.ExceptionHandler) or the DefaultGraphQLErrorHandler.

This is done in GraphQLErrorStartupListener -> GraphQLErrorHandlerFactory -> override implementation.

Done in following PR:
https://github.com/graphql-java-kickstart/graphql-spring-boot/pull/305

E.g.

```
@Component
public class CustomGraphQLErrorHandler implements GraphQLErrorHandler 
```

Is this a feature to no longer support bring your own GraphQLErrorHandler?

**Comment by oliemansm** [comment]
Hi, this is not intended behavior. We welcome PRs to fix stuf like this in case you have time :)

**Comment by neerajsu** [comment]
The issue is because GraphQLObjectMapper being overriden. So for those still on 7.0.1, just create the following bean in any configuration class and you should be good to go.

The custom exception handler in this code snippet is `GraphQLExceptionHandler`. Rest of them are library classes. The Exception handler should be exposed as a Bean or a Component.

```java
    @Bean
    public GraphQLObjectMapper graphQLObjectMapper(ObjectProvider<ObjectMapperProvider> objectMapperProviderObjectProvider, GraphQLExceptionHandler graphQLExceptionHandler, @Autowired(required = false) GraphQLServletObjectMapperConfigurer objectMapperConfigurer) {
        GraphQLObjectMapper.Builder builder = newBuilder();

        builder.withGraphQLErrorHandler(new ErrorHandlerSupplier(graphQLExceptionHandler));

        ObjectMapperProvider objectMapperProvider = objectMapperProviderObjectProvider.getIfAvailable();

        if (objectMapperProvider != null) {
            builder.withObjectMapperProvider(objectMapperProvider);
        } else if (objectMapperConfigurer != null) {
            builder.withObjectMapperConfigurer(objectMapperConfigurer);
        }
        return builder.build();
    }
```

Someone should add this to the documentation just in case people are not stuck trying to troubleshoot a problem that they didn't cause.
