### ISSUE TITLE
graphql-java-extended-validation ValidationSchemaDirective doesn't get registered

### ISSUE THREAD

**Issue by brendamckenne** [graphql-java-kickstart/graphql-spring-boot#381]
Hi, I am using  https://github.com/graphql-java/graphql-java-extended-validation library along with graphql-java-tools spring boot.

I tried registering **SchemaWiring** Directive in SchemaParser builder's  directiveWiring method but still it fails to pick that directive which has been provided in the library above.

Basically
```

ValidationRules validationRules = ValidationRules.newValidationRules()
                .onValidationErrorStrategy(OnValidationErrorStrategy.RETURN_NULL)
                .build();
        //
        // This will rewrite your data fetchers when rules apply to them so that validation
        ValidationSchemaWiring schemaWiring = new ValidationSchemaWiring(validationRules);
        
```

This schemaWiring is not getting added to directive in SchemaParser.

Can you help?

**Comment by oliemansm** [comment]
You're using the `graphql-spring-boot-starter` since you've registered the issue here. Instead of passing it in manually, can you expose a bean for it and see if that works. E.g.

```java
@Bean
public ValidationSchemaWiring() schemaWiring(){
    ValidationRules validationRules = ValidationRules.newValidationRules()
                .onValidationErrorStrategy(OnValidationErrorStrategy.RETURN_NULL)
                .build();
    return new ValidationSchemaWiring(validationRules);
}
```

**Comment by sumitbadaya27** [comment]
Tried the approach that you suggested. Unfortunate to say, it didn't work either.

Added screenshot of debug point. You can see that 3 directives get registered but there should be fourth one too which had an annotation "@NotEmpty" in SDL file.
 
![Screenshot from 2020-04-04 23-11-57](https://user-images.githubusercontent.com/49803617/78457717-dc046100-76c9-11ea-95c9-b248816303d4.png)

**Comment by oliemansm** [comment]
As discussed in other issue this is supported starting with version 7.0.2-SNAPSHOT of graphql-spring-boot (although the next official release will be 7.1.0 btw).

However... This library is using graphql-java 14.0, while graphql-java-extended-validation is not yet compatible with it. That's why you'll run into problems trying to run it. You'll have to wait until they [merged this PR](https://github.com/graphql-java/graphql-java-extended-validation/pull/11) and released a new version to provide support for graphql-java 14.0

**Comment by brendamckenne** [comment]
Yeah till then i have used snapshot version and its working fine till now.

**Comment by baileylo** [comment]
If you really want to get this working, you can do the following. Create the the bean as @oliemansm suggested,

```
@Bean
public ValidationSchemaWiring() schemaWiring(){
    ValidationRules validationRules = ValidationRules.newValidationRules()
                .onValidationErrorStrategy(OnValidationErrorStrategy.RETURN_NULL)
                .clearValidations()
                .addRule(new BlankValidationRule())
                .build();
    return new ValidationSchemaWiring(validationRules);
}
```

Then you'll need to define your own NotBlankRule as:

```
public class NotBlankRule extends graphql.validation.constraints.standard.NotBlankRule {
    protected boolean isOneOfTheseTypes(GraphQLInputType inputType, GraphQLScalarType... scalarTypes) {
        GraphQLInputType unwrappedType = Util.unwrapNonNull(inputType);
        for (GraphQLScalarType scalarType : scalarTypes) {
            if (scalarType.equals(unwrappedType)) {
                return true;
            }
        }
        return false;
    }
}
```

Though you may just want to wait for the validation library to be updated.

**Comment by brendamckenne** [comment]
Thanks for throwing a light in right direction.

Actually the extended-validaiton library and java-tools library are so closely associated and people are using it as if they both are from the same source.
That's why it is becoming difficult to figure out if an issue is related to java-validation library or it has something to do with java-tools

Like 1 update from java-tools could make/break validation library.
Vice-versa
