### ISSUE TITLE
Altair Basepath not found after update to 7.0.1

### ISSUE THREAD

**Issue by coderDem** [graphql-java-kickstart/graphql-spring-boot#383]
Hello,

after the update from 6.0.1 to 7.0.1 Altair has a problem to load the files,
since the base path is wrong.
`GET http://vendor/altair/styles.css net::ERR_NAME_NOT_RESOLVED
altair:49`

`GET http://vendor/altair/runtime.js net::ERR_NAME_NOT_RESOLVED
altair:50` 

`GET http://vendor/altair/polyfills.js net::ERR_NAME_NOT_RESOLVED
altair:51` 

`GET http://vendor/altair/main.js net::ERR_NAME_NOT_RESOLVED
altair:39` 

`GET http://vendor/altair/assets/img/logo_350.svg net::ERR_NAME_NOT_RESOLVED
vendor/altair/favicon.ico:1` 

`GET http://vendor/altair/favicon.ico net::ERR_NAME_NOT_RESOLVED`

I can set the basepath manually, but this should be not the solution.

**Comment by coderDem** [comment]
Ok, if I let the basepath in my properties empty it works for the Version 7.0.1:

`altair.static.basePath=`

**Comment by oliemansm** [comment]
Can you retest this with 7.1.0-SNAPSHOT (add snapshot repo: https://github.com/graphql-java-kickstart/graphql-spring-boot#snapshots). Believe I fixed it already for the upcoming release.

**Comment by coderDem** [comment]
Hello @oliemansm,

in the SNAPSHOT-repository: https://oss.jfrog.org/artifactory/oss-snapshot-local I could only find the version 7.0.2-SNAPSHOT. I tested it with the version 7.0.2-SNAPSHOT and does not work.
You can give me a update if you load the 7.1.0-SNAPSHOT to the  https://oss.jfrog.org/artifactory/oss-snapshot-local.

**Comment by oliemansm** [comment]
Just deployed 7.1.0-SNAPSHOT with a fix. Can you try it again?

**Comment by coderDem** [comment]
Helo @oliemansm,

I have tested it with 7.1.0-SNAPSHOT. It does not work. :(

**Comment by oliemansm** [comment]
Even after clearing your cache? Because [this sample](https://github.com/graphql-java-kickstart/samples/tree/master/file-upload) uses altair too without specifying the base path without any problems.

**Comment by coderDem** [comment]
Hello @oliemansm,

I cleared the cache. It does work. 👍 
And thank you for the example how to upload a file.

**Comment by oliemansm** [comment]
Ok, nice. There's a problem with Altair and uploading a file unfortunately (see #262), but this approach should work if you use it directly.
