### ISSUE TITLE
Cannot override SimpleDataFetcherExceptionHandler

### ISSUE THREAD

**Issue by erdenebadral** [graphql-java-kickstart/graphql-spring-boot#384]
Hi,
Thank you for this great implementation. I am using version 7.0.1.
Facing problem with exception handling. Tried lots of different ways. like this one: [https://github.com/leangen/graphql-spqr/issues/219](url)

`@Configuration
public class GraphQLConfig {
    
  @Bean
  public GraphQL graphQL(GraphQLSchema schema)
  {
      return GraphQL.newGraphQL(schema)
              .queryExecutionStrategy(new AsyncExecutionStrategy(new CustomExceptionHandler()))
              .mutationExecutionStrategy(new AsyncSerialExecutionStrategy(new CustomExceptionHandler()))
              .build();
  } 
}`
Also have 
`public class CustomExceptionHandler implements DataFetcherExceptionHandler {

  @Override
  public DataFetcherExceptionHandlerResult onException(
      DataFetcherExceptionHandlerParameters handlerParameters) {

    Throwable exception = handlerParameters.getException();

    // do something with exception
    System.out.println("asdadad");

    GraphQLError error = GraphqlErrorBuilder.newError().message(exception.getMessage()).build();

    return DataFetcherExceptionHandlerResult.newResult().error(error).build();
  }
}`

My **CustomExceptionHandler** is not triggering. 
Please, help to solve this issue.
P.S: I am new in GraphQL, also sorry my english.

**Comment by oliemansm** [comment]
You're trying a solution from a different GraphQL project that's using a different approach. That's not going to work.

This library provides exception handling using the `@ExceptionHandler` annotation from Spring Boot. Just enable the feature by setting `graphql.servlet.exception-handlers-enabled: true` as stated in the [README](https://github.com/graphql-java-kickstart/graphql-spring-boot#enable-graphql-servlet).

If you don't do anything else it'll simply translate every exception into a `GraphQLError` with the message from the thrown exception (instead of always returning "Internal Server Error"). If you want to customize the returned error just add a method to one of your beans returning a `GraphQLError` or a List of `GraphQLError` and annotate it with `@ExceptionHandler`, e.g.

```java
@ExceptionHandler
GraphQLError myCustomHandler(Exception e) {
  return GraphQLErrorBuilder.newError().message(e.getMessage()).build();
}
```

**Comment by erdenebadral** [comment]
Thank you for quick response and clarification.
It's working like a charm. 
```java
@Component
public class GraphQLExceptionHandler {

  @ExceptionHandler(CustomValidationException.class)
  GraphQLError myCustomHandler(CustomValidationException e) {   
    return GraphqlErrorBuilder.
        newError()
        .extensions(
            e.getExtensions())
        .message(e.getMessage())
        .build();
  }
}
```
If you mind, i have one more question.
The respond is 
```json
{
  "errors": [
    {
      "message": "Custom Error Message",
      "locations": [],
      "extensions": {
        "name": "must not be empty",
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": null
}
```
I want my response without location and classification. like
```json
{
  "errors": [
    {
      "message": "Custom Error Message",      
      "extensions": {
        "name": "must not be empty"        
      }
    }
  ],
  "data": null
}
```
I've tried location to set null but no luck.
Is there any way to control or customize response?
Thank you again.

**Comment by erdenebadral** [comment]
My main goal is to add Spring Boot Bean Validation.

Mutation is:
```java
@Transactional
  public Book addBook(BookInput input) {
    ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
    Validator validator = factory.getValidator();

    Book book =
        Book.builder().name(input.getName()).publishedDate(input.getPublishedDate()).build();
    Set<ConstraintViolation<Book>> constraintViolations = validator.validate(book);
    if (constraintViolations.isEmpty()) {
      return bookRepository.save(book);
    } else {
      Map<String, String> message = new HashMap<String, String>();
      for (ConstraintViolation<Book> contraints : constraintViolations) {
        message.put(contraints.getPropertyPath().toString(), contraints.getMessage());
      }
      throw new CustomValidationException(message);
    }

  }
```

**Comment by oliemansm** [comment]
You could create a custom implementation of `GraphQLError` and return that. If you return `null` for the `locations` and just limit the values returned by `getExtensions()` you should get the result you're after.

**Comment by erdenebadral** [comment]
Thank you very much.
If someone looking code example:
```java
public class CustomGraphQLError implements GraphQLError {

  private static final long serialVersionUID = 1L;

  private String message;
  private final Map<String, Object> extensions;

  public CustomGraphQLError(String message, Map<String, Object> extensions) {
    this.extensions = extensions;
    this.message = message;
  }
  @Override
  public String getMessage() {
    return message;
  }

  @Override
  public List<SourceLocation> getLocations() {
    return null;
  }

  @Override
  public ErrorClassification getErrorType() {
    return null;
  }

  @Override
  public Map<String, Object> getExtensions() {
    return extensions;
  }

}
```java
@Component
public class GraphQLExceptionHandler {

  @ExceptionHandler(CustomValidationException.class)
  GraphQLError myCustomHandler(CustomValidationException e) {
    CustomGraphQLError customError = new CustomGraphQLError(e.getMessage(), e.getExtensions());
    return customError;
  }

}
```java
public class CustomValidationException extends RuntimeException implements GraphQLError {

  private static final long serialVersionUID = 1L;
  private final HashMap<String, Object> extensions;

  public CustomValidationException(Map<String, String> message) {
    super("Validation Error");
    extensions = new HashMap<String, Object>();
    extensions.putAll(message);
  }

  @Override
  public List<SourceLocation> getLocations() {    
    return null;
  }

  @Override
  public ErrorType getErrorType() {
    return null;
  }

  @Override
  public Map<String, Object> getExtensions() {
    return extensions;
  }

}
```
```java
@Transactional
  public Book addBook(BookInput input) {
    ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
    Validator validator = factory.getValidator();

    Book book =
        Book.builder().name(input.getName()).publishedDate(input.getPublishedDate()).build();
    Set<ConstraintViolation<Book>> constraintViolations = validator.validate(book);
    if (constraintViolations.isEmpty()) {
      return bookRepository.save(book);
    } else {
      Map<String, String> message = new HashMap<String, String>();
      for (ConstraintViolation<Book> contraints : constraintViolations) {
        message.put(contraints.getPropertyPath().toString(), contraints.getMessage());
      }
      throw new CustomValidationException(message);
    }

  }
```
