### ISSUE TITLE
GraphQLErrorHandler not working after updating from 6.0.1 to 7.0.1

### ISSUE THREAD

**Issue by Chaniro** [graphql-java-kickstart/graphql-spring-boot#390]
I updated my project from 6.0.1 to 7.0.1 (which makes me renaming some imports from `com.coxautodev.graphql.tools.*` to `graphql.kickstart.tools.*` by the way).

Now my `GraphQLErrorHandler` doesn't work, the default one (`DefaultGraphQLErrorHandler`) is used instead.

Here is how it looks like :
```java
@Component
public class MyGraphQLErrorHandler implements GraphQLErrorHandler {
    @Override
    public List<GraphQLError> processErrors(List<GraphQLError> errors) {
        // This code is never called
    }
}
```

Any suggestion ?

**Comment by oliemansm** [comment]
Please search closed issues too before raising an issue. Fix is already part of next release #379. You could use the snapshot version in the meantime if you want (see README how).
