### ISSUE TITLE
Custom Directive not exposed in Introspective response

### ISSUE THREAD

**Issue by amarflybot18** [graphql-java-kickstart/graphql-spring-boot#394]
HI,

Is there a particular reason why is custom Directive not exposed in graphql Introspective response. This is important for Apollo Federation to find directives used in types.

Referring to the example used in https://github.com/graphql-java-kickstart/samples

This is the schema that is generated by playground after having introspection run.

```graphql
input InputObject {
  value: Float
  nolimit: Float
  limit: Float
}

# directive @Max(value : Int! = 2147483647, message : String =
# "graphql.validation.Max.message") on ARGUMENT_DEFINITION |
# INPUT_FIELD_DEFINITION
type Query {
  hello(value: String!): String
  limitedValue(value: Float!): Float
  limitedInt(value: Int!): Int
  withInput(input: InputObject): Float
}


```

Thanks

**Comment by oliemansm** [comment]
Could you raise this issue at [graphql-java](https://github.com/graphql-java/graphql-java) instead? Since this library wraps that library and delegates responsibility for the introspection query to that library.

**Comment by amarflybot18** [comment]
Sure thanks

**Comment by amarflybot18** [comment]
https://github.com/graphql-java/graphql-java/pull/1756
