### ISSUE TITLE
so, in my company project, the return response has a uniform format, how can i change the graphQL-response to a custom format?

### ISSUE THREAD

**Issue by lin362234867** [graphql-java-kickstart/graphql-spring-boot#399]
graphQL response as 
{
data{
    a{
       name: '123'
   }
}
}
but I want the response format as 
{
  code: 200,
  msg: 'OK',
  data:{
  }
}

**Comment by neerajsu** [comment]
Both code and msg here is redundant as a successful response is 200, which means OK.

When you create a GraphQL api, it generally returns 200 unless there is an error in pipeline during request processing. When this happens it has nothing to do with GraphQL api.

For business logic related error handling when you return, for example, 400 BAD REQUEST (example:- when some logic defines that a request is not valid), you can return those contextual information in error object which is NOT part of data. Notice how I added fields to extensions objects in errors

```json
{
  "errors": [
    {
      "message": "Exception while fetching data (/viewer/customer) : User does not have privileges for processing this request'",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "viewer",
        "customer"
      ],
      "extensions": {
        "code": "400",
        "msg" : "OK",
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": {
    "viewer": {
      "customer": null
    }
  }
}
```

When the message is processed successfully with no errors, the customer object inside data will be populated and will not return as null.

To enable such functionality you need to make slight tweaks to what is available out of the box with this library's error handling. See this blog post for detailed explanation ---> [here](https://medium.com/@philippechampion58/understanding-graphql-error-handling-mechanisms-in-spring-boot-604301c9bedb)

I'm assuming you are moving from a RestAPI to GraphQL. With that assumption, you will need to change your response to adhere to GraphQL practices.

**Comment by oliemansm** [comment]
Thanks @neerajsu for the detailed response. Think that says it all. @lin362234867 Take a look at https://graphql.org/learn/ too to get some more background about GraphQL.
