### ISSUE TITLE
Release please: Error handling fix

### ISSUE THREAD

**Issue by rwilliams-r7** [graphql-java-kickstart/graphql-spring-boot#401]
Was hoping you could do a graphql-spring-boot release for the commit: a9b0a8efdb11f408fd6a095620f74b9ce2441d1b. 

All our error handling is broken and we need this fix, do you have an eta on when this will be out?

**Comment by rwilliams-r7** [comment]
@oliemansm Sorry for the ping, just any update, trying to work out if we should down grade in the mean time.

**Comment by oliemansm** [comment]
Will release in the next few days.

**Comment by rwilliams-r7** [comment]
Thank you so much!
