### ISSUE TITLE
Deprecated introspectionEnabled but new property not accepted

### ISSUE THREAD

**Issue by ubarua123** [graphql-java-kickstart/graphql-spring-boot#402]
I am on `graphql-spring-boot-autoconfigure` version `7.0.1`. I suddenly see that `graphql.tools.introspection-enabled` is deprecated. The new property is `graphql.tools.schema-parser-options.introspection-enabled` but springboot **can't find it** neither is it accepted.
Can anybody point me to what am I doing wrong?

![image](https://user-images.githubusercontent.com/8141308/80277188-f0f17480-870a-11ea-9d4b-2decc3daf33b.png)

And because of this, I had managed to turn off introspection logging, now that's back on polluting the entire console. I have both the properties in my project and I don't know which ones working.

**Comment by setchy** [comment]
I have the same problem @ubarua123.  I am looking to disable introspection within my production environment, but neither the deprecated property `graphql.tools.introspection-enabled` or its suggested successor `graphql.tools.schema-parser-options.introspection-enabled` are working

**Comment by setchy** [comment]
After a little bit of digging I've discovered this feature has been replaced by using
 GraphqlFieldVisibility

As an example

```
@Bean
GraphqlFieldVisibility disableIntrospection() {
   return new NoIntrospectionGraphqlFieldVisibility();
}
```

**Comment by KylinDC** [comment]
It's still not working for me. It still will get into the `DefaultGraphqlFieldVisibility` when I try to get graphql introspection.

**Comment by oliemansm** [comment]
@setchy Thanks for pointing out the workaround. I've reinstated the original property that is also still mentioned in the README. When set to `false` it'll instantiate the `NoIntrospectionGraphqlFieldVisibility` bean like your example. It'll log a warning about putting your server in contravention of the GraphQL specification when doing so.
