### ISSUE TITLE
[Need Guidance]: From client side( say POSTMAN), how can we query to retrieve results satisfying specific value in the output.

### ISSUE THREAD

**Issue by CuriousQA** [graphql-java-kickstart/graphql-spring-boot#409]
My request has multiple queries. Is there any way I can filter out the results that match the status "PENDING"

query statusCheck {
    Status0: verify(id: "1000"  )
    {        ...results }
    Status11: verify(id: "1001"  )
    {        ...results }
    Status10: verify(id: "1002"  )
    {        ...results }
    Status2: verify(id: "1003"  )
    {        ...results }
    Status3: verify(id: "1004"  )
    {        ...results }
    Status4: verify(id: "1005"  )
    {        ...results }
    Status5: verify(id: "1006"  )
    {        ...results }
    Status6: verify(id: "1007"  )
    {        ...results }
    Status7: verify(id: "1008"  )
    {        ...results }
    Status8: verify(id: "1009"  )
    {        ...results }
    Status9: verify(id: "1010"  )
    {        ...results } }
 
 fragment results on Status{
         Details {
        val
         Date}
        
 }

There are many possible values for Val in the status. Sometimes, it takes AWAITING as well as PENDING. Suppose the above query gives result in the following
1000, 1003, 1005 -> {SUCCESS},{SUCCESS},{SUCCESS}
1002, 1004       --> {AWAITING},{AWAITING}
1001,1006 --> { { AWAITING}, {SUCCESS}} , {{AWAITING},{PENDING}}
1007,1008 --> {PENDING}, {PENDING}
1009,1010 -- > {FAILURE},{FAILURE}

then how can I apply a filter on "Val", so that all records that do not have AWAITING will be displayed in my output.

Here I need the results of the records 1000,1003,1005,1007,1008,1009 & 1010 in the output and ignore 1001, 1002, 1004 & 1006.

**Comment by oliemansm** [comment]
Don't see how this is related to this project? Please keep issues here specific to this library. For general GraphQL related questions you're better off at Stackoverflow.
