### ISSUE TITLE
Customize message "Exception while fetching data... "

### ISSUE THREAD

**Issue by AndreKunitz** [graphql-java-kickstart/graphql-spring-boot#411]
Need guidance.

I want to make the error message more concise and remove the "Exception while fetching data" that is wraped by `ExceptionWhileDataFetching`.
Also, if possible, remove `locations`, `path` and `extensions`, if possible.

I made a custom Error that extends `RuntimeException` and implements `GraphQLError`, but that only appends the my custom message to "Exception while fetching data (/getUser) : My custom message"

I've implemented a custom `GraphQLErrorHandler` and anotate it with @Component, but got stuck there. 

Any ideas?

```
{
  "errors": [
    {
      "message": "Exception while fetching data (/getUser) : ...",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "getUser"
      ],
      "extensions": {
        "classification": "DataFetchingException"
      }
    }
  ],
```

**Comment by oliemansm** [comment]
Have you enabled `exception-handlers-enabled` as mentioned in the README? Why do you want to remove those fields? That would make the error response no longer be compliant with GraphQL spec.

**Comment by AndreKunitz** [comment]
Thanks a lot @oliemansm

That did the trick. 

Enabling `exception-handlers-enabled` and creating a custom Error that extends `RuntimeException` and implements `GraphQLError` returned me the following: 

```
{
  "errors": [
    {
      "message": "My messge"
    }
  ],
  "data": {
    "getUser": null
  }
}
```

Is this the correct approach?

**Comment by oliemansm** [comment]
Yeah, although you don’t even have to implement GraphQLError. Just enabling that prop will grab the message of any exception. You only need GraphQLError if you want to customize the error response.

**Comment by AndreKunitz** [comment]
Got it. Thanks again. 

Closing this issue.
