### ISSUE TITLE
annotations instead of marker interfaces

### ISSUE THREAD

**Issue by xenoterracide** [graphql-java-kickstart/graphql-spring-boot#414]
just getting started with this, but instead of empty marker interfaces, e.g.

```java
@Component
class UserQuery implements GraphQLQueryResolver {
}
```
could we have this instead? note: spring annotations are "composable" meaning you can make this "extend" `@component`.

```java
@GraphQLQueryResolver
class UserQuery  {
}

**Comment by oliemansm** [comment]
The interface comes from graphql java tools which is also usable this way without using spring.
