### ISSUE TITLE
Please publish new release 7.1.0

### ISSUE THREAD

**Issue by ImaBird** [graphql-java-kickstart/graphql-spring-boot#418]
Hello, 

There are a lot of improvements and bug-fixes since previous release.
As I can see, all of issues in 7.1.0 milestone are closed. Could you please publish new release?

Thank you!

**Comment by Kadenwxz** [comment]
Yeah, could we prioritize releasing 7.1.0?

**Comment by BlasiusSecundus** [comment]
Hi @oliemansm, is there a planned date for 7.1 release? Are there any further issues that need to be resolved before this release?

**Comment by oliemansm** [comment]
Traveling atm, will do a release this Sunday when I arrive.

**Comment by oliemansm** [comment]
Just released it
