### ISSUE TITLE
/graphql POST method not supported if Graphql Spring boot application is deployed on aws lambda

### ISSUE THREAD

**Issue by gaurav-tanwar-gt** [graphql-java-kickstart/graphql-spring-boot#421]
**Describe the bug**
When try to hit POST /graphql endpoint (Graphql Spring boot app deployed on aws lambda) then 
/graphql POST method not supported 

**Expected behavior**
It should work as it work on ECS 

using 
aws-serverless-java-container-springboot2 to deploy spring boot on AWS lambda

**Comment by oliemansm** [comment]
This issue should be raised on Stackoverflow instead if you're not able to figure out the root cause of this. We don't provide any support for specific deployments. The libary itself supports POST method, so I don't see any indication here this is a bug in this library. Once you've found the cause you're experiencing this problem and there's something in this library causing that or an improvement you want to suggest then feel free to create a new issue with enough details to be able to do something about it. Or better yet: create a PR to address that.

**Comment by somadeaki** [comment]
I am facing the same exact issue. The app works locally, but returns 405 Method Not Allowed when trying to hit /graphql in a lambda deployment. I do believe it is a bug in the framework, since I've followed the readme instructions to the letter.

@gaurav-tanwar-gt were you ever able to figure out how to fix this?

**Comment by gaurav-tanwar-gt** [comment]
package project.config;

import graphql.kickstart.servlet.GraphQLHttpServlet;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.CorsRegistry;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
import org.springframework.web.servlet.handler.SimpleServletHandlerAdapter;
import org.springframework.web.servlet.handler.SimpleUrlHandlerMapping;

import java.util.HashMap;

@Configuration
@EnableWebMvc
public class WebConfig implements WebMvcConfigurer {

    @Autowired
    GraphQLHttpServlet graphQLHttpServlet;

    @Override
    public void addCorsMappings(CorsRegistry registry) {
        registry.addMapping("/**")
                .allowedOrigins("*")
                .allowedMethods("GET", "POST", "DELETE", "OPTIONS", "PUT");
    }
    // this will solve ur problem
    @Bean
    public SimpleUrlHandlerMapping simpleUrlHandlerMapping() {
        var simpleUrlHandlerMapping = new SimpleUrlHandlerMapping();

        var map = new HashMap<String, Object>();
        map.put("/graphql", graphQLHttpServlet);

        simpleUrlHandlerMapping.setUrlMap(map);
        return simpleUrlHandlerMapping;
    }

    @Bean
    public SimpleServletHandlerAdapter simpleServletHandlerAdapter() {
        return new SimpleServletHandlerAdapter();
    }
}

**Comment by gaurav-tanwar-gt** [comment]
@somadeaki 
above should solve ur problem 
and at last import this config in app

like this import org.springframework.boot.SpringApplication;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;
import org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration;
import org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration;
import org.springframework.context.annotation.Import;
import project.config.WebConfig;


@SpringBootConfiguration
@EnableAutoConfiguration(exclude = {
        DataSourceAutoConfiguration.class,
        DataSourceTransactionManagerAutoConfiguration.class,
        HibernateJpaAutoConfiguration.class
})
@Import({WebConfig.class})
public class SpringBootApplication {
    public static void main(String[] args) {
        SpringApplication.run(SpringBootApplication.class, args);
    }
}
i hope this will solve your problem

**Comment by somadeaki** [comment]
@gaurav-tanwar-gt thank you for the quick response! I was able to get it up and running using @EnableWebMvc and the manual url handler mapping. Unfortunately I have not been able to locate the source of the bug - if I find it I'll put in a PR.
