### ISSUE TITLE
Multiple mutations in one request

### ISSUE THREAD

**Issue by cleanoxi** [graphql-java-kickstart/graphql-spring-boot#423]
I have multiple mutations of the same kind that I want to execute in a single transaction. Can I do this?

`type Mutation {
    editAuthor(author: String!, book: String!): Boolean
}

mutation updateDetails {
    editAuthor(author: "Stephen King", book: "Castle Rock")
    editAuthor(author: "Kurt Vonnegut", book: "Cat's Cradle")
}`

**Comment by BlasiusSecundus** [comment]
Yes, you can do that using aliases: https://graphql.org/learn/queries/#aliases

```graphql
mutation updateDetails {
    king: editAuthor(author: "Stephen King", book: "Castle Rock")
    vonnegut: editAuthor(author: "Kurt Vonnegut", book: "Cat's Cradle")
}
```
