### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by huehnerlady** [graphql-java-kickstart/graphql-spring-boot#425]
Hi,

I can see this package is updated in 2018 in maven repository. 
With that a lot of dependencies are quite out of date.

Please update everything to the latest versions

Thanks 🙂

**Comment by oliemansm** [comment]
@huehnerlady The group changed at that time, see the readme for the correct group.

**Comment by huehnerlady** [comment]
@oliemansm many thanks. Not sure how that works, but in maven repository you can mark dependencies who changes group-id, see [junit](https://mvnrepository.com/artifact/junit/junit) for example. Maybe something like that makes sense for these dependencies? If that were the case I would have found the right dependency straight away 🙂

**Comment by oliemansm** [comment]
@huehnerlady Hmm, didn't know that was an option. Not a clue how that works though...

**Comment by huehnerlady** [comment]
I have no idea, but if it helps I can try to find out? :)

**Comment by oliemansm** [comment]
All help is welcome, so if you have time to try to find out it would be much appreciated :)
