### ISSUE TITLE
Unable to run spring-boot-webflux sample

### ISSUE THREAD

**Issue by sseep** [graphql-java-kickstart/graphql-spring-boot#428]
I downloaded project [spring-boot-webflux](https://github.com/graphql-java-kickstart/samples/tree/master/spring-boot-webflux)  and
HAS NOT modify any file. 
Run spring-boot-webflux sample still got error.
```
Description:

Parameter 1 of method webSocketHandlerMapping in graphql.kickstart.spring.webflux.boot.GraphQLSpringWebfluxAutoConfiguration required a bean of type 'graphql.kickstart.spring.webflux.ReactiveWebSocketSubscriptionsHandler' that could not be found.


Action:

Consider defining a bean of type 'graphql.kickstart.spring.webflux.ReactiveWebSocketSubscriptionsHandler' in your configuration.
```

[https://github.com/graphql-java-kickstart/samples/issues/6#issuecomment-648046669](https://github.com/graphql-java-kickstart/samples/issues/6#issuecomment-648046669)

**Comment by Tandolf** [comment]
i have the same issue, i downgraded to version 7.0.1 and it started working then

**Comment by sseep** [comment]
> i have the same issue, i downgraded to version 7.0.1 and it started working then

thank you. i will try

**Comment by phongphan** [comment]
The AutoConfiguration class doesn't seems to work well with the @ComponentScan. The `graphql.kickstart.spring.webflux.ReactiveWebSocketSubscriptionsHandler` didn't pick up by spring.

I have to add this to my configuration class.

```
    @Bean
    @ConditionalOnMissingBean
    ReactiveWebSocketSubscriptionsHandler reactiveWebSocketSubscriptionsHandler(ReactiveSubscriptionsProtocolFactory factory) {
        return new ReactiveWebSocketSubscriptionsHandler(factory);
    }
```

**Comment by phongphan** [comment]
I think adding above snippet to the `GraphQLSpringWebfluxAutoConfiguration.java` should work too. But I don't have enough confident that it solved the primary cause.

**Comment by phongphan** [comment]
Sorry for the comment spam. But for my case, the component scan doesn't seem to work at all.

Now my configuration class is look like this:
```
package test;

import graphql.kickstart.execution.GraphQLInvoker;
import graphql.kickstart.execution.GraphQLObjectMapper;
import graphql.kickstart.spring.GraphQLSpringInvocationInputFactory;
import graphql.kickstart.spring.webflux.GraphQLController;
import graphql.kickstart.spring.webflux.ReactiveSubscriptionsProtocolFactory;
import graphql.kickstart.spring.webflux.ReactiveWebSocketSubscriptionsHandler;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class MyTestConfiguration {

    @Bean
    @ConditionalOnMissingBean
    ReactiveWebSocketSubscriptionsHandler reactiveWebSocketSubscriptionsHandler(ReactiveSubscriptionsProtocolFactory factory) {
        return new ReactiveWebSocketSubscriptionsHandler(factory);
    }

    @Bean
    @ConditionalOnMissingBean
    GraphQLController graphQLController(GraphQLObjectMapper objectMapper, GraphQLInvoker graphQLInvoker, GraphQLSpringInvocationInputFactory invocationInputFactory) {
        return new GraphQLController(objectMapper, graphQLInvoker, invocationInputFactory);
    }
}
```

Not sure if the `ConditionalOnBean` added in the [d865b8cee499685ac2e155915cff576cc424bc3c] breaks the `ComponentScan`.

**Comment by Mixel2142** [comment]
Hello to all. If we remove the @ConditionalOnBean ({GraphQLSchema.class}) annotation in the public class GraphQLSpringWebfluxAutoConfiguration, it works fine.

**Comment by oliemansm** [comment]
Fixed by implementing https://github.com/graphql-java-kickstart/samples/issues/6#issuecomment-649137889
