### ISSUE TITLE
Wrong Altair version for static package

### ISSUE THREAD

**Issue by Larkhis** [graphql-java-kickstart/graphql-spring-boot#433]
First of all, Thanks for this great job.

**Describe the bug**
After upgrading graphql-spring-boot version from 7.0.0 to 7.1.0 I noticed in altair-spring-boot-autoconfigure maven dependencies that altair was not updated. The version remains in 2.1.7 version instead of 2.4.6.

**Expected behavior**
Have the 2.4.6 altair static package for graphql-spring-boot 7.1.0 version.

**Comment by coderDem** [comment]
Hello @Larkhis,

thank you for the update. But the index.html seems to be not right. 
It should look like this:

`<!doctype html>
<html>

  <head>
    <meta charset="utf-8">
    <title>Altair</title>
    <base href="https://unpkg.com/altair-static@latest/build/dist/">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="favicon.ico">
    <link rel="stylesheet" href="styles.css">
  </head>

  <body>
    <script>
		document.addEventListener('DOMContentLoaded', () => {
      AltairGraphQL.init();
    });
    </script>
    <app-root>
      <style>
        .loading-screen {
          /*Prevents the loading screen from showing until CSS is downloaded*/
          display: none;
        }

      </style>
      <div class="loading-screen styled">
        <div class="loading-screen-inner">
          <div class="loading-screen-logo-container">
            <img src="assets/img/logo_350.svg" alt="Altair">
          </div>
          <div class="loading-screen-loading-indicator">
            <span class="loading-indicator-dot"></span>
            <span class="loading-indicator-dot"></span>
            <span class="loading-indicator-dot"></span>
          </div>
        </div>
      </div>
    </app-root>
    <script type="text/javascript" src="runtime.js"></script>
    <script type="text/javascript" src="polyfills.js"></script>
    <script type="text/javascript" src="main.js"></script>
  </body>

</html>
`

This part is important as fallback for the webworker:
`    <script>
		document.addEventListener('DOMContentLoaded', () => {
      AltairGraphQL.init();
    });
    </script>`

Could you please update your fix?

**Comment by Larkhis** [comment]
Hello @coderDem 
Yes you was right.
Branche updated and tested.
