### ISSUE TITLE
Need to have ability to configure dataloader

### ISSUE THREAD

**Issue by yduchesne** [graphql-java-kickstart/graphql-spring-boot#44]
Hi, based on the example [here](https://medium.com/@bradbaker/big-movements-in-the-graphql-java-world-67629fd45508), I've set up the following Spring config in the context of a Spring Boot app levering the present project:

```
@Configuration
@Slf4j
public class DataLoaderConfig {

    @Autowired
    private Dao<Author>    authorDao;

    @Autowired
    private Dao<Publisher> publisherDao;

    @Autowired
    private Dao<Book>      bookDao;

    @Bean
    public Instrumentation instrumentation() {
        log.info("Creating GraphQL execution instrumentation");

        final AuthorBatchLoader    authorBatchLoader    = new AuthorBatchLoader(authorDao);
        final BookBatchLoader      bookBatchLoader      = new BookBatchLoader(bookDao);
        final PublisherBatchLoader publisherBatchLoader = new PublisherBatchLoader(publisherDao);


        final DataLoader<Integer, Author>    authorDataLoader    = new DataLoader<>(authorBatchLoader);
        final DataLoader<Integer, Book>      bookDataLoader      = new DataLoader<>(bookBatchLoader);
        final DataLoader<Integer, Publisher> publisherDataLoader = new DataLoader<>(publisherBatchLoader);

        final DataLoaderRegistry registry = new DataLoaderRegistry();
        registry.register("authors", authorDataLoader);
        registry.register("books", bookDataLoader);
        registry.register("publishers", publisherDataLoader);

        return new DataLoaderDispatcherInstrumentation(registry);
    }
}
``` 
And BTW, I'm using the resolver support, as in the following:
```
@RequiredArgsConstructor
public class AuthorResolver implements GraphQLResolver<Author> {

    private final Dao<Author> authors;

    public Author author(int id) {
        return authors.findById(id);
    }

    public List<Author> authors(int index, int maxResults) {
        return authors.paginate(index, maxResults);
    }

}
```
There seems to be a bit of abstraction involved, and I'm uncertain about how resolvers correspond to data fetchers (I suspecting that my resolvers are invoked by some generic that fetcher wrapping them). So I'm not clear as to how this type of abstraction may play into the data loading I've configured being used or not...

At runtime, I can see the the SimpleGraphQLServlet instance uses the DataLoaderDispatcherInstrumentation created above (added traces that show the servlet holding the instrumentation instance), but the instrumentation is not being used for loading. Not sure how to wire things up in the context of the Spring Boot starter so that Dataloader is used, there's no doc I could find on the topic. It would be very useful to be able to benefit from the Dataloader support when using the Spring Boot starter. 

Can you provide steps to move forward? Thanks.

**Comment by jkwatson** [comment]
Would love to have first-class support for DataLoaders, as well, since they're the only non-deprecated way to do batching.

**Comment by oliemansm** [comment]
Closing, since support for this has been added in the meantime. See also https://github.com/graphql-java-kickstart/graphql-spring-boot/tree/master/example-request-scoped-dataloader.

**Comment by adityadrao** [comment]
This example is perfect, just one thing it needs more is to explain on how additional parameters received in a Resolver would be passed to the DataLoader.


Consider the example schema 

```
type Query {
   products(productId: [Int]!): [Product]
}

type Product {
    productId: Int
    name: String
    transactions(fromDate: String, toDate: String): [Transaction]
}

type Transaction {
    transactionId: String
    value: Float
    quantity: Int
}
```


and the query that I would want to send is to get all transactions that have happened between 20-MAR and 22-MAR for products 3,5 & 7.

```
products ( productId: [3,5,7] ){
    productId
    name
    transactions(fromDate:"20-MAR-2020", toDate: "22-MAR-2020"){
        transactionId
        quantity
    }
}
```


Using DataLoader I am able to reduce the trips to the transaction data source(db, api)
I don't do 3 trips, but only one with all 3 product Ids passed as the List<keys>.

However the DataLoader, BatchLoader does not have provision to pass the parameters **fromDate** & **toDate**.

**Comment by thrkrdk** [comment]
> Closing, since support for this has been added in the meantime. See also https://github.com/graphql-java-kickstart/graphql-spring-boot/tree/master/example-request-scoped-dataloader.

Hi @oliemansm How I can use CustomGraphQLContextBuilder  for multiple registry
