### ISSUE TITLE
Configure the use of custom ObjectMapper for GraphQL

### ISSUE THREAD

**Issue by Nxtra** [graphql-java-kickstart/graphql-spring-boot#447]
How can I specify an ObjectMapper that has to be used when calling the `/graphql` endpoint?

I found this issue: https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/97. Where a combination of `ObjectMapperConfigurer` and `schemaParserOptions` is mentioned.

I currently have the following `JacksonConfig`. 

```
@Configuration
public class JacksonConfig {

    @Bean
    public ObjectMapper objectMapper() {
        return new ObjectMapper()
                .setDefaultPropertyInclusion(JsonInclude.Include.NON_EMPTY)
                .findAndRegisterModules();
    }

    @Bean
    ObjectMapperConfigurer objectMapperConfigurer() {
        return (mapper, context) -> mapper.setDefaultPropertyInclusion(JsonInclude.Include.NON_NULL);
    }

    @Bean
    SchemaParserOptions schemaParserOptions() {
        return SchemaParserOptions.newOptions()
            .objectMapperConfigurer((ObjectMapper mapper, ObjectMapperConfigurerContext context) -> mapper.setDefaultPropertyInclusion(JsonInclude.Include.NON_NULL))
            .build();
    }
}
```

As you can see I am trying to set a different setting for `DefaultPropertyInclusion` when calling the `\graphql` endpoint.
(This is because I want the empty `interfaces: []` array to be in the response from the introspection)

However, currently with the above configuration, the ObjectMapper with `DefaultPropertyInclusion` = `NON_EMPTY` is still being used when doing the graphql introspection. Instead of the ObjectMapper with `DefaultPropertyInclusion` = `NON_NULL`.

Can you help me with how I should configure a custom ObjectMapper for the queries on `/graphql`?

**Comment by neerajsu** [comment]
What is there a need to set objectMapper in 3 different beans. Just SchemaparserOptions should suffice. Have tried removing the other beans and checking if its working?
