### ISSUE TITLE
What's the difference between com.graphql-java-kickstart and com.graphql-java

### ISSUE THREAD

**Issue by liudonghua123** [graphql-java-kickstart/graphql-spring-boot#450]
In some demo code, I find the dependences is like the following.

```xml
        <!-- GraphQL -->
        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-spring-boot-starter</artifactId>
            <version>${graphql-starter.version}</version>
        </dependency>
        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphiql-spring-boot-starter</artifactId>
            <version>${graphql-starter.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-spring-boot-starter-test</artifactId>
            <version>${graphql-starter.version}</version>
            <scope>test</scope>
        </dependency>
```

and in some other demos, I see the following dependences.

```xml

        <!-- https://mvnrepository.com/artifact/com.graphql-java/graphql-spring-boot-starter -->
        <dependency>
            <groupId>com.graphql-java</groupId>
            <artifactId>graphql-spring-boot-starter</artifactId>
            <version>5.0.2</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.graphql-java/graphiql-spring-boot-starter -->
        <dependency>
            <groupId>com.graphql-java</groupId>
            <artifactId>graphiql-spring-boot-starter</artifactId>
            <version>5.0.2</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.graphql-java/graphql-java-tools -->
        <dependency>
            <groupId>com.graphql-java</groupId>
            <artifactId>graphql-java-tools</artifactId>
            <version>5.2.4</version>
        </dependency>
```

And the home page of https://mvnrepository.com/artifact/com.graphql-java/graphql-spring-boot-starter is https://github.com/graphql-java/graphql-spring-boot, when I clicked, it redirected to the https://github.com/graphql-java-kickstart/graphql-spring-boot. It seems the `com.graphql-java` is deprecated, but both the sites(https://www.graphql-java.com/, https://www.graphql-java-kickstart.com/) are active. It's really confused. Please add some documentation about these history stories.

**Comment by oliemansm** [comment]
These libraries used to be part of graphql-java project, but upon their request have been extracted into a separate organization because they wanted to focus on just graphql-java itself, and not graphql-java-tools and such. There's an old blog post on their documentation site with more details. I've added it in the description of the GraphQL Java Kickstart organization.

**Comment by liudonghua123** [comment]
@oliemansm Thanks for explanation, could you provide the link of the old blog post since I could not find it.

**Comment by learnings225** [comment]
@liudonghua123 https://www.graphql-java.com/blog/moving-projects/
