### ISSUE TITLE
Spring boot + Graphql + Oauth2 how can i secure my single endpoint?

### ISSUE THREAD

**Issue by gantsogtOmbo** [graphql-java-kickstart/graphql-spring-boot#452]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by a-reznic** [comment]
try keycloak.org

**Comment by oliemansm** [comment]
Closing due to insufficient information in question.
