### ISSUE TITLE
How to override GraphQL Context ?

### ISSUE THREAD

**Issue by ankit-joinwal** [graphql-java-kickstart/graphql-spring-boot#456]
Based on some http headers for eg JWT token, i want to set the auth state of a user in GraphQL context so that it is available in all resolver functions where i can build logic on auth state.
How to achieve this in graphql-java-kickstart/graphql-spring-boot

**Comment by neerajsu** [comment]
@ankit-joinwal : You can access any auth related stuff on your resolvers from DatafetchingEnvironment. Just add another parameter in your resolver function (last parameter) : `DataFetchingEnvironment env`.

Example:

Schema

```graphql
type Query {
    getCustomerInfo(id: ID!) : Customer
}

type Customer {
   id: ID!
   name: String!
   address: String!
   canSeeOrders: Boolean!
}
```

Query Resolver:

```java
@Component
public class QueryResolver implements GraphQLQueryResolver {

    public Customer getCustomerInfo(String id, DataFetchingEnvironment env) {
        GraphQLServletContext graphQLServletContext = (GraphQLServletContext) env.getContext();
        // some logic here
        String user = graphQLServletContext.getHttpServletRequest().getHeader("user");
        return customer;
    }
}

```

You can also add env to type resolver

```java
public class CustomerResolver implements GraphQLResolver<Customer> {

   private UserService userService;
   
   @Autowired
   public CustomerResolver(UserService userService) {
       this.userService = userService;
   }

   public boolean canSeeOrders(Customer customer, DataFetchingEnvironment env){
      
      GraphQLServletContext graphQLServletContext = (GraphQLServletContext) env.getContext();
       // some logic here
      String user = graphQLServletContext.getHttpServletRequest().getHeader("user");
      if (userService.getUserInfo(user).getRole().equals("Owner")) {
          return true;
      } else {
         return false;
      }
   }
}
```

**Comment by pstarritt-evooq** [comment]
Create a spring bean that implements GraphQLServletContextBuilder.

Implement GraphQLServletContextBuilder's build methods and return your custom context object. It must implement  GraphQLContext, optionally implement GraphQLServletContext instead. 

Inside the build method you can extract the http headers and create an immutable object to encapsulate your auth data. This is available inside all revolvers via

```
public Stuff resolver(Product product, DataFetchingEnvironment environment){ 
       YourContextClass context = environment.getContext();
        context.getYourData()
        // do stuff
}
```
