### ISSUE TITLE
close the log in SimpleDataFetcherExceptionHandler

### ISSUE THREAD

**Issue by ankelen** [graphql-java-kickstart/graphql-spring-boot#473]
i want to close the log output in SimpleDataFetcherExceptionHandler, what shoud i do?
i have try use logging.level.graphql.execution.SimpleDataFetcherExceptionHandler=none, but it's not working

**Comment by oliemansm** [comment]
You want to reduce the number of logging messages? That class is part of the graphql-java project, not this one. And your question is more generic Spring Boot related. You should double check the documentation of Spring Boot itself what values are supported there. Top of mind I'm not sure if "none" is a valid value. Seeing that particular class only seems to be logging with "warn" level, you could set it to "error" instead.

Having said that: if it's logging warnings and apparently in the amount that it's annoying you. Shouldn't you be actually looking at those warnings and trying to fix them or are they all expected anyway and can be safely ignored?
