### ISSUE TITLE
Ability to Have Multiple Independent Roots by Configuration

### ISSUE THREAD

**Issue by ryandanielspmc** [graphql-java-kickstart/graphql-spring-boot#474]
**Is your feature request related to a problem? Please describe.**

In reference to #186:

> I want to be able to deploy multiple roots in different paths, like this:
> 
> http://localhost/api/v1/ -> resources/api/v1/queyr.graphqls
> http://localhost/api/v2/ -> resources/api/v2/queyr.graphqls
> 
> and then also have different query resolvers as well.

Currently, the only ways that I am aware of that this can be done are:

1. Duplicate the work that this project is doing (misc. bean creation) and hope that it works
2. Create a new independent service to have the new version of schema

Having the ability to do this via configuration as a feature of the project would allow breaking changes without doing one of the precarious options above. 

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
See above.

**Additional context**
N/A

**Comment by oliemansm** [comment]
Closing this issue and reopened the original one.
