### ISSUE TITLE
GraphQLTestTemplate: post() Should Be Public

### ISSUE THREAD

**Issue by ryandanielspmc** [graphql-java-kickstart/graphql-spring-boot#475]
**Is your feature request related to a problem? Please describe.**

GraphQLTestTemplate seems to only allow queries to be read from files. This is very inconvenient. The class should allow inline query / mutate strings.

**Describe the solution you'd like**

Making `post()` public would seem to solve this problem.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by oliemansm** [comment]
This has been added by @BlasiusSecundus and will be part of 8.1.0
