### ISSUE TITLE
Allow graphql.GraphQL.Builder#doNotAddDefaultInstrumentations to be set

### ISSUE THREAD

**Issue by adrian-skybaker** [graphql-java-kickstart/graphql-spring-boot#486]
By default GraphQL Java will add an instance of graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation, which has a performance impact.

This can be disabled using graphql.GraphQL.Builder#doNotAddDefaultInstrumentations - it would be great if we could set this flag somehow from config, or perhaps a custom builder customizer bean.

As a hacky solution I'm registering a custom no-op sub-class of DataLoaderDispatcherInstrumentation which prevents the default registration.

**Comment by oliemansm** [comment]
Version 8.1.0 will contain the option to configure this. You'll have to expose a bean implementing `GraphQLBuilderConfigurer` which has just one method: `configure(GraphQL.Builder builder)`. You can use that one to override settings.
