### ISSUE TITLE
Playground incompatible with Spring Webflux

### ISSUE THREAD

**Issue by ooga** [graphql-java-kickstart/graphql-spring-boot#487]
**Describe the bug**
When we add `playground-spring-boot-starter` in a spring webflux project, the project is instantiated as spring mvc and served with Tomcat

Because `playground-spring-boot-starter` require `spring-boot-starter-web`

**To Reproduce**
1. include these dependencies
	- graphql-kickstart-spring-boot-starter-webflux
	- playground-spring-boot-starter

**Expected behavior**
Project is served with Netty and the playground is accessible

**Comment by BlasiusSecundus** [comment]
The Playgound integration is currently not working with WebFlux. 

I have a WIP fix for the issue, see the linked commit. It seems to work properly but additional tests would be needed (only tested with the bundled webflux sample).

**Comment by varunsufi** [comment]
Is it something blocking here ? Can we merge the proposed solution ?

**Comment by BlasiusSecundus** [comment]
I planned to do some more testing before finalizing the MR but time passes faster than expected... I opened it up to review so that it is not blocked anymore on my side. Help with testing with different setups / feedback is of course appreciated.
