### ISSUE TITLE
Altair Settings Pane Configuration

### ISSUE THREAD

**Issue by JamesPeters98** [graphql-java-kickstart/graphql-spring-boot#529]
I'm just trying to set the default Settings for Altair through the starter. It doesn't seem to currently be implemented unless I've missed something.

I'd like to be able to set these settings: https://altair.sirmuel.design/docs/features/settings-pane.html

There was an issue opened on the Altair repo about this and it doesn't seem like it was added here:
https://github.com/imolorhe/altair/issues/1153

**Comment by oliemansm** [comment]
@JamesPeters98 Release 12.0.0 will contain support for this including IntelliJ property suggestion support. Things have been rearranged a bit, so properties have been moved. Setting the theme already works on the example project on the reorganization branch, see also: https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/9bb473d6d141f21cfa6be3d9d024df364e9b09dc/example/src/main/resources/application.yml#L32.

```yaml
graphql:
  altair:
    options:
      initial-settings:
        theme: dracula
```
