### ISSUE TITLE
max-query-depth: 10 configuration causing errors

### ISSUE THREAD

**Issue by Jojoooo1** [graphql-java-kickstart/graphql-spring-boot#569]
**Describe the bug**
Set graphql.servlet.max-query-depth: 10

**To Reproduce**
1. Go to application.yaml set graphql.servlet.max-query-depth: 10
2. Go to /playground
3. Open developer console: "ServerParseError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"

**Expected behavior**
Playground should be working

**Desktop (please complete the following information):**
- Browser: Firefox
- Version: 87.0 (64-bit)

**Comment by oliemansm** [comment]
I just tried this in an example project using the latest versions and I'm not getting those JSON parse errors. Instead I'm seeing in the console (expected) errors about max query depth being reached:

```
middleware.js:98 Uncaught Error: {
  "errors": [
    {
      "message": "maximum query depth exceeded 13 > 10",
      "extensions": {
        "classification": "ExecutionAborted"
      }
    }
  ],
  "data": null
}
    at Object.next (middleware.js:98)
    at b (middleware.js:98)
    at E (middleware.js:98)
    at e.value (middleware.js:98)
    at middleware.js:124
```

So from my point of view this is working as expected. Sounds like there's a specific problem with your local configuration instead. I'll convert this into a Discussion.
