### ISSUE TITLE
Graphiql does not support Korean.

### ISSUE THREAD

**Issue by mwkang** [graphql-java-kickstart/graphql-spring-boot#57]
Graphiql Page can not display Korean.
Please refer to the screenshot.

![2018-02-13 21 55 09](https://user-images.githubusercontent.com/10624086/36150890-9ab3cee4-1108-11e8-88f3-4cead30fa9b7.png)

**Comment by apottere** [comment]
Do you know how to fix it?  I don't have much experience with issues like that.

**Comment by oliemansm** [comment]
@mwkang Is this caused by the font used by GraphiQL not supporting Korean characters? If that's the case then overriding the font settings with a custom style should do it.

**Comment by oliemansm** [comment]
@mwkang Did that fix it for you?

**Comment by mwkang** [comment]
These days I have a heavy workload So I don't test yet. Sorry.
If I tested, I will leave a comment.
