### ISSUE TITLE
HTTP headers are not available after upgrading to version 11.1.0

### ISSUE THREAD

**Issue by beheshtraya** [graphql-java-kickstart/graphql-spring-boot#638]
After upgrading to version 11.1.0, the request headers are not available anymore.
```
HttpServletRequest curRequest = ((ServletRequestAttributes) RequestContextHolder.currentRequestAttributes()).getRequest();

var headers = curRequest.getHeaderNames()
```

These lines of code are working with versions before 11.1.0, but after upgrading, the `RequestContextHolder` is null.

To reproduce, a graghql request can be made (query or mutation).

- OS: macOS 11.3
- Java: 11
- Browser: Chrome, Postman
- Version 11.1.0

**Comment by oliemansm** [comment]
Turn off async mode using Spring Boot property: `graphql.servlet.async-mode-enabled: false`.

Alternatively you can grab the request from the `DataFetchingEnvironment` instead of this. On any resolver method:

```java
@Component
class Query implements GraphQLQueryResolver {

  /**
   * DataFetchingEnvironment is an optional parameter you can add to any resolver method as last parameter.
   */
  String hello(DataFetchingEnvironment env) {
    GraphQLServletContext context = env.getContext();
    HttpServletRequest request = context.getHttpServletRequest();
    // this way of getting the request is not impacted by the async mode and still works
  }

}
```

In 11.1.0 a bug related to async mode not correctly being started resulted in an unexpected breaking change like this.

**Comment by arjun-oodle** [comment]
> Turn off async mode using Spring Boot property: `graphql.servlet.async-mode-enabled: false`.
> 
> Alternatively you can grab the request from the `DataFetchingEnvironment` instead of this. On any resolver method:
> 
> ```java
> @Component
> class Query implements GraphQLQueryResolver {
> 
>   /**
>    * DataFetchingEnvironment is an optional parameter you can add to any resolver method as last parameter.
>    */
>   String hello(DataFetchingEnvironment env) {
>     GraphQLServletContext context = env.getContext();
>     HttpServletRequest request = context.getHttpServletRequest();
>     // this way of getting the request is not impacted by the async mode and still works
>     return "world";
>   }
> 
> }
> ```
> 
> In 11.1.0 a bug related to async mode not correctly being started was fixed, which resulted in an unexpected breaking change like this.

`env.getContext();` is depricated now. Any alternative to this in 14.0.0 version?

**Comment by oliemansm** [comment]
See the release notes of v13.0.0 and this answer in the Discussions section: https://github.com/graphql-java-kickstart/graphql-spring-boot/discussions/851#discussioncomment-3373272

**Comment by AdityaVashist** [comment]
Try this

@Component
class Query implements GraphQLQueryResolver {

  /**
   * DataFetchingEnvironment is an optional parameter you can add to any resolver method as last parameter.
   */
  String hello(DataFetchingEnvironment env) {
        GraphQLContext context = env.getGraphQlContext();
    ServerWebExchange req = context.get(ServerWebExchange.class);
    HttpHeaders headers = req.getRequest().getHeaders();
    // this way of getting the request is not impacted by the async mode and still works
    return "world";
  }

}
