### ISSUE TITLE
README.md "simple example" link is broken

### ISSUE THREAD

**Issue by Kepler-Br** [graphql-java-kickstart/graphql-spring-boot#640]
**Describe the bug**
README's "Simple example" link is 404

**To Reproduce**
1. Go to https://github.com/graphql-java-kickstart/graphql-spring-boot#enable-graphql-servlet
2. Click 'simple example' link

**Expected behavior**
Well, probably [this repo](https://github.com/graphql-java-kickstart/samples) should be opened instead?

**Desktop:**
- Version: commit [9f6e1c54adbe11b21e4ab579b70be31e3b39948f](https://github.com/graphql-java-kickstart/graphql-spring-boot/tree/9f6e1c54adbe11b21e4ab579b70be31e3b39948f) (Master branch as for 24 May 2021)

**Comment by setchy** [comment]
Thanks @Kepler-Br - broken link has been fixed
