### ISSUE TITLE
GraphQLServletListener's onSuccess is not in request scope after upgrading to 11.1.0

### ISSUE THREAD

**Issue by norbert-sziraczki** [graphql-java-kickstart/graphql-spring-boot#643]
**Describe the bug**
I've encountered a strange bug when upgrading to graphql-spring-boot-starter:11.1.0 from 6.0.
I have a GraphQLServletListener that is used to trigger an applicationEvent using Spring's ApplicationEventPublisher to handle transaction status monitoring. The endpoint for listening to the event stream is scoped per request (WebApplicationContext.SCOPE_REQUEST), and that was working perfectly previously. The GraphQLListener's onRequest set the event to requestStart, the onSuccess of the listener set it to requestEnd. Now after upgrading our dependencies (kotlin 1.4.32, SpringBoot 2.4.5, GQL starter 11.1.0) the bean creation fails for the listener by telling me that there is no request scope (while obviously there should be as I'm currently handling the onSuccess part of the request before the onFinally)
Caused by: java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
Any ideas what's happening, what's changed or what am I doing wrong (and why did it work previously)?

**To Reproduce**
Project is a closed-source, haven't yet created an example project for the bug.

**Expected behavior**
The listener's onSuccess should be in request scope

**Screenshots**

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04

**Comment by oliemansm** [comment]
The default setting has been reverted to false in release 13.0.0 which has just been released.
