### ISSUE TITLE
Working with graphql-java 17.0beta

### ISSUE THREAD

**Issue by softshape** [graphql-java-kickstart/graphql-spring-boot#676]
Any chance to get graphql-spring-boot working with graphql-java 17.0beta ? There's a lot of bugfixes in it we need in production.

**Comment by dmtrkuzmin** [comment]
> Any chance to get graphql-spring-boot working with graphql-java 17.0beta ? There's a lot of bugfixes in it we need in production.

Yes! We need 17.0 beta too

**Comment by dmtrkuzmin** [comment]
Anyone can guess how could it happen?
![image](https://user-images.githubusercontent.com/88098184/127516102-d8fa099d-99b7-446c-a3e8-2696b1819a5f.png)

**Comment by setchy** [comment]
Hi @dmtrkuzmin - that would be a question best directed to the [graphql-java team](https://github.com/graphql-java/graphql-java) (either as an issue or a discussion)

We'll update to graphql-java:17 shortly after it has been released.  That will likely coincide with graphql-java-kickstart v12.0.0

**Comment by setchy** [comment]
@softshape https://github.com/graphql-java-kickstart/graphql-spring-boot/pull/679 

Some items we need to resolve, along with waiting for a 17.0 version of graphql-java-annotations.  I made a [draft PR](https://github.com/Enigmatis/graphql-java-annotations/pull/272) for that repo this morning

**Comment by softshape** [comment]
> @softshape see #679. Some items we need to resolve, along with waiting for a 17.0 version of graphql-java-annotations. I made a [draft PR](https://github.com/Enigmatis/graphql-java-annotations/pull/272) for that repo this morning

graphql-java-annotations is updated, see https://github.com/Enigmatis/graphql-java-annotations/releases/tag/v9.0

**Comment by setchy** [comment]
@softshape - you're on the ball.

graphql-java released 17.2 only a few days ago with a [handful of fixes](https://github.com/graphql-java/graphql-java/milestone/36?closed=1).   We're looking to have https://github.com/Enigmatis/graphql-java-annotations/pull/280 and https://github.com/graphql-java-kickstart/graphql-java-tools/pull/575 merged and re-released

**Comment by setchy** [comment]
https://github.com/graphql-java-kickstart/graphql-spring-boot/pull/711

**Comment by setchy** [comment]
@oliemansm - annotations and tools both updated to 17.2.  Next is to release servlet 12.0.0

**Comment by softshape** [comment]
> Next is to release servlet 12.0.0

Any plans for that?

**Comment by oliemansm** [comment]
@softshape We'll have to double check any open issues and then release it. Will try to do that this weekend.
