### ISSUE TITLE
/graphql endpoint is not exposed with Spring Boot 2.6.2

### ISSUE THREAD

**Issue by sergeivisotsky** [graphql-java-kickstart/graphql-spring-boot#780]
**Describe the bug**
Adding all required dependencies, e.g. (all of them have the latest versions and Spring Boot 2.6.2) :

```xml
<dependency>
    <groupId>com.graphql-java</groupId>
    <artifactId>graphql-java</artifactId>
</dependency>
<dependency>
    <groupId>com.graphql-java</groupId>
    <artifactId>graphql-java-extended-scalars</artifactId>
</dependency>
<dependency>
    <groupId>com.graphql-java-kickstart</groupId>
    <artifactId>graphql-spring-boot-starter</artifactId>
</dependency>
<dependency>
    <groupId>com.graphql-java-kickstart</groupId>
    <artifactId>graphiql-spring-boot-starter</artifactId>
</dependency>
``` 

Also all graphQL schemas a properly created as well as Query Resolvers are also properly defined. `/graphql` endpoint is not exposed. 

**To Reproduce**
1. Create Spring Boot 2.6.2 project
2. Add graphql dependencies
3. Create schemas
4. Create query resolvers from these schemas
5. Start application and try to reach `/graphql` endpoint
5. Face issue

**Expected behavior**
`/graphql` endpoint is accessible.

**Desktop (please complete the following information):**
- OS: MacOS 12.1
- Browser: Chrome 97.0.4692.99

**Comment by oliemansm** [comment]
Don't include graphql-Java yourself, but let it be pulled in. I can't reproduce this. Have no problems with 2.6.2 or 2.6.3. Recheck your local config please and try to create and share a minimal example project reproducing the issue.

You might want to enable spring boot debug to be able to analyze spring boot issues explaining why it's not being exposed.

**Comment by sergeivisotsky** [comment]
@oliemansm I see. You are right, you already have these dependencies in your starters' POM. By the way is it required to define a `GraphQLSchema` bean?

**Comment by oliemansm** [comment]
It's not if you use GraphQL Java tools. Assuming that's what you want to use then you're missing that dependency. Since version 12 you need to explicitly add the GraphQL Java tools starter as a dependency too. See the sample project in the samples repo. The graphiql starter is no longer in use, since it's included in the main starter and configurable through props.

**Comment by sergeivisotsky** [comment]
yes, you are right. w/ simple project it works. probably some issues w/ setup.

closing issue.

thanks!
