### ISSUE TITLE
getGraphQlContext has an empty value.

### ISSUE THREAD

**Issue by 13klove** [graphql-java-kickstart/graphql-spring-boot#796]
getGraphQlContext has an empty value.

spring boot webflux 2.5.10 
java 11
com.graphql-java-kickstart graphql-spring-boot-starter 12.0.0

I tried to use getContext from DataFetchingEnvironment , but it was deprecated and I tried to use getGraphQlContext but it is empty.

Even if you try to create a custom context by referring to the tutorial, it is empty. Confirmation is required.
(https://www.youtube.com/watch?v=YsM2VSnWUcg&list=PLiwhu8iLxKwL1TU0RMM6z7TtkyW-3-5Wi&index=21)

If it is not a bug, please guide.

**Comment by oliemansm** [comment]
Support for `getGraphQlContext` has been added to v13. Values can be retrieved from that context map like `environment.getGraphQlContext().get(ServerWebExchange.class)`
