### ISSUE TITLE
v12.0,how use GraphQLServletContext? 

### ISSUE THREAD

**Issue by NoBugBoy** [graphql-java-kickstart/graphql-spring-boot#808]
getContext(); is deprecated, how can I retrieve HttpServletRequest from DataFetchingEnvironment?

**Comment by NoBugBoy** [comment]
in Instrumentation can not use RequestContextHolder.getRequestAttributes();

**Comment by oliemansm** [comment]
As you've noticed v12 does not support `environment.getGraphQLContext()` yet. Support has been added to v13.0.0. You can retrieve the request from the context as follows:

```java
var httpServletRequest = (HttpServletRequest) environment.getGraphQlContext().get(HttpServletRequest.class);
```
