### ISSUE TITLE
Integration Test fails, /graphql enpoint not found

### ISSUE THREAD

**Issue by gigo1980** [graphql-java-kickstart/graphql-spring-boot#82]
If i try to execute an integration test the graphql endpoint is not found, the test returns a "404"

```java
RunWith(SpringRunner.class)
@SpringBootTest(
        webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureMockMvc
@EnableConfigurationProperties(GraphQLServletProperties.class)
@TestPropertySource(
        locations = "classpath:application-integrationtest.yaml")
public class GraphQlControllerTest {


    @Autowired
    private MockMvc mvc;


    @Test
    public void myTests() throws Exception {
        String request = "{\"query\": \"query{groups{id}}\", \"variables\": null}";
        ResultActions response = mvc.perform(post("/graphql").content(request).contentType(MediaType.APPLICATION_JSON));

        response.andExpect(status().isOk());
    }
}
```

output of the test is:
```
MockHttpServletRequest:
      HTTP Method = POST
      Request URI = /graphql
       Parameters = {}
          Headers = {Content-Type=[application/json;charset=UTF-8]}

Handler:
             Type = org.springframework.web.servlet.resource.ResourceHttpRequestHandler

Async:
    Async started = false
     Async result = null

Resolved Exception:
             Type = null

ModelAndView:
        View name = null
             View = null
            Model = null

FlashMap:
       Attributes = null

MockHttpServletResponse:
           Status = 404
    Error message = null
          Headers = {}
     Content type = null
             Body = 
    Forwarded URL = null
   Redirected URL = null
          Cookies = []

java.lang.AssertionError: Status 
Expected :200
Actual   :404
```

has anyone an working example for writing integration tests?

**Comment by oliemansm** [comment]
@gigo1980 I've added a `graphql-spring-boot-starter-test` package which should make it easier to write integration tests. It provides the `@GraphQLTest` annotation which is comparable to the `@WebMvcTest` annotation. So it only loads GraphQL related environment and classes, and by default sets up a webserver with random port to send GraphQL queries to.

To help you with sending those you can have the `GraphQLTestTemplate` autowired in your test class. That's available if you run a test with the `@GraphQLTest` annotation. You can store your GraphQL queries in files on the classpath, e.g. in  `src/test/resources/graphql/groups.graphql`. Then you can post it to your endpoint like this:
```java
GraphQLResponse response = graphQLTestTemplate.postForResource("graphql/groups.graphql");
```
The response supports JSONPath, which means you can easily verify the responses:
```java
assertEquals("1", response.get("$.data.group.id"));
```
It's still a work in progress, but should be workable already for most use cases. Didn't get around to write a proper README for it yet, so for now consider this to be the instructions. 

Also take a look at `GraphQLToolsSampleApplicationTest` in **example-graphql-tools**. That contains a working example.

**Comment by Thinkenterprise** [comment]
I also have problems with the test. I also get the error 404 in the GraphQLResult. The loading of the test query getAllRoutes.graphql works, that I have checked. I think the problem is that the application will not start up, because the spring beans will not be created. I have set a few breakpoints that are not called. 

The https://github.com/Thinkenterprise/spring-boot-graphql 

Here is the excerpt from my test. 

``` java
@RunWith(SpringRunner.class)
@GraphQLTest
public class GraphQLRouteTest {

   @Autowired
    private GraphQLTestTemplate graphQLTestTemplate;

    @Test
    public void routes() throws IOException {
        GraphQLResponse response = graphQLTestTemplate.postForResource("getAllRoutes.graphql");
        assertNotNull(response);
        assertTrue(response.isOk());
        assertEquals("1", response.get("$.data.routes.id"));
    }

}

```

**Comment by jaggerwang** [comment]
@oliemansm The` @GraphQLTest` annotation is not convinient as `MockMvc`, such as it not support using `@WithUserDetails` to specify login user. I have the same problem too.

```java
package net.jaggerwang.sbip.api;

...

@SpringBootTest()
@AutoConfigureMockMvc
@ActiveProfiles("test")
@Sql({"/db/init-db-test.sql"})
@Sql(scripts = {"/db/clean-db-test.sql"}, executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD)
@EnabledIfSystemProperty(named = "test.api.enabled", matches = "true")
public class UserGraphQLApiTests {
    @Autowired
    private MockMvc mvc;

    @Value("${graphql.servlet.mapping}")
    private String graphqlServletMapping;

    @Autowired
    private ObjectMapper objectMapper;

    @Test
    void register() throws Exception {
        var userEntity = UserEntity.builder().username("jagger001").password("123456").build();
        var content = new ObjectMapper().createObjectNode();
        content.put("query", "mutation($user: UserInput!) { userRegister(user: $user) { id username } }");
        content.putObject("variables").putObject("user").put("username", userEntity.getUsername()).put("password", userEntity.getPassword());
        mvc.perform(post(graphqlServletMapping).contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(content))).andExpect(status().isOk())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.errors").doesNotExist())
                .andExpect(jsonPath("$.data.userRegister.username").value(userEntity.getUsername()));
    }

    ...
}

```

The full code be found at https://github.com/jaggerwang/spring-boot-in-practice.

**Comment by Sam-Kruglov** [comment]
I came to the conclusion that MockMvc is not supposed to be used for testing raw servlets, as here we are not exposing `/graphql` endpoint as a Spring MVC Controller, but rather as a raw `HttpServlet`.

The following works for me quite nicely:
```
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.test.autoconfigure.web.reactive.AutoConfigureWebTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.web.reactive.server.WebTestClient;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureWebTestClient
public class AbstractGraphQLTest {

    @SpringBootApplication
    static class App {

    }

    @Autowired
    private WebTestClient webTestClient;

    @Autowired
    private ObjectMapper mapper;

    private String json(String query) throws JsonProcessingException {
        ObjectNode node = mapper.createObjectNode();
        node.put("query", query);
        return mapper.writeValueAsString(node);
    }

    protected WebTestClient.BodyContentSpec graphql(String query) throws JsonProcessingException {
        return webTestClient.post()
                .uri("/graphql")
                .bodyValue(json(query))
                .exchange()
                .expectBody();
    }

}
```
and then:
```
class default_handler extends AbstractGraphQLTest {

        @Test
        void expected_error__message_from_error() throws IOException {
            graphql("{illegalArgumentException}")
                    .jsonPath("errors[0].message").isEqualTo(EXPECTED_ERROR_MESSAGE)
                    .jsonPath("data.illegalArgumentException").doesNotExist();
        }
}
```

**Comment by wbf22** [comment]
this worked for me courtesy of chatgpt:

`
package ad.attractions.controller;

import ad.attractions.AbstractTestContainerSetup;
import ad.attractions.AttractionsApiApplication;
import ad.attractions.repository.AttractionRepository;
import ad.attractions.repository.ProductRepository;
import ad.attractions.service.api.AttractionsService;
import ad.attractions.test.data.TestMockDataService;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.graphql.spring.boot.test.GraphQLResponse;
import com.graphql.spring.boot.test.GraphQLTestTemplate;
import io.restassured.http.Header;
import io.restassured.response.ValidatableResponse;
import org.hamcrest.Matchers;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.core.io.DefaultResourceLoader;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.TestPropertySource;

import java.io.IOException;
import java.util.List;
import java.util.Optional;

import static ad.attractions.enums.AttractionCategory.THEME_PARK;
import static io.restassured.RestAssured.given;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.when;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class AttractionsControllerTest {

    @LocalServerPort
    private int port;

    @MockBean
    private AttractionRepository attractionRepository;
    @MockBean
    private ProductRepository productRepository;

    static final String BASE_URL = "/v1/attractions";

    @Autowired
    private TestRestTemplate testRestTemplate;

    private GraphQLTestTemplate graphQLTestTemplate;

    @Test
    void test_attractionDetails() throws IOException {
        graphQLTestTemplate = new GraphQLTestTemplate(
                new DefaultResourceLoader(),
                testRestTemplate,
                "/v1/attraction/attractionsDetails",
                new ObjectMapper());

        when(attractionRepository.getAttractions(anyString())).thenReturn(
                List.of(TestMockDataService.testAttractionView("attr_456", "Test Park", THEME_PARK.name()))
        );

        when(attractionRepository.getAttraction(anyString())).thenReturn(
                Optional.of(TestMockDataService.testAttractionView("attr_456", "Test Park", THEME_PARK.name()))
        );

        when(productRepository.getProducts( anyString(), any()) ).thenReturn(
                List.of(
                        TestMockDataService.testProductView( "SKU_123", "3 Day Park Hopper", "park_hopper", "adult"),
                        TestMockDataService.testProductView( "SKU_456", "3 Day Park Hopper", "park_hopper", "child")
                )
        );

        String query = "query getAttractions { attractionsDetails (programKey : \"1234\") { attractionUrlId name description products{ name } brand { name } location { country } apiIntegration } }";

        GraphQLResponse response = graphQLTestTemplate.postForString(query);

        assertNotNull(response);
        assertEquals("attr_456", response.get("$.data.attractionsDetails[0].attractionUrlId"));
        assertEquals("Test Park", response.get("$.data.attractionsDetails[0].name"));
        assertEquals("some desc", response.get("$.data.attractionsDetails[0].description"));
        assertEquals("3 Day Park Hopper", response.get("$.data.attractionsDetails[0].products[0].name"));
        assertEquals("3 Day Park Hopper", response.get("$.data.attractionsDetails[0].products[1].name"));
        assertEquals("GALAXY_CONNECT", response.get("$.data.attractionsDetails[0].apiIntegration"));
    }
}
`

**Comment by wbf22** [comment]
I was having trouble with the @GraphQlTest annotation fighting with the @SpringBootTest annotation, so getting the GraphQLTestTemplate I was able to access to the endpoint with still using the @SpringBootTest. I'm not exactly sure how it worked but it did yay
