### ISSUE TITLE
graphiql-spring-boot-starter version is still 11.1.0 not 14.0.0?

### ISSUE THREAD

**Issue by aihua5** [graphql-java-kickstart/graphql-spring-boot#879]
graphql-spring-boot-starter has been upgrade to latest 14.0.0, why is the graphiql 11.10?
Do you have any plan to upgrade the graphiql?

**Comment by oliemansm** [comment]
Starters have been reorganized in v12.0.0, see: https://github.com/graphql-java-kickstart/graphql-spring-boot/pull/617

**Comment by aihua5** [comment]
Thank your quick reply. Now I changed grapiql to graphql like below:
graphql:
  graphiql:
    enabled: true
    headers:
      test: test


But some starting error is popped up:

Description:

The bean 'graphiQLController', defined in class path resource [graphql/kickstart/graphiql/boot/GraphiQLAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [graphql/kickstart/autoconfigure/editor/graphiql/GraphiQLAutoConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

Could you give some comments?

**Comment by oliemansm** [comment]
Sounds like you didn't remove the old graphiql starter from your dependencies.

**Comment by aihua5** [comment]
Thank you. I have resolved the issue after deleting the old graphiql starter. It is amazing. :)
