### ISSUE TITLE
Spring Boot 3.0.0 / Jakarta EE 9 (jakarta.* namespace) support

### ISSUE THREAD

**Issue by ajgassner** [graphql-java-kickstart/graphql-spring-boot#894]
Today Spring Boot 3.0.0 has been released. It uses Jakarta EE 9 under the hood.

The current version of graphql-spring-boot is not API compatible with jakarta.* and it uses the good old javax.* Servlet API for e.g. GraphQLServletContextBuilder

Is there any plan to support Spring Boot 3.0.0 in the near future?

**Comment by oliemansm** [comment]
See https://github.com/graphql-java-kickstart/graphql-java-servlet/pull/485 and https://github.com/graphql-java-kickstart/graphql-java-servlet/discussions/487

**Comment by oliemansm** [comment]
Included in just released version 15.0.0
