### ISSUE TITLE
Maven seems to confuse graphql-java version

### ISSUE THREAD

**Issue by KammererTob** [graphql-java-kickstart/graphql-spring-boot#957]
**Describe the bug**
I have updated to 15.1.0 of the javax flavor and i noticed that my instrumentation is no longer working, because a version mismatch.
It loads graphql-java 18.5, while 15.1.0 expects classes from at least version 19 (i believe), specifically `SimplePerformantInstrumentation` and a casting issue between `DataLoaderDispatcherInstrumentationState` provided by graphql-java and graphql-java-kickstart

This is the dependency in my pom.xml
```
        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-spring-boot-starter-javax</artifactId>
            <version>15.1.0</version>
        </dependency>
```

IntelliJ does not show any conflict of versions:
![image](https://github.com/graphql-java-kickstart/graphql-spring-boot/assets/1510949/09906e77-1c23-4836-826e-f886af3b660e)

`mvn dependency:tree` seems to show graphql-java-tools as the culprit (although the dependency also looks correct in there) - posting a screenshot since the formatting gets destroyed when pasting here:
![image](https://github.com/graphql-java-kickstart/graphql-spring-boot/assets/1510949/fb41ba38-49ab-4cde-87bb-d076836c2d38)

I have re-imported the project multiple times, but still the same 18.5 version. Any idea why this happens?

**Desktop (please complete the following information):**
- OS: Windows 10 Pro

**Comment by KammererTob** [comment]
@oliemansm Sorry about opening this as a bug. Do you happen to know why this doesn't show up in the maven dependency analysis (or am i blind)? That was mostly the reason why i thought it was a bug.

**Comment by oliemansm** [comment]
I don't know enough about that kind of thing to give a definitive answer on that. Afaik the bill of materials provided by Spring enforces that if no specific version of graphql-java is explicitly imported, and some dependency pulls in graphql-java it then somehow overrules the version requested by the dependency (kickstart in this case) and thus forces the version indicated in the BOM. Unless you manually override that version as indicated.

**Comment by KammererTob** [comment]
Alright. Thanks for your help. Manually defining the dependency fixes the issue!
