### ISSUE TITLE
Async Option (Spring Reactor) available/planned?

### ISSUE THREAD

**Issue by hartmut-co-uk** [graphql-java-kickstart/graphql-spring-boot#99]
Hi, I was wondering if there are plans to support async operations via spring reactor?
I think it would really play well with relations - when e.g. working with NoSQL dbs like Cassandra/Elasticsearch/MongoDB/Redis which already come with async client libs...

**Comment by hartmut-co-uk** [comment]
different 'use case', `MediaType.TEXT_EVENT_STREAM_VALUE`...
but e.g. found as a reference: https://github.com/bsideup/graphql-java-reactive/tree/master/examples/spring-boot

**Comment by oliemansm** [comment]
@hartmut-co-uk Take a look at https://github.com/graphql-java/graphql-spring-boot/tree/master/example-graphql-subscription. Is this what you mean?

**Comment by hartmut-co-uk** [comment]
Thanks @oliemansm - not quite - it's using _RxJava_ as the reactivestreams impl. vs. _Reactor_ - but it's still built on top of servlets / MVC (`spring-boot-starter-web`) vs. async/netty (`spring-boot-starter-webflux`).

**Comment by oliemansm** [comment]
@hartmut-co-uk Ah, that clarifies it for me. There are no plans that I know of. This particular project tries to make it easy to enable various existing graphql-java technologies. Sounds like a good idea. Have you looked if there is any other graphql project already doing that which could be integrated?

**Comment by hartmut-co-uk** [comment]
Thanks, the tiny example I referenced in my initial post. 
Using the `com.github.bsideup.graphql.reactive.ReactiveExecutionStrategy` of the actual library https://github.com/bsideup/graphql-java-reactive

**Comment by yonigibbs** [comment]
@bjartek, if it's of any use to you, @geowarin created an example with non-reactive GraphQL handling in a Spring Boot application [here](https://github.com/geowarin/graphql-webflux).  I forked it [here](https://github.com/yonigibbs/graphql-webflux-dataloader) and added a bunch of stuff, one of which is the use of [reactive-pg-client](https://github.com/reactiverse/reactive-pg-client/) for non-blocking DB access, as you said in your original post here (reactive-pg-client is for Postgres, not a NoSQL DB, but the same approach would apply there).  It's not a version of this starter, as you hoped for, but hopefully it might be of some use.

**Comment by oliemansm** [comment]
@hartmut-co-uk The guys from graphql-java created a Spring starter of their own now which supports webflux, see: https://github.com/graphql-java/graphql-java-spring.

**Comment by oliemansm** [comment]
Closing this issue since the most straightforward approach to support this now seems to be the https://github.com/graphql-java/graphql-java-spring project.

**Comment by aschrijver** [comment]
Some confusion (note: this project is not causing it): In [graphql-java blog](https://www.graphql-java.com/blog/moving-projects/) there is announcement that graphql-java-kickstart is the new home for `graphql-spring-boot` and then 2 months later they announce [First Release of GraphQL Java Spring](https://www.graphql-java.com/blog/moving-projects/).

So you both offer the Spring MVC graphql road ahead. But for webflux only graphql-java is the way to go.

**Comment by oliemansm** [comment]
@aschrijver Yeah, that's correct and was a bit surprising too, to be honest. Right now this project doesn't support webflux, and haven't looked into adding it yet. The graphql-spring lib from graphql-java promotes direct usage and wiring, where this lib provides graphql-java-tools as a means for wiring your schema, besides the ability to do it manually. 

Haven't looked at their spring project tbh, and don't know what other differences there are atm.
